#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Period 5: Transición, Postmodernismo y Apertura (1975 – 1999)"""

period_5 = [
    {
        "id": "edificio-consorcio-santiago",
        "nombre_proyecto": "Edificio Consorcio Nacional de Seguros",
        "arquitecto": "Enrique Browne y Borja Huidobro",
        "arquitecto_principal": "Enrique Browne & Borja Huidobro",
        "colaboradores": "Paulina Courard, Patricio Morelli",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. El Bosque Sur 130",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4172, "lng": -70.5989},
        "ano_diseno": "1990",
        "anos_construccion": "1990-1993",
        "ano_inauguracion": "1993",
        "estilos": ["Posmodernismo", "High-Tech"],
        "programa": ["Comercial"],
        "descripcion": "Edificio corporativo pionero en bio-arquitectura y sustentabilidad en América Latina, célebre por su muro cortina curvo de 3.000 m² de enredaderas verticales que regulan naturalmente la temperatura interior.",
        "fuente_url": "https://www.enriquebrowne.cl",
        "materiales_principales": ["Hormigón armado", "Vidrio termopanel", "Jardín vertical vegetal", "Metal"]
    },
    {
        "id": "pabellon-chile-expo-sevilla-92",
        "nombre_proyecto": "Pabellón de Chile en la Expo Sevilla '92",
        "arquitecto": "José Cruz Ovalle y Guillermo Acuña",
        "arquitecto_principal": "José Cruz Ovalle",
        "colaboradores": "Guillermo Acuña",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Isla de la Cartuja (original) / Parque O'Higgins (reinstalación)",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4650, "lng": -70.6583},
        "ano_diseno": "1990",
        "anos_construccion": "1991-1992",
        "ano_inauguracion": "1992",
        "estilos": ["Organicismo", "Posmodernismo"],
        "programa": ["Cultural"],
        "descripcion": "Estructura curva construida en madera laminada de pino radiata chileno que cobijó un iceberg milenario transportado desde la Antártica durante la Exposición Universal de Sevilla 1992, marcando el retorno democrático de Chile.",
        "fuente_url": "https://www.josecruzovalle.cl",
        "materiales_principales": ["Madera laminada encolada", "Cobre", "Acero"]
    },
    {
        "id": "hotel-explora-patagonia",
        "nombre_proyecto": "Hotel Explora Patagonia",
        "arquitecto": "Germán del Sol y José Cruz Ovalle",
        "arquitecto_principal": "Germán del Sol",
        "colaboradores": "José Cruz Ovalle",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Salto Chico, Lago Pehoé, Parque Nacional Torres del Paine",
        "ciudad": "Torres del Paine",
        "pais": "Chile",
        "coordenadas": {"lat": -51.1167, "lng": -73.0167},
        "ano_diseno": "1989",
        "anos_construccion": "1990-1993",
        "ano_inauguracion": "1993",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Hospedaje"],
        "descripcion": "Obra de culto de la arquitectura del paisaje mundial. Un volumen blanco esculpido que descansa frente a la cascada del Salto Chico y los Cuernos del Paine, con interiores cálidos de madera de lenga.",
        "fuente_url": "https://www.germandelsol.com",
        "materiales_principales": ["Madera de lenga patagónica", "Acero blanco", "Vidrio panorámico"]
    },
    {
        "id": "hotel-explora-atacama",
        "nombre_proyecto": "Hotel Explora Atacama",
        "arquitecto": "Germán del Sol",
        "arquitecto_principal": "Germán del Sol",
        "colaboradores": "Equipo Germán del Sol Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Ayllu de Larache, San Pedro de Atacama",
        "ciudad": "San Pedro de Atacama",
        "pais": "Chile",
        "coordenadas": {"lat": -22.9194, "lng": -68.2056},
        "ano_diseno": "1996",
        "anos_construccion": "1997-1998",
        "ano_inauguracion": "1998",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Hospedaje"],
        "descripcion": "Diseñado en el ayllu histórico de Larache con patios continuos, muros de adobe encalados, pasarelas de madera y piscinas termales que reinterpretan la sabiduría ancestral del desierto atacameño.",
        "fuente_url": "https://www.germandelsol.com",
        "materiales_principales": ["Adobe", "Madera", "Piedra pómez", "Agua"]
    },
    {
        "id": "centro-de-extension-puc-santiago",
        "nombre_proyecto": "Centro de Extensión PUC",
        "arquitecto": "Emilio Soyer",
        "arquitecto_principal": "Emilio Soyer",
        "colaboradores": "Pontificia Universidad Católica de Chile",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Libertador Bernardo O'Higgins 390",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4411, "lng": -70.6419},
        "ano_diseno": "1986",
        "anos_construccion": "1987-1988",
        "ano_inauguracion": "1988",
        "estilos": ["Posmodernismo"],
        "programa": ["Cultural", "Educacional"],
        "descripcion": "Intervención posmoderna junto a la Casa Central de la PUC que crea una galería peatonal cubierta de doble altura conectando la Alameda con el interior de la manzana universitaria a través de galerías de arte y salas de cine.",
        "fuente_url": "https://www.uc.cl",
        "materiales_principales": ["Ladrillo prensado", "Hormigón", "Madera", "Lucernarios de vidrio"]
    },
    {
        "id": "edificio-plaza-mulato-gil-de-castro",
        "nombre_proyecto": "Edificio Plaza Mulato Gil de Castro",
        "arquitecto": "Cristián Boza",
        "arquitecto_principal": "Cristián Boza",
        "colaboradores": "Manuel Moreno, Hernán Riesco",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "José Victorino Lastarria 307",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4383, "lng": -70.6406},
        "ano_diseno": "1979",
        "anos_construccion": "1980-1981",
        "ano_inauguracion": "1981",
        "estilos": ["Posmodernismo"],
        "programa": ["Cultural", "Comercial"],
        "descripcion": "Operación de reciclaje urbano y lenguaje posmoderno que detonó el renacimiento cultural del Barrio Lastarria. Articula una plaza pública interior con el Museo de Artes Visuales (MAVI) y cafés.",
        "fuente_url": "https://www.mavi.cl",
        "materiales_principales": ["Albañilería de ladrillo", "Hormigón", "Madera torneada"]
    },
    {
        "id": "edificio-mop-santiago",
        "nombre_proyecto": "MOP / Edificio del Ministerio de Obras Públicas",
        "arquitecto": "Emilio Duhart y asociados",
        "arquitecto_principal": "Emilio Duhart",
        "colaboradores": "Rolf Behncke, Jorge Elton",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Morandé 59",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4419, "lng": -70.6542},
        "ano_diseno": "1987",
        "anos_construccion": "1988-1990",
        "ano_inauguracion": "1990",
        "estilos": ["Posmodernismo", "Racionalismo"],
        "programa": ["Institucional / Gubernamental"],
        "descripcion": "Completación del Barrio Cívico de La Moneda proyectada por Emilio Duhart, respetando la normativa volumétrica histórica y reinterpretando el orden del zócalo y ático cívico republicano.",
        "fuente_url": "https://www.mop.gob.cl",
        "materiales_principales": ["Hormigón armado", "Revestimiento pétreo reconstituido", "Vidrio"]
    },
    {
        "id": "facultad-de-matematicas-uc",
        "nombre_proyecto": "Facultad de Matemáticas UC (Edificio Rolando Chuaqui)",
        "arquitecto": "Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Equipo docente UC",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Campus San Joaquín UC, Macul/San Joaquín",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4989, "lng": -70.6128},
        "ano_diseno": "1998",
        "anos_construccion": "1998-1999",
        "ano_inauguracion": "1999",
        "estilos": ["Brutalismo", "Racionalismo"],
        "programa": ["Educacional"],
        "descripcion": "Una de las primeras obras maestras de Alejandro Aravena (Premio Pritzker 2016). Bloque escultórico de hormigón armado perforado con galerías de sombra y muros inclinados diseñados para el aislamiento del pensamiento matemático.",
        "fuente_url": "https://www.elementalchile.cl",
        "materiales_principales": ["Hormigón armado visto", "Madera", "Vidrio"]
    },
    {
        "id": "museo-interactivo-mirador-mim",
        "nombre_proyecto": "Museo Interactivo Mirador (MIM)",
        "arquitecto": "Eduardo Baixas y Enrique del Río",
        "arquitecto_principal": "Eduardo Baixas",
        "colaboradores": "Enrique del Río, Baixas y Del Río Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Punta Arenas 6711, Parque Brasil",
        "ciudad": "La Granja",
        "pais": "Chile",
        "coordenadas": {"lat": -33.5208, "lng": -70.6186},
        "ano_diseno": "1998",
        "anos_construccion": "1998-1999",
        "ano_inauguracion": "1999",
        "estilos": ["Deconstructivismo", "High-Tech"],
        "programa": ["Cultural", "Educacional"],
        "descripcion": "El mayor museo de ciencias interactivo de Chile, ubicado en un parque urbano en la zona sur de Santiago. Volumen escultórico revestido en madera de coigüe y cobre pulido con grandes vigas en voladizo.",
        "fuente_url": "https://www.mim.cl",
        "materiales_principales": ["Madera nativa laminada", "Cobre chileno", "Hormigón visto", "Vidrio"]
    },
    {
        "id": "colegio-huelquen-montessori-santiago",
        "nombre_proyecto": "Colegio Huelquén Montessori",
        "arquitecto": "Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Equipo docente Montessori",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Las Perdices, Peñalolén",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4833, "lng": -70.5333},
        "ano_diseno": "1999",
        "anos_construccion": "2000-2001",
        "ano_inauguracion": "2001",
        "estilos": ["Racionalismo", "Minimalismo"],
        "programa": ["Educacional"],
        "descripcion": "Obra educacional temprana de Alejandro Aravena, estructurada como una calle interior techada con luz cenital donde las salas de clase se abren para fomentar el aprendizaje autónomo.",
        "fuente_url": "https://www.elementalchile.cl",
        "materiales_principales": ["Albañilería de ladrillo", "Hormigón", "Madera"]
    },
    {
        "id": "casa-en-vilches-smiljan-radic",
        "nombre_proyecto": "Casa en Vilches",
        "arquitecto": "Smiljan Radic",
        "arquitecto_principal": "Smiljan Radic",
        "colaboradores": "Marcela Correa",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Vilches Alto, Precordillera del Maule",
        "ciudad": "Vilches, Región del Maule",
        "pais": "Chile",
        "coordenadas": {"lat": -35.6000, "lng": -71.1833},
        "ano_diseno": "1996",
        "anos_construccion": "1996-1997",
        "ano_inauguracion": "1997",
        "estilos": ["Minimalismo", "Organicismo"],
        "programa": ["Vivienda"],
        "descripcion": "Pionero refugio de montaña de Smiljan Radic, posado discretamente en un bosque de robles y canelos precordillerano con estructura de madera oscura y grandes ventanales sin marco.",
        "fuente_url": "https://www.plataformaarquitectura.cl",
        "materiales_principales": ["Madera carbonizada", "Vidrio", "Piedra de río"]
    },
    {
        "id": "casa-de-las-vigas-pirque",
        "nombre_proyecto": "Casa de las Vigas",
        "arquitecto": "Smiljan Radic",
        "arquitecto_principal": "Smiljan Radic",
        "colaboradores": "Marcela Correa",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Camino San Juan de Pirque",
        "ciudad": "Pirque",
        "pais": "Chile",
        "coordenadas": {"lat": -33.6667, "lng": -70.5833},
        "ano_diseno": "1999",
        "anos_construccion": "2000-2002",
        "ano_inauguracion": "2002",
        "estilos": ["Minimalismo", "Organicismo"],
        "programa": ["Vivienda"],
        "descripcion": "Residencia construida en el valle rural de Pirque con una cubierta soportada por masivas vigas de madera sin labrar apoyadas sobre bloques rústicos de granito, combinando primitivismo y sofisticación.",
        "fuente_url": "https://www.plataformaarquitectura.cl",
        "materiales_principales": ["Rocas de granito", "Vigas de madera bruta", "Vidrio templado"]
    },
    {
        "id": "edificio-manantiales-santiago",
        "nombre_proyecto": "Edificio Manantiales",
        "arquitecto": "Luis Izquierdo, Antonia Lehmann, Raimundo Lira, Juan Domingo Peñafiel",
        "arquitecto_principal": "Luis Izquierdo & Antonia Lehmann",
        "colaboradores": "Raimundo Lira, Juan Domingo Peñafiel",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Isidora Goyenechea 3250",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4147, "lng": -70.5986},
        "ano_diseno": "1997",
        "anos_construccion": "1997-1999",
        "ano_inauguracion": "1999",
        "estilos": ["Minimalismo", "Racionalismo"],
        "programa": ["Comercial"],
        "descripcion": "Edificio corporativo que obtuvo el Premio Nacional de Arquitectura, reconocido por su precisa modulación de hormigón armado visto y su integración con el espacio peatonal del barrio El Golf.",
        "fuente_url": "https://www.izquierdolehmann.com",
        "materiales_principales": ["Hormigón armado visto", "Vidrio serigrafiado", "Granito pulido"]
    },
    {
        "id": "edificio-las-boza-santiago",
        "nombre_proyecto": "Edificio Las Boza",
        "arquitecto": "Cristián Boza",
        "arquitecto_principal": "Cristián Boza",
        "colaboradores": "Cristián Boza y Asociados",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Vitacura con Las Tranqueras",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.3917, "lng": -70.5611},
        "ano_diseno": "1985",
        "anos_construccion": "1985-1986",
        "ano_inauguracion": "1986",
        "estilos": ["Posmodernismo"],
        "programa": ["Comercial"],
        "descripcion": "Notable hito de la arquitectura comercial posmoderna chilena de los años ochenta, articulando columnatas clasicistas reinterpretadas, arquerías y una paleta cromática de gran notoriedad visual.",
        "fuente_url": "https://www.plataformaarquitectura.cl",
        "materiales_principales": ["Hormigón armado", "Albañilería estucada y pintada", "Vidrio"]
    },
    {
        "id": "casa-en-panguipulli-klotz",
        "nombre_proyecto": "Casa en Panguipulli",
        "arquitecto": "Mathias Klotz",
        "arquitecto_principal": "Mathias Klotz",
        "colaboradores": "Klotz Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Riberas del Lago Panguipulli",
        "ciudad": "Panguipulli",
        "pais": "Chile",
        "coordenadas": {"lat": -39.6444, "lng": -72.3333},
        "ano_diseno": "1997",
        "anos_construccion": "1997-1998",
        "ano_inauguracion": "1998",
        "estilos": ["Minimalismo", "Racionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Volumen cúbico puro posado sobre una plataforma suspendida de madera que parece levitar sobre las aguas del lago Panguipulli, con fachadas transparentes hacia el volcán y los bosques nativos.",
        "fuente_url": "https://www.mathiasklotz.com",
        "materiales_principales": ["Madera nativa", "Estructura de acero", "Vidrio de piso a cielo"]
    },
    {
        "id": "casa-muller-chiloe-klotz",
        "nombre_proyecto": "Casa Müller",
        "arquitecto": "Mathias Klotz",
        "arquitecto_principal": "Mathias Klotz",
        "colaboradores": "Klotz Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Bahía de Caulín, Ancud",
        "ciudad": "Isla Grande de Chiloé",
        "pais": "Chile",
        "coordenadas": {"lat": -41.8167, "lng": -73.6000},
        "ano_diseno": "1990",
        "anos_construccion": "1990-1991",
        "ano_inauguracion": "1991",
        "estilos": ["Minimalismo"],
        "programa": ["Vivienda"],
        "descripcion": "La primera obra de Mathias Klotz construida a sus 25 años que catapultó su carrera internacionalmente. Una caja abstracta de madera de alerce y alerce patinado sobre pilotes frente a la marea chilota.",
        "fuente_url": "https://www.mathiasklotz.com",
        "materiales_principales": ["Madera de alerce y ciprés", "Tejuelas de alerce", "Pilotes de madera"]
    },
    {
        "id": "teatro-del-lago-frutillar",
        "nombre_proyecto": "Teatro del Lago",
        "arquitecto": "Gerardo Köster y Gustavo Greene",
        "arquitecto_principal": "Gerardo Köster",
        "colaboradores": "Gustavo Greene; acústica por Müller-BBM (Munich)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Philippi 1000",
        "ciudad": "Frutillar",
        "pais": "Chile",
        "coordenadas": {"lat": -41.1278, "lng": -73.0278},
        "ano_diseno": "1996",
        "anos_construccion": "1996-2010",
        "ano_inauguracion": "2010",
        "estilos": ["Organicismo", "Historicismo"],
        "programa": ["Cultural"],
        "descripcion": "Teatro internacional de conciertos construido sobre pilotes en el Lago Llanquihue con vistas al Volcán Osorno. Combina la calidez de las tejuelas de madera nativa con ingeniería acústica alemana de punta.",
        "fuente_url": "https://www.teatrodellago.cl",
        "materiales_principales": ["Madera de roble pellín, mañío y lenga", "Cobre", "Vidrio"]
    },
    {
        "id": "campus-uai-penalolen",
        "nombre_proyecto": "Campus Universidad Adolfo Ibáñez Peñalolén",
        "arquitecto": "José Cruz Ovalle",
        "arquitecto_principal": "José Cruz Ovalle",
        "colaboradores": "Hernán Cruz, Juan Purcell",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Diagonal Las Torres 2640",
        "ciudad": "Peñalolén",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4917, "lng": -70.5278},
        "ano_diseno": "1999",
        "anos_construccion": "1999-2002",
        "ano_inauguracion": "2002",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Educacional"],
        "descripcion": "Obra galardonada con el Premio Nacional de Arquitectura, emplazada en las laderas de la precordillera de Los Andes con muros curvos continuos de hormigón teñido y rampas que enmarcan la vista panorámica del valle de Santiago.",
        "fuente_url": "https://www.josecruzovalle.cl",
        "materiales_principales": ["Hormigón visto coloreado ocre", "Madera de cedro", "Cobre"]
    },
    {
        "id": "lofts-plaza-brasil-santiago",
        "nombre_proyecto": "Lofts Plaza Brasil",
        "arquitecto": "Francisco Vergara, María José Castillo, Margarita Murtinho, Alex Brahm",
        "arquitecto_principal": "Francisco Vergara",
        "colaboradores": "María José Castillo, Margarita Murtinho, Alex Brahm",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Huerfanos con Maturana, Barrio Brasil",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4389, "lng": -70.6667},
        "ano_diseno": "1997",
        "anos_construccion": "1997-1998",
        "ano_inauguracion": "1998",
        "estilos": ["Posmodernismo", "High-Tech"],
        "programa": ["Vivienda"],
        "descripcion": "Proyecto pionero en la recuperación patrimonial y reconversión habitacional del casco histórico de Santiago en lofts de doble altura con estructuras de acero visto y terrazas comunitarias.",
        "fuente_url": "https://www.plataformaarquitectura.cl",
        "materiales_principales": ["Estructura metálica a la vista", "Albañilería de ladrillo existente", "Vidrio"]
    },
    {
        "id": "centro-cultura-solidaridad-padre-hurtado",
        "nombre_proyecto": "Centro de la Cultura de la Solidaridad / Fundación Padre Hurtado",
        "arquitecto": "Cristián Undurraga",
        "arquitecto_principal": "Cristián Undurraga",
        "colaboradores": "Undurraga Devés Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. General Velásquez 1090",
        "ciudad": "Estación Central",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4583, "lng": -70.6861},
        "ano_diseno": "1994",
        "anos_construccion": "1994-1995",
        "ano_inauguracion": "1995",
        "estilos": ["Minimalismo", "Racionalismo"],
        "programa": ["Cultural", "Religioso"],
        "descripcion": "Espacio memorial y santuario subterráneo de serenidad absoluta en medio de la vorágine urbana de Estación Central, con patios excavados de ladrillo y hormigón bañado por luz mística cenital.",
        "fuente_url": "https://www.undurragadeves.cl",
        "materiales_principales": ["Ladrillo cocido", "Hormigón visto", "Agua en espejos reflexivos"]
    }
]

print(f"Period 5 defined: {len(period_5)} projects.")
