#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Period 6: Contemporáneo: Vivienda Social, Equipamiento Regional y Paisaje (2000 – Presente)"""

period_6 = [
    {
        "id": "quinta-monroy-iquique",
        "nombre_proyecto": "Viviendas Sociales Quinta Monroy",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Alfonso Monroy, Emilio de la Cerda, Gonzalo Arteaga, Juan Ignacio Cerda",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Pedro Prado con Las Rosas",
        "ciudad": "Iquique",
        "pais": "Chile",
        "coordenadas": {"lat": -20.2444, "lng": -70.1333},
        "ano_diseno": "2003",
        "anos_construccion": "2003-2004",
        "ano_inauguracion": "2004",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "El manifiesto mundial de la vivienda social incremental desarrollado por ELEMENTAL. Construye la mitad difícil e indivisible de una casa de clase media (estructura, cocina, baño), permitiendo que la familia complete la otra mitad con su propio esfuerzo y plusvalía.",
        "fuente_url": "https://www.elementalchile.cl/proyectos/quinta-monroy/",
        "materiales_principales": ["Bloque de hormigón celular", "Hormigón armado", "Madera", "Chapas de acero ondulado"]
    },
    {
        "id": "viviendas-sociales-renca",
        "nombre_proyecto": "Viviendas Sociales Renca",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Equipo ELEMENTAL",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Renca, sector poniente",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4000, "lng": -70.7167},
        "ano_diseno": "2006",
        "anos_construccion": "2006-2007",
        "ano_inauguracion": "2007",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Conjunto habitacional incremental de ELEMENTAL en Santiago poniente para familias vulnerables, densificando sin hacinar mediante tipologías pareadas ampliables hacia patios colectivos.",
        "fuente_url": "https://www.elementalchile.cl",
        "materiales_principales": ["Albañilería de bloques", "Hormigón", "Madera tratada"]
    },
    {
        "id": "viviendas-sociales-lo-barnechea",
        "nombre_proyecto": "Viviendas Sociales Lo Barnechea",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Gonzalo Arteaga, Juan Ignacio Cerda, Víctor Oddó",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Raúl Labbé con Monseñor Escrivá de Balaguer",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.3611, "lng": -70.5194},
        "ano_diseno": "2010",
        "anos_construccion": "2011-2012",
        "ano_inauguracion": "2012",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Proyecto incremental de alta densidad emplazado en uno de los municipios de mayores ingresos del país para retener a familias históricas de campamentos en su red laboral y educativa sin expulsarlas a la periferia lejana.",
        "fuente_url": "https://www.elementalchile.cl",
        "materiales_principales": ["Hormigón armado", "Albañilería", "Estructuras de madera ampliable"]
    },
    {
        "id": "villa-verde-constitucion",
        "nombre_proyecto": "Villa Verde",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Arauco (Forestal Arauco), Juan Ignacio Cerda",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Constitución, Región del Maule",
        "ciudad": "Constitución",
        "pais": "Chile",
        "coordenadas": {"lat": -35.3333, "lng": -72.4167},
        "ano_diseno": "2010",
        "anos_construccion": "2012-2013",
        "ano_inauguracion": "2013",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Barrio de 484 viviendas incrementales diseñado en madera estructural tras el terremoto y tsunami del 27F de 2010, permitiendo que la vivienda pase de 57 m² iniciales a 85 m² definitivos mediante autoconstrucción guiada.",
        "fuente_url": "https://www.elementalchile.cl/proyectos/villa-verde/",
        "materiales_principales": ["Madera aserrada y contrachapada de pino", "Hormigón en fundaciones", "Zinc"]
    },
    {
        "id": "conjunto-habitacional-la-maestranza-san-bernardo",
        "nombre_proyecto": "Conjunto Habitacional La Maestranza",
        "arquitecto": "Fernando Castillo Velasco / Walter Junge / Cooperativa de Vivienda",
        "arquitecto_principal": "Fernando Castillo Velasco",
        "colaboradores": "Walter Junge, Cooperativa de Vivienda La Maestranza",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Ex Maestranza Central de San Bernardo",
        "ciudad": "San Bernardo",
        "pais": "Chile",
        "coordenadas": {"lat": -33.5958, "lng": -70.7028},
        "ano_diseno": "2012",
        "anos_construccion": "2016-2019",
        "ano_inauguracion": "2019",
        "estilos": ["Racionalismo", "Organicismo"],
        "programa": ["Vivienda"],
        "descripcion": "Obra póstuma del célebre arquitecto Fernando Castillo Velasco, desarrollada en co-diseño comunitario con comités de allegados obreros en los antiguos terrenos de ferrocarriles, con pasajes vecinales y patios comunes.",
        "fuente_url": "https://www.minvu.cl",
        "materiales_principales": ["Albañilería de ladrillo a la vista", "Hormigón armado", "Madera"]
    },
    {
        "id": "torres-siamesas-uc",
        "nombre_proyecto": "Torres Siamesas UC",
        "arquitecto": "Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Emilio de la Cerda, Gonzalo Arteaga",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Campus San Joaquín UC, Macul",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4986, "lng": -70.6106},
        "ano_diseno": "2003",
        "anos_construccion": "2004-2005",
        "ano_inauguracion": "2005",
        "estilos": ["Deconstructivismo", "High-Tech"],
        "programa": ["Educacional"],
        "descripcion": "Doble torre de vidrio unida en su base que alberga el centro de tecnologías de información de la UC. Resuelve el calor del muro cortina acristalado creando una doble piel ventilada donde el aire caliente asciende por efecto chimenea.",
        "fuente_url": "https://www.elementalchile.cl/proyectos/torres-siamesas/",
        "materiales_principales": ["Vidrio templado reflectivo", "Hormigón armado visto", "Acero"]
    },
    {
        "id": "centro-innovacion-uc-angelini",
        "nombre_proyecto": "Centro de Innovación UC Anacleto Angelini",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Juan Ignacio Cerda, Gonzalo Arteaga, Víctor Oddó",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Vicuña Mackenna 4860, Campus San Joaquín",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4975, "lng": -70.6133},
        "ano_diseno": "2011",
        "anos_construccion": "2012-2014",
        "ano_inauguracion": "2014",
        "estilos": ["Brutalismo", "Minimalismo"],
        "programa": ["Educacional", "Institucional / Gubernamental"],
        "descripcion": "Edificio monolítico de hormigón premiado como Design of the Year internacional. Invierte el paradigma del edificio corporativo acristalado situando la masa opaca en el perímetro para eliminar la radiación solar y creando un atrio interior transparente para propiciar el encuentro humano casual.",
        "fuente_url": "https://www.elementalchile.cl/proyectos/centro-de-innovacion-uc-anacleto-angelini/",
        "materiales_principales": ["Hormigón armado visto pigmentado", "Madera natural", "Vidrio termopanel"]
    },
    {
        "id": "restaurante-mestizo-vitacura",
        "nombre_proyecto": "Restaurante Mestizo",
        "arquitecto": "Smiljan Radic",
        "arquitecto_principal": "Smiljan Radic",
        "colaboradores": "Marcela Correa (escultura)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Bicentenario 4050, Parque Bicentenario",
        "ciudad": "Vitacura",
        "pais": "Chile",
        "coordenadas": {"lat": -33.3986, "lng": -70.5986},
        "ano_diseno": "2005",
        "anos_construccion": "2006-2007",
        "ano_inauguracion": "2007",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Comercial"],
        "descripcion": "Pabellón en el Parque Bicentenario cuya losa de hormigón armado descansa sobre 29 rocas de granito sin labrar de hasta 15 toneladas traídas de canteras cordilleranas, estableciendo un poético diálogo entre naturaleza pétrea y técnica.",
        "fuente_url": "https://www.plataformaarquitectura.cl/cl/02-4467/restaurante-mestizo-smiljan-radic",
        "materiales_principales": ["Rocas de granito bruto", "Losa de hormigón armado negro", "Vidrio curvo", "Madera"]
    },
    {
        "id": "teatro-regional-del-biobio",
        "nombre_proyecto": "Teatro Regional del Biobío",
        "arquitecto": "Smiljan Radic, Eduardo Castillo y Gabriela Medrano",
        "arquitecto_principal": "Smiljan Radic",
        "colaboradores": "Eduardo Castillo, Gabriela Medrano",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Cardenal Raúl Silva Henríquez s/n, Ribera del Río Biobío",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8306, "lng": -73.0658},
        "ano_diseno": "2011",
        "anos_construccion": "2014-2018",
        "ano_inauguracion": "2018",
        "estilos": ["Minimalismo", "Deconstructivismo"],
        "programa": ["Cultural"],
        "descripcion": "Caja monumental traslúcida envuelta en membrana de teflón (PTFE) frente a la inmensidad del río Biobío. De día actúa como un hermético contenedor industrial y de noche se transforma en una linterna urbana resplandeciente.",
        "fuente_url": "https://www.teatrobiobio.cl",
        "materiales_principales": ["Membrana de PTFE tensada", "Estructura de acero reticulada", "Hormigón armado", "Vidrio"]
    },
    {
        "id": "nave-centro-creacion-residencia",
        "nombre_proyecto": "NAVE Centro de Creación y Residencia",
        "arquitecto": "Smiljan Radic",
        "arquitecto_principal": "Smiljan Radic",
        "colaboradores": "Marcela Correa",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Libertad 410, Barrio Yungay",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4386, "lng": -70.6728},
        "ano_diseno": "2012",
        "anos_construccion": "2013-2015",
        "ano_inauguracion": "2015",
        "estilos": ["Posmodernismo", "Deconstructivismo"],
        "programa": ["Cultural"],
        "descripcion": "Reconstrucción radical tras un incendio de una casona patrimonial en Barrio Yungay para un centro de danza y performance. Mantuvo la fachada histórica vaciando su interior para insertar una caja negra teatral coronada por una terraza ajardinada y una carpa amarilla.",
        "fuente_url": "https://www.nave.io",
        "materiales_principales": ["Hormigón armado negro", "Fachada histórica de albañilería", "Madera", "Carpa tensada"]
    },
    {
        "id": "bodega-vik-millahue",
        "nombre_proyecto": "Bodega VIK",
        "arquitecto": "Smiljan Radic",
        "arquitecto_principal": "Smiljan Radic",
        "colaboradores": "Loreto Lyon",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Viña VIK, Valle de Millahue",
        "ciudad": "Millahue, Región de O'Higgins",
        "pais": "Chile",
        "coordenadas": {"lat": -34.3333, "lng": -71.1833},
        "ano_diseno": "2007",
        "anos_construccion": "2008-2014",
        "ano_inauguracion": "2014",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Comercial", "Infraestructura"],
        "descripcion": "Extraordinaria bodega vitivinícola semienterrada en el Valle de Cachapoal. Una gran plaza de agua corriente inclinada sirve como cubierta enfriadora natural para las barricas subterráneas, atravesada por una pasarela de hormigón.",
        "fuente_url": "https://www.vikwine.com",
        "materiales_principales": ["Espejo de agua sobre losa de hormigón", "Membrana traslúcida de tela tensada", "Piedras de río"]
    },
    {
        "id": "casa-poli-coliumo",
        "nombre_proyecto": "Casa Poli (Centro Cultural y Residencia)",
        "arquitecto": "Pezo von Ellrichshausen",
        "arquitecto_principal": "Pezo von Ellrichshausen",
        "colaboradores": "Mauricio Pezo, Sofía von Ellrichshausen",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Península de Coliumo, Comuna de Tomé",
        "ciudad": "Coliumo, Región del Biobío",
        "pais": "Chile",
        "coordenadas": {"lat": -36.5367, "lng": -72.9619},
        "ano_diseno": "2003",
        "anos_construccion": "2004-2005",
        "ano_inauguracion": "2005",
        "estilos": ["Minimalismo", "Brutalismo"],
        "programa": ["Cultural", "Vivienda"],
        "descripcion": "Cubo monolítico de hormigón rústico al borde del acantilado del Océano Pacífico. Opera como residencia de artistas y centro cultural con vanos cuadrados que recortan vistas cinematográficas del mar austral.",
        "fuente_url": "https://pezo.cl/work/poli-house/",
        "materiales_principales": ["Hormigón armado artesanal vertido in situ", "Madera", "Vidrio"]
    },
    {
        "id": "torre-cien-concepcion",
        "nombre_proyecto": "Torre Cien",
        "arquitecto": "Pezo von Ellrichshausen",
        "arquitecto_principal": "Pezo von Ellrichshausen",
        "colaboradores": "Mauricio Pezo, Sofía von Ellrichshausen",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Pedro de Valdivia",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8389, "lng": -73.0556},
        "ano_diseno": "2013",
        "anos_construccion": "2014-2015",
        "ano_inauguracion": "2015",
        "estilos": ["Minimalismo"],
        "programa": ["Vivienda", "Comercial"],
        "descripcion": "Torre prismática de siete pisos en hormigón armado tintado que alberga la casa y estudio de Pezo von Ellrichshausen. Basada en una secuencia concéntrica de habitaciones cuadradas apiladas en vertical.",
        "fuente_url": "https://pezo.cl",
        "materiales_principales": ["Hormigón armado visto", "Madera nativa", "Vidrio"]
    },
    {
        "id": "casa-ribo-concepcion",
        "nombre_proyecto": "Casa Ribo",
        "arquitecto": "Pezo von Ellrichshausen",
        "arquitecto_principal": "Pezo von Ellrichshausen",
        "colaboradores": "Mauricio Pezo, Sofía von Ellrichshausen",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Chiguayante / Río Biobío",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8500, "lng": -73.0333},
        "ano_diseno": "2002",
        "anos_construccion": "2002-2003",
        "ano_inauguracion": "2003",
        "estilos": ["Minimalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Una de las primeras residencias construidas por Pezo von Ellrichshausen. Bloque rectangular puro de hormigón visto y madera que se abre mediante una galería introvertida hacia el paisaje natural.",
        "fuente_url": "https://pezo.cl",
        "materiales_principales": ["Hormigón visto", "Madera de pino", "Vidrio"]
    },
    {
        "id": "termas-geometricas-conaripe",
        "nombre_proyecto": "Termas Geométricas",
        "arquitecto": "Germán del Sol",
        "arquitecto_principal": "Germán del Sol",
        "colaboradores": "Artesanos locales carpinteros",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Parque Nacional Villarrica, Coñaripe",
        "ciudad": "Coñaripe, Región de Los Ríos",
        "pais": "Chile",
        "coordenadas": {"lat": -39.4975, "lng": -71.8683},
        "ano_diseno": "2002",
        "anos_construccion": "2003-2004",
        "ano_inauguracion": "2004",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Hospedaje", "Cultural"],
        "descripcion": "Pasarela peatonal continua de 450 metros en madera de coigüe teñida de rojo bermellón que desciende por una quebrada natural de bosque templado lluvioso uniendo 17 pozones termales de pizarra volcánica.",
        "fuente_url": "https://www.termasgeometricas.cl",
        "materiales_principales": ["Madera de coigüe teñida al aceite", "Piedra pizarra volcánica", "Agua termal", "Fuego de leña"]
    },
    {
        "id": "templo-bahai-de-sudamerica",
        "nombre_proyecto": "Templo Bahá'í de Sudamérica",
        "arquitecto": "Hariri Pontarini Architects",
        "arquitecto_principal": "Hariri Pontarini Architects",
        "colaboradores": "Siamak Hariri; Benjamín Lezaeta (arquitecto local), Simpson Gumpertz & Heger",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Diagonal Las Torres 2015, Precordillera",
        "ciudad": "Peñalolén",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4736, "lng": -70.5117},
        "ano_diseno": "2003",
        "anos_construccion": "2010-2016",
        "ano_inauguracion": "2016",
        "estilos": ["Parametrismo", "Organicismo"],
        "programa": ["Religioso"],
        "descripcion": "Templo continental de nueve alas alabastrinas translúcidas que parecen elevarse como pétalos en movimiento. Su innovadora piel compuesta de vidrio fundido y mármol translúcido de Portugal capta la luz natural creando un interior espiritual resplandeciente.",
        "fuente_url": "https://templo.bahai.cl",
        "materiales_principales": ["Vidrio fundido borosilicatado", "Mármol translúcido portugués", "Estructura espacial de acero", "Bronce"]
    },
    {
        "id": "parque-bicentenario-de-la-infancia",
        "nombre_proyecto": "Parque Bicentenario de la Infancia",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Víctor Oddó, Gonzalo Arteaga, Juan Ignacio Cerda",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Perú 1001, Ladera poniente Cerro San Cristóbal",
        "ciudad": "Recoleta, Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4186, "lng": -70.6433},
        "ano_diseno": "2010",
        "anos_construccion": "2011-2012",
        "ano_inauguracion": "2012",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Cultural", "Deportivo"],
        "descripcion": "Parque infantil escalonado en la empinada ladera del cerro de 4 hectáreas con un sendero de toboganes de hormigón integrados a la pendiente, funicular lúdico y una reja perimetral en 3D que es a la vez juego y mirador urbano.",
        "fuente_url": "https://www.elementalchile.cl/proyectos/parque-bicentenario-de-la-infancia/",
        "materiales_principales": ["Hormigón armado visto", "Acero galvanizado", "Madera", "Vegetación nativa"]
    },
    {
        "id": "centro-cultural-de-constitucion",
        "nombre_proyecto": "Centro Cultural de Constitución",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Víctor Oddó, Gonzalo Arteaga, Juan Ignacio Cerda",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Freire con Portales, Plaza de Armas",
        "ciudad": "Constitución",
        "pais": "Chile",
        "coordenadas": {"lat": -35.3333, "lng": -72.4119},
        "ano_diseno": "2011",
        "anos_construccion": "2012-2014",
        "ano_inauguracion": "2014",
        "estilos": ["Minimalismo", "Racionalismo"],
        "programa": ["Cultural"],
        "descripcion": "Edificio cultural frente a la plaza de armas de Constitución reconstruido tras el 27F, caracterizado por sus volúmenes sobrios de madera y hormigón con pórticos de doble altura abiertos a la comunidad.",
        "fuente_url": "https://www.elementalchile.cl",
        "materiales_principales": ["Madera laminada", "Hormigón armado", "Vidrio"]
    },
    {
        "id": "plan-pres-constitucion-elemental",
        "nombre_proyecto": "Plan de Reconstrucción Sustentable PRES Constitución",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Consorcio Arauco, Municipalidad de Constitución, Ministerio de Vivienda",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Borde fluvial y urbano de Constitución",
        "ciudad": "Constitución",
        "pais": "Chile",
        "coordenadas": {"lat": -35.3314, "lng": -72.4139},
        "ano_diseno": "2010",
        "anos_construccion": "2010-2015",
        "ano_inauguracion": "2010",
        "estilos": ["Funcionalismo", "Organicismo"],
        "programa": ["Infraestructura", "Cultural"],
        "descripcion": "Plan maestro urbano participativo desarrollado tras el tsunami de 2010. En lugar de muros de contención mecánicos que cortaran la vista, propuso un parque fluvial forestado de amortiguación contra olas sísmicas y espacio público cívico.",
        "fuente_url": "https://www.elementalchile.cl",
        "materiales_principales": ["Paisajismo de bosque de amortiguación", "Hormigón", "Madera", "Ciclovías"]
    },
    {
        "id": "centro-cultural-castro-edward-rojas",
        "nombre_proyecto": "Centro Cultural Castro",
        "arquitecto": "Edward Rojas",
        "arquitecto_principal": "Edward Rojas",
        "colaboradores": "Taller Puertazul",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Serrano 320",
        "ciudad": "Castro, Chiloé",
        "pais": "Chile",
        "coordenadas": {"lat": -42.4789, "lng": -73.7667},
        "ano_diseno": "2012",
        "anos_construccion": "2013-2015",
        "ano_inauguracion": "2015",
        "estilos": ["Organicismo", "Posmodernismo"],
        "programa": ["Cultural"],
        "descripcion": "Diseñado por el Premio Nacional de Arquitectura Edward Rojas, reinterpretando la tipología del galpón maderero chilote con tejuelas de alerce, auditorio acústico y espacios expositivos.",
        "fuente_url": "https://www.edwardrojas.cl",
        "materiales_principales": ["Madera nativa chilota", "Tejuelas de alerce", "Vidrio"]
    },
    {
        "id": "museo-del-desierto-de-atacama",
        "nombre_proyecto": "Museo del Desierto de Atacama / Ruinas de Huanchaca",
        "arquitecto": "Coz, Polidura y Volante Arquitectos",
        "arquitecto_principal": "Ramón Coz, Marco Polidura, Eugenia Volante",
        "colaboradores": "Fundación Ruinas de Huanchaca",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Angamos 01606",
        "ciudad": "Antofagasta",
        "pais": "Chile",
        "coordenadas": {"lat": -23.6900, "lng": -70.4167},
        "ano_diseno": "2007",
        "anos_construccion": "2008-2009",
        "ano_inauguracion": "2009",
        "estilos": ["Minimalismo", "Brutalismo"],
        "programa": ["Cultural"],
        "descripcion": "Magno edificio semienterrado en la planicie frente a las monumentales ruinas de piedra de la fundición de plata de Huanchaca, con una secuencia de rampas y taludes de hormigón teñido con tierra del desierto.",
        "fuente_url": "https://www.cozpolidurayarquitectos.cl",
        "materiales_principales": ["Hormigón armado teñido con áridos locales", "Piedra", "Vidrio"]
    },
    {
        "id": "teatro-municipal-la-serena",
        "nombre_proyecto": "Teatro Municipal de San Bartolomé de La Serena",
        "arquitecto": "Morales de Giles + Luis Carreño",
        "arquitecto_principal": "Morales de Giles Arquitectos",
        "colaboradores": "Luis Carreño, Sara de Giles, José Morales",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Colina El Pino",
        "ciudad": "La Serena",
        "pais": "Chile",
        "coordenadas": {"lat": -29.9056, "lng": -71.2472},
        "ano_diseno": "2014",
        "anos_construccion": "2015-2017",
        "ano_inauguracion": "2017",
        "estilos": ["Minimalismo", "Racionalismo"],
        "programa": ["Cultural"],
        "descripcion": "Edificio escénico contemporáneo emplazado en la terraza intermedia de La Serena, con celosías cerámicas y hormigones claros que filtran la radiación solar costera.",
        "fuente_url": "https://www.laserena.cl",
        "materiales_principales": ["Hormigón blanco", "Cerámica arquitectónica", "Vidrio"]
    },
    {
        "id": "centro-cultural-de-coyhaique",
        "nombre_proyecto": "Centro Cultural de Coyhaique",
        "arquitecto": "Diego Quintana y asociados",
        "arquitecto_principal": "Diego Quintana",
        "colaboradores": "Gobierno Regional de Aysén",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Eusebio Lillo 398",
        "ciudad": "Coyhaique",
        "pais": "Chile",
        "coordenadas": {"lat": -45.5714, "lng": -72.0686},
        "ano_diseno": "2010",
        "anos_construccion": "2011-2012",
        "ano_inauguracion": "2012",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Cultural"],
        "descripcion": "Pabellón cultural adaptado al rigor climático extremo de la Patagonia occidental, utilizando maderas nativas certificadas de lenga, techumbres a dos aguas empinadas contra la nieve y grandes lucernarios.",
        "fuente_url": "https://www.culturacoyhaique.cl",
        "materiales_principales": ["Madera de lenga", "Acero negro", "Aislamiento térmico de alta densidad", "Vidrio"]
    },
    {
        "id": "edificio-cruz-del-sur-izquierdo-lehmann",
        "nombre_proyecto": "Edificio Cruz del Sur",
        "arquitecto": "Izquierdo Lehmann",
        "arquitecto_principal": "Luis Izquierdo & Antonia Lehmann",
        "colaboradores": "Equipo Izquierdo Lehmann",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Apoquindo 4501 esq. Cruz del Sur",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4158, "lng": -70.5833},
        "ano_diseno": "2006",
        "anos_construccion": "2007-2009",
        "ano_inauguracion": "2009",
        "estilos": ["Minimalismo", "High-Tech"],
        "programa": ["Comercial"],
        "descripcion": "Torre corporativa en el eje Apoquindo con una imponente losa en voladizo sobre la esquina peatonal y una doble piel de vidrio serigrafiado de máxima eficiencia energética.",
        "fuente_url": "https://www.izquierdolehmann.com",
        "materiales_principales": ["Hormigón armado visto", "Vidrio serigrafiado", "Granito"]
    },
    {
        "id": "edificio-gen-santiago",
        "nombre_proyecto": "Edificio Gen",
        "arquitecto": "Felipe Assadi y Francisca Pulido",
        "arquitecto_principal": "Felipe Assadi",
        "colaboradores": "Francisca Pulido",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Portugal 520",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4472, "lng": -70.6367},
        "ano_diseno": "2008",
        "anos_construccion": "2009-2010",
        "ano_inauguracion": "2010",
        "estilos": ["Minimalismo", "High-Tech"],
        "programa": ["Vivienda"],
        "descripcion": "Edificio residencial pionero en sustentabilidad urbana con colectores solares en fachada y celosías cinéticas de protección térmica, ubicado en el pericentro de Santiago.",
        "fuente_url": "https://www.felipeassadi.com",
        "materiales_principales": ["Hormigón armado", "Paneles solares", "Celosías de aluminio"]
    },
    {
        "id": "punta-pite-teresa-moller",
        "nombre_proyecto": "Punta Pite (Intervención de Paisaje)",
        "arquitecto": "Teresa Moller",
        "arquitecto_principal": "Teresa Moller",
        "colaboradores": "Canteros y picapedreros locales",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Entre Zapallar y Papudo, Región de Valparaíso",
        "ciudad": "Zapallar",
        "pais": "Chile",
        "coordenadas": {"lat": -32.5333, "lng": -71.4500},
        "ano_diseno": "2003",
        "anos_construccion": "2004-2005",
        "ano_inauguracion": "2005",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Cultural"],
        "descripcion": "Sendero costero peatonal esculpido directamente en los farellones rocosos de granito junto al rompiente del Pacífico. Una intervención de sutileza extraordinaria donde las escalinatas parecen brotar de la propia geología.",
        "fuente_url": "https://www.teresamoller.com",
        "materiales_principales": ["Piedra granito canteada a mano in situ", "Flora costera nativa"]
    },
    {
        "id": "escuela-de-diseno-puc",
        "nombre_proyecto": "Escuela de Diseño PUC",
        "arquitecto": "Sebastián Irarrázaval",
        "arquitecto_principal": "Sebastián Irarrázaval",
        "colaboradores": "Facultad de Arquitectura, Diseño y Estudios Urbanos PUC",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Campus Lo Contador, El Comendador 1916",
        "ciudad": "Providencia",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4183, "lng": -70.6186},
        "ano_diseno": "2009",
        "anos_construccion": "2009-2010",
        "ano_inauguracion": "2010",
        "estilos": ["Minimalismo", "Brutalismo"],
        "programa": ["Educacional"],
        "descripcion": "Intervención de hormigón armado visto y maderas nobles en el campus histórico de Lo Contador, con talleres diáfanos y patios suspendidos que fomentan la interacción creativa entre alumnos y profesores.",
        "fuente_url": "https://www.sebastianirarrazaval.net",
        "materiales_principales": ["Hormigón visto", "Madera", "Acero"]
    },
    {
        "id": "biblioteca-publica-de-licanten",
        "nombre_proyecto": "Biblioteca Pública de Licantén",
        "arquitecto": "Sebastián Irarrázaval",
        "arquitecto_principal": "Sebastián Irarrázaval",
        "colaboradores": "Municipalidad de Licantén",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Lautaro s/n",
        "ciudad": "Licantén, Región del Maule",
        "pais": "Chile",
        "coordenadas": {"lat": -34.9833, "lng": -72.0167},
        "ano_diseno": "2013",
        "anos_construccion": "2013-2014",
        "ano_inauguracion": "2014",
        "estilos": ["Minimalismo", "Funcionalismo"],
        "programa": ["Educacional", "Cultural"],
        "descripcion": "Biblioteca cívica levantada sobre pilotes de hormigón para evitar inundaciones del río Mataquito, resuelta enteramente en madera laminada de pino con linternas de luz cenital.",
        "fuente_url": "https://www.sebastianirarrazaval.net",
        "materiales_principales": ["Madera laminada", "Hormigón en pilotes", "Vidrio"]
    },
    {
        "id": "hotel-tierra-patagonia-cazu-zegers",
        "nombre_proyecto": "Hotel Tierra Patagonia",
        "arquitecto": "Cazú Zegers",
        "arquitecto_principal": "Cazú Zegers",
        "colaboradores": "Roberto Benavente, Paulina Courard",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Borde del Lago Sarmiento, Torres del Paine",
        "ciudad": "Torres del Paine",
        "pais": "Chile",
        "coordenadas": {"lat": -51.0500, "lng": -72.7833},
        "ano_diseno": "2009",
        "anos_construccion": "2010-2011",
        "ano_inauguracion": "2011",
        "estilos": ["Organicismo"],
        "programa": ["Hospedaje"],
        "descripcion": "Edificio silueta concebido como una forma fósil o una ráfaga de viento patagónico posada en la orilla del lago Sarmiento, revestida íntegramente en madera de lenga lavada.",
        "fuente_url": "https://www.cazuzegers.cl",
        "materiales_principales": ["Madera de lenga patagónica", "Vidrio panorámico", "Hormigón"]
    },
    {
        "id": "hotel-escondido-cazu-zegers",
        "nombre_proyecto": "Pabellón de las Cotorras / Hotel Escondido",
        "arquitecto": "Cazú Zegers",
        "arquitecto_principal": "Cazú Zegers",
        "colaboradores": "Cazú Zegers Arquitectura",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Quebrada de Puritama",
        "ciudad": "Puritama, Atacama",
        "pais": "Chile",
        "coordenadas": {"lat": -22.7167, "lng": -68.0333},
        "ano_diseno": "2013",
        "anos_construccion": "2013-2014",
        "ano_inauguracion": "2014",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Hospedaje"],
        "descripcion": "Intervención de bajo impacto en el cañón termal de Puritama con materiales vernáculos de barro, caña brava y madera ensamblada para mimetizarse con la geografía desértica.",
        "fuente_url": "https://www.cazuzegers.cl",
        "materiales_principales": ["Piedra volcánica", "Caña", "Madera", "Tierra cruda"]
    },
    {
        "id": "planta-almazara-olisur",
        "nombre_proyecto": "Planta Almazara Olisur",
        "arquitecto": "Guillermo Hevia",
        "arquitecto_principal": "Guillermo Hevia",
        "colaboradores": "GH+A Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Fundo San José, Marchigüe",
        "ciudad": "Marchigüe, Región de O'Higgins",
        "pais": "Chile",
        "coordenadas": {"lat": -34.4000, "lng": -71.6167},
        "ano_diseno": "2007",
        "anos_construccion": "2007-2008",
        "ano_inauguracion": "2008",
        "estilos": ["Minimalismo", "High-Tech"],
        "programa": ["Infraestructura", "Comercial"],
        "descripcion": "Planta aceitera de vanguardia bioclimática que utiliza geotermia y ventilación pasiva por chimeneas solares, construida con maderas laminadas y cristales de alta performance.",
        "fuente_url": "https://www.guillermohevia.cl",
        "materiales_principales": ["Madera laminada", "Acero", "Vidrio con control térmico"]
    },
    {
        "id": "planta-cristalchile-llay-llay",
        "nombre_proyecto": "Planta CristalChile",
        "arquitecto": "Guillermo Hevia",
        "arquitecto_principal": "Guillermo Hevia",
        "colaboradores": "GH+A Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Panamericana Norte Km 87, Llay-Llay",
        "ciudad": "Llay-Llay, Región de Valparaíso",
        "pais": "Chile",
        "coordenadas": {"lat": -32.8417, "lng": -70.9667},
        "ano_diseno": "2005",
        "anos_construccion": "2005-2006",
        "ano_inauguracion": "2006",
        "estilos": ["High-Tech", "Funcionalismo"],
        "programa": ["Infraestructura"],
        "descripcion": "Fábrica de envases de vidrio de gran escala concebida bajo criterios de arquitectura bioclimática pasiva e iluminación natural cenital con ondulaciones que replican los cerros del Valle del Aconcagua.",
        "fuente_url": "https://www.guillermohevia.cl",
        "materiales_principales": ["Acero estructural", "Paneles aislantes curvados", "Vidrio"]
    },
    {
        "id": "centro-arte-molino-machmar",
        "nombre_proyecto": "Centro de Arte Molino Machmar",
        "arquitecto": "Pablo Ortúzar y equipo",
        "arquitecto_principal": "Pablo Ortúzar",
        "colaboradores": "Equipo de restauración patrimonial de Puerto Varas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Gramado 1100",
        "ciudad": "Puerto Varas",
        "pais": "Chile",
        "coordenadas": {"lat": -41.3194, "lng": -72.9861},
        "ano_diseno": "2013",
        "anos_construccion": "2014-2016",
        "ano_inauguracion": "2016",
        "estilos": ["Historicismo", "Minimalismo"],
        "programa": ["Cultural"],
        "descripcion": "Recuperación y reconversión de un molino harinero histórico de madera de alerce del siglo XX en un vibrante centro cultural, sala de cine de arte y museo de la colonización alemana.",
        "fuente_url": "https://www.molinomachmar.cl",
        "materiales_principales": ["Estructura de madera nativa original", "Tejuelas de alerce", "Hormigón", "Acero"]
    },
    {
        "id": "museo-arte-contemporaneo-chiloe-mam",
        "nombre_proyecto": "Museo de Arte Contemporáneo Chiloé (MAM)",
        "arquitecto": "Eduardo Feuerhake y Edward Rojas",
        "arquitecto_principal": "Eduardo Feuerhake",
        "colaboradores": "Edward Rojas, Taller Puertazul",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Parque Municipal de Castro s/n",
        "ciudad": "Castro, Chiloé",
        "pais": "Chile",
        "coordenadas": {"lat": -42.4833, "lng": -73.7833},
        "ano_diseno": "1988",
        "anos_construccion": "1988-2000",
        "ano_inauguracion": "2000",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Cultural"],
        "descripcion": "Pabellón de madera construido al interior de un parque natural en Castro. Galardonado internacionalmente por reciclar las casas de madera tradicionales de la isla y transformarlas en salas de arte de nivel mundial.",
        "fuente_url": "https://www.mamchiloe.cl",
        "materiales_principales": ["Madera reciclada de demolición", "Tejuelas de alerce", "Vidrio"]
    },
    {
        "id": "museo-de-la-memoria-y-los-derechos-humanos",
        "nombre_proyecto": "Museo de la Memoria y los Derechos Humanos",
        "arquitecto": "Estudio Mario Figueroa, Lucas Fehr y Carlos Dias",
        "arquitecto_principal": "Mario Figueroa",
        "colaboradores": "Lucas Fehr, Carlos Dias (Estudio América, Brasil); Roberto Santomauro",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Matucana 501, Quinta Normal",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4397, "lng": -70.6797},
        "ano_diseno": "2007",
        "anos_construccion": "2008-2010",
        "ano_inauguracion": "2010",
        "estilos": ["Minimalismo", "High-Tech"],
        "programa": ["Cultural"],
        "descripcion": "Magno paralelepípedo de cobre y vidrio suspendido como una viga puente sobre una gran plaza cívica hundida de granito, concebido para conmemorar a las víctimas de la dictadura civil-militar.",
        "fuente_url": "https://www.museodelamemoria.cl",
        "materiales_principales": ["Cobre patinado verde", "Vidrio serigrafiado", "Hormigón armado visto", "Acero"]
    },
    {
        "id": "plaza-ciudadania-centro-cultural-la-moneda",
        "nombre_proyecto": "Plaza de la Ciudadanía y Centro Cultural La Moneda",
        "arquitecto": "Cristián Undurraga",
        "arquitecto_principal": "Cristián Undurraga",
        "colaboradores": "Undurraga Devés Arquitectos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza de la Ciudadanía 26",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4439, "lng": -70.6539},
        "ano_diseno": "2004",
        "anos_construccion": "2004-2006",
        "ano_inauguracion": "2006",
        "estilos": ["Minimalismo"],
        "programa": ["Cultural", "Institucional / Gubernamental"],
        "descripcion": "Intervención cívica que abrió el zócalo sur de La Moneda al público, excavando un centro cultural de tres niveles subterráneos iluminado por una cubierta de agua y lucernarios enrasados.",
        "fuente_url": "https://www.cclm.cl",
        "materiales_principales": ["Hormigón blanco", "Madera", "Espejo de agua", "Vidrio templado"]
    },
    {
        "id": "colegio-ayelen-rancagua",
        "nombre_proyecto": "Colegio Ayelén",
        "arquitecto": "ELEMENTAL / Alejandro Aravena",
        "arquitecto_principal": "Alejandro Aravena (ELEMENTAL)",
        "colaboradores": "Gonzalo Arteaga, Juan Ignacio Cerda",
        "ano_pritzker": 2016,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Rancagua, Región de O'Higgins",
        "ciudad": "Rancagua",
        "pais": "Chile",
        "coordenadas": {"lat": -34.1667, "lng": -70.7500},
        "ano_diseno": "2014",
        "anos_construccion": "2014-2015",
        "ano_inauguracion": "2015",
        "estilos": ["Racionalismo", "Minimalismo"],
        "programa": ["Educacional"],
        "descripcion": "Colegio polivalente que optimiza el presupuesto público con galerías perimetrales de hormigón que sirven simultáneamente como circulaciones protegidas y aleros de sombra.",
        "fuente_url": "https://www.elementalchile.cl",
        "materiales_principales": ["Hormigón armado visto", "Acero", "Albañilería"]
    },
    {
        "id": "edificio-transoceanica-vitacura",
        "nombre_proyecto": "Edificio Transoceánica",
        "arquitecto": "+Arquitectos / Alex Brahm",
        "arquitecto_principal": "+Arquitectos",
        "colaboradores": "Alex Brahm, David Bonomi, Marcelo Leturia, Maite Escribano",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Santa María 5888",
        "ciudad": "Vitacura",
        "pais": "Chile",
        "coordenadas": {"lat": -33.3778, "lng": -70.5667},
        "ano_diseno": "2008",
        "anos_construccion": "2009-2010",
        "ano_inauguracion": "2010",
        "estilos": ["Organicismo", "High-Tech"],
        "programa": ["Comercial"],
        "descripcion": "Edificio corporativo con certificación LEED Gold, curvo en forma de hoja o gota de agua rodeado por un parque paisajístico con geotermia de napas subterráneas y celosías de madera.",
        "fuente_url": "https://www.masarquitectos.cl",
        "materiales_principales": ["Vidrio termoacústico", "Madera", "Hormigón", "Agua subterránea geotérmica"]
    },
    {
        "id": "edificio-bice-las-condes",
        "nombre_proyecto": "Edificio BICE",
        "arquitecto": "Teodoro Fernández",
        "arquitecto_principal": "Teodoro Fernández",
        "colaboradores": "Sebastián Hernández",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Apoquindo con Gertrudis Echeñique",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4161, "lng": -70.5961},
        "ano_diseno": "2005",
        "anos_construccion": "2006-2007",
        "ano_inauguracion": "2007",
        "estilos": ["Minimalismo", "Racionalismo"],
        "programa": ["Comercial"],
        "descripcion": "Edificio bancario y de oficinas que destaca por su fachada de piedra natural chilena y su respeto a la escala peatonal del barrio El Golf.",
        "fuente_url": "https://www.teodorofernandez.cl",
        "materiales_principales": ["Piedra canteada", "Hormigón armado", "Vidrio"]
    },
    {
        "id": "parque-koinco-punta-arenas",
        "nombre_proyecto": "Parque Koinco / Parque Metropolitano Los Cerros",
        "arquitecto": "Teodoro Fernández",
        "arquitecto_principal": "Teodoro Fernández",
        "colaboradores": "Equipo Teodoro Fernández Paisajismo",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Alto de Punta Arenas",
        "ciudad": "Punta Arenas",
        "pais": "Chile",
        "coordenadas": {"lat": -53.1500, "lng": -70.9333},
        "ano_diseno": "2012",
        "anos_construccion": "2013-2014",
        "ano_inauguracion": "2014",
        "estilos": ["Organicismo"],
        "programa": ["Cultural", "Deportivo"],
        "descripcion": "Parque urbano y paisajístico en los cerros de Magallanes que canaliza las escorrentías naturales y protege de los vientos australes mediante vegetación esteparia nativa y terrazas mirador.",
        "fuente_url": "https://www.teodorofernandez.cl",
        "materiales_principales": ["Madera nativa", "Piedra", "Especies vegetales magallánicas"]
    },
    {
        "id": "parque-bicentenario-vitacura",
        "nombre_proyecto": "Parque Bicentenario de Vitacura",
        "arquitecto": "Teodoro Fernández",
        "arquitecto_principal": "Teodoro Fernández",
        "colaboradores": "Danilo Martic, Paulina Courard",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Bicentenario 3800",
        "ciudad": "Vitacura",
        "pais": "Chile",
        "coordenadas": {"lat": -33.3972, "lng": -70.5989},
        "ano_diseno": "2000",
        "anos_construccion": "2006-2007",
        "ano_inauguracion": "2007",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Cultural", "Deportivo"],
        "descripcion": "Uno de los parques urbanos contemporáneos más celebrados de América Latina. 30 hectáreas junto al Río Mapocho con lagunas de flamencos, senderos de paseo y paisajismo autóctono de bajo consumo hídrico.",
        "fuente_url": "https://www.teodorofernandez.cl",
        "materiales_principales": ["Piedra de río", "Lagunas artificiales", "Árboles nativos", "Césped"]
    },
    {
        "id": "san-carlos-de-apoquindo-deportes",
        "nombre_proyecto": "Complejo Deportivo San Carlos de Apoquindo (Rugby/Atletismo)",
        "arquitecto": "Izquierdo Lehmann",
        "arquitecto_principal": "Luis Izquierdo & Antonia Lehmann",
        "colaboradores": "Club Deportivo Universidad Católica",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Camino Las Flores 13000",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.3958, "lng": -70.5056},
        "ano_diseno": "2019",
        "anos_construccion": "2020-2021",
        "ano_inauguracion": "2021",
        "estilos": ["Minimalismo", "Brutalismo"],
        "programa": ["Deportivo"],
        "descripcion": "Complejo de rugby y atletismo tallado en la precordillera andina con pabellones de vestuarios y graderías de hormigón armado a la vista de sobria elegancia tectónica.",
        "fuente_url": "https://www.izquierdolehmann.com",
        "materiales_principales": ["Hormigón armado visto", "Madera", "Acero galvanizado"]
    },
    {
        "id": "cabana-laguna-aculeo-assadi",
        "nombre_proyecto": "Cabaña/Refugio en Laguna Aculeo",
        "arquitecto": "Felipe Assadi",
        "arquitecto_principal": "Felipe Assadi",
        "colaboradores": "Francisca Pulido",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Pintué, Laguna de Aculeo",
        "ciudad": "Pintué",
        "pais": "Chile",
        "coordenadas": {"lat": -33.8500, "lng": -70.9167},
        "ano_diseno": "2008",
        "anos_construccion": "2008-2009",
        "ano_inauguracion": "2009",
        "estilos": ["Minimalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Volumen suspendido horizontal de hormigón y vidrio proyectado hacia la naturaleza con vistas hacia los cerros de Aculeo, encarnando la radical síntesis geométrica de Assadi.",
        "fuente_url": "https://www.felipeassadi.com",
        "materiales_principales": ["Hormigón armado", "Vidrio", "Madera nativa"]
    },
    {
        "id": "casa-wall-paredes-de-granito",
        "nombre_proyecto": "Paredes de Granito / Casa Wall",
        "arquitecto": "FAR Marc Frohn & Mario Rojas",
        "arquitecto_principal": "FAR Marc Frohn & Mario Rojas",
        "colaboradores": "FAR frohn&rojas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector precordillerano",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4000, "lng": -70.5167},
        "ano_diseno": "2006",
        "anos_construccion": "2006-2007",
        "ano_inauguracion": "2007",
        "estilos": ["Deconstructivismo", "Minimalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Vivienda unifamiliar organizada a partir de cuatro capas concéntricas envolventes (desde una cortina textil traslúcida hasta muros de hormigón y vidrio), regulando gradualmente clima y privacidad.",
        "fuente_url": "https://f-a-r.net",
        "materiales_principales": ["Policarbonato", "Hormigón", "Membrana textil", "Vidrio"]
    },
    {
        "id": "centro-visitantes-torres-del-paine",
        "nombre_proyecto": "Centro de Visitantes Parque Nacional Torres del Paine",
        "arquitecto": "Pedro Kovacic",
        "arquitecto_principal": "Pedro Kovacic",
        "colaboradores": "CONAF, Ministerio de Obras Públicas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Río Serrano, Parque Nacional Torres del Paine",
        "ciudad": "Magallanes",
        "pais": "Chile",
        "coordenadas": {"lat": -51.2167, "lng": -72.9833},
        "ano_diseno": "2016",
        "anos_construccion": "2017-2018",
        "ano_inauguracion": "2018",
        "estilos": ["Organicismo", "Minimalismo"],
        "programa": ["Cultural", "Institucional / Gubernamental"],
        "descripcion": "Portal de acceso al Parque Nacional que reinterpreta los galpones de esquila patagónicos, con techumbres aerodinámicas que desvían las ráfagas de viento y amplios ventanales orientados al Macizo Paine.",
        "fuente_url": "https://www.conaf.cl",
        "materiales_principales": ["Madera de lenga", "Acero zincado prepintado", "Vidrio térmico"]
    }
]

print(f"Period 6 defined: {len(period_6)} projects.")
