#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Period 2: Protomodernismo, Eclecticismos e Industrialización (1900 – 1930)"""

period_2 = [
    {
        "id": "museo-nacional-bellas-artes-santiago",
        "nombre_proyecto": "Museo Nacional de Bellas Artes",
        "arquitecto": "Émile Jéquier",
        "arquitecto_principal": "Émile Jéquier",
        "colaboradores": "Talleres y fundiciones francesas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Parque Forestal s/n",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4356, "lng": -70.6433},
        "ano_diseno": "1905",
        "anos_construccion": "1905-1910",
        "ano_inauguracion": "1910",
        "estilos": ["Historicismo", "Art Nouveau", "Arquitectura Neoclásica"],
        "programa": ["Cultural"],
        "descripcion": "Inaugurado para el Centenario de la República. Combina el academicismo Beaux-Arts con una espectacular cúpula de vidrio y hierro forjado alemana inspirada en el Petit Palais de París.",
        "fuente_url": "https://www.mnba.gob.cl/historia-del-edificio",
        "materiales_principales": ["Albañilería armada", "Hormigón temprano", "Hierro forjado", "Vidrio"]
    },
    {
        "id": "estacion-mapocho-santiago",
        "nombre_proyecto": "Estación Mapocho",
        "arquitecto": "Émile Jéquier",
        "arquitecto_principal": "Émile Jéquier",
        "colaboradores": "Fábricas de fundición belgas y francesas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza de la Cultura s/n",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4325, "lng": -70.6528},
        "ano_diseno": "1905",
        "anos_construccion": "1905-1912",
        "ano_inauguracion": "1912",
        "estilos": ["Arquitectura del Hierro y Cristal", "Historicismo"],
        "programa": ["Infraestructura", "Cultural"],
        "descripcion": "Monumental estación terminal ferroviaria con una gran nave central de 200 metros de largo techada por una estructura abovedada de acero sin pilares intermedios, reconvertida en centro cultural en los años 90.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/estacion-mapocho",
        "materiales_principales": ["Acero estructural", "Albañilería", "Vidrio", "Cobre"]
    },
    {
        "id": "palacio-tribunales-justicia-santiago",
        "nombre_proyecto": "Palacio de los Tribunales de Justicia",
        "arquitecto": "Emilio Doyère",
        "arquitecto_principal": "Emilio Doyère",
        "colaboradores": "Cuerpo de ingenieros del Ministerio de Obras Públicas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Compañía de Jesús 1140",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4392, "lng": -70.6528},
        "ano_diseno": "1905",
        "anos_construccion": "1905-1911",
        "ano_inauguracion": "1911",
        "estilos": ["Arquitectura Neoclásica", "Historicismo"],
        "programa": ["Institucional / Gubernamental"],
        "descripcion": "Sede de la Corte Suprema de Justicia de Chile. Edificio monumental de estilo neoclásico francés con pórtico hexástilo corintio y un deslumbrante vestíbulo de triple altura con lucernario y vidrieras.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-tribunales-justicia",
        "materiales_principales": ["Albañilería de ladrillo y cemento", "Hierro", "Mármol"]
    },
    {
        "id": "edificio-comercial-edwards",
        "nombre_proyecto": "Edificio Comercial Edwards",
        "arquitecto": "Eugenio Joannon",
        "arquitecto_principal": "Eugenio Joannon",
        "colaboradores": "Talleres de fundición Saint-Sauveur Arras (Francia)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Merced esq. Estado",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4414, "lng": -70.6508},
        "ano_diseno": "1911",
        "anos_construccion": "1911-1913",
        "ano_inauguracion": "1913",
        "estilos": ["Art Nouveau", "Historicismo"],
        "programa": ["Comercial"],
        "descripcion": "Hito pionero del Art Nouveau comercial en Chile con estructura metálica prefabricada en Francia, grandes ventanales curvos en esquina, marquesinas de cristal y cúpula de hierro.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/edificio-comercial-edwards",
        "materiales_principales": ["Estructura metálica", "Vidrio curvo", "Estuco ornamentado"]
    },
    {
        "id": "palacio-baburizza-valparaiso",
        "nombre_proyecto": "Palacio Baburizza",
        "arquitecto": "Arnaldo Barison y Giuliano Pellegrini",
        "arquitecto_principal": "Arnaldo Barison",
        "colaboradores": "Giuliano Pellegrini; Ottorino Zanelli (mandante original)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Paseo Yugoeslavo, Cerro Alegre",
        "ciudad": "Valparaíso",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0403, "lng": -71.6289},
        "ano_diseno": "1914",
        "anos_construccion": "1914-1916",
        "ano_inauguracion": "1916",
        "estilos": ["Art Nouveau", "Historicismo"],
        "programa": ["Vivienda", "Cultural"],
        "descripcion": "Cúspide residencial del modernismo catalán y Jugendstil en Valparaíso. Emplazado sobre el acantilado del Cerro Alegre con terrazas voladas, entramados de madera a la vista y torre mirador sobre la bahía.",
        "fuente_url": "https://www.museobaburizza.cl",
        "materiales_principales": ["Albañilería de ladrillo", "Maderas nobles", "Hierro forjado art nouveau"]
    },
    {
        "id": "biblioteca-nacional-de-chile",
        "nombre_proyecto": "Biblioteca Nacional de Chile",
        "arquitecto": "Gustavo García Postigo",
        "arquitecto_principal": "Gustavo García Postigo",
        "colaboradores": "Manuel Cifuentes Gómez (diseño inicial)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Libertador Bernardo O'Higgins 651",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4422, "lng": -70.6456},
        "ano_diseno": "1913",
        "anos_construccion": "1913-1925",
        "ano_inauguracion": "1925",
        "estilos": ["Arquitectura Neoclásica", "Historicismo"],
        "programa": ["Cultural", "Educacional"],
        "descripcion": "Magna obra del neoclasicismo monumetal de inspiración académica francesa, con una planta cruciforme, Sala Gabriela Mistral, estucos dorados, cúpula vidriada y depósitos mecánicos de libros pioneros.",
        "fuente_url": "https://www.bibliotecanacional.gob.cl",
        "materiales_principales": ["Hormigón armado", "Albañilería", "Mármol", "Bronce"]
    },
    {
        "id": "palacio-astoreca-iquique",
        "nombre_proyecto": "Palacio Astoreca",
        "arquitecto": "Alberto Cruz Montt",
        "arquitecto_principal": "Alberto Cruz Montt",
        "colaboradores": "Ebanistas y artesanos europeos en la pampa salitrera",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Calle Bernardo O'Higgins 350",
        "ciudad": "Iquique",
        "pais": "Chile",
        "coordenadas": {"lat": -20.2189, "lng": -70.1517},
        "ano_diseno": "1903",
        "anos_construccion": "1903-1904",
        "ano_inauguracion": "1904",
        "estilos": ["Historicismo", "Art Nouveau"],
        "programa": ["Vivienda", "Cultural"],
        "descripcion": "Máxima joya arquitectónica del ciclo del salitre construida íntegramente en madera de pino oregón con un deslumbrante patio central cubierto por un vitral Art Nouveau estilo Tiffany.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-astoreca",
        "materiales_principales": ["Madera de pino oregón importado", "Vitrales art nouveau", "Bronce"]
    },
    {
        "id": "palacio-valle-vina-del-mar",
        "nombre_proyecto": "Palacio Valle",
        "arquitecto": "Arnaldo Barison y Giuliano Pellegrini",
        "arquitecto_principal": "Arnaldo Barison",
        "colaboradores": "Giuliano Pellegrini; Giovanni Valle (mandante)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Paseo Valle 396",
        "ciudad": "Viña del Mar",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0239, "lng": -71.5583},
        "ano_diseno": "1914",
        "anos_construccion": "1914-1916",
        "ano_inauguracion": "1916",
        "estilos": ["Historicismo", "Arquitectura Neoclásica"],
        "programa": ["Vivienda", "Educacional"],
        "descripcion": "Casona neorrenacentista veneciana y ecléctica en la colina de Viña del Mar, caracterizada por sus loggias con arcos trilobulados, terracotas y balaustradas. Actual Instituto de Historia PUCV.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Albañilería de ladrillo", "Mármol", "Yeso modelado"]
    },
    {
        "id": "palacio-vergara-vina-del-mar",
        "nombre_proyecto": "Palacio Vergara",
        "arquitecto": "Ettore Petri Santini",
        "arquitecto_principal": "Ettore Petri Santini",
        "colaboradores": "Artesanos y constructores venecianos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Parque Quinta Vergara s/n",
        "ciudad": "Viña del Mar",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0278, "lng": -71.5500},
        "ano_diseno": "1908",
        "anos_construccion": "1908-1910",
        "ano_inauguracion": "1910",
        "estilos": ["Historicismo"],
        "programa": ["Vivienda", "Cultural"],
        "descripcion": "Residencia de la familia fundadora de Viña del Mar, de exquisito estilo neogótico veneciano con tracerías caladas en piedra y balaustres de mármol blanco, inserta en el histórico parque botánico de la Quinta Vergara.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-parque-quinta-vergara",
        "materiales_principales": ["Albañilería reforzada", "Mármol", "Maderas nobles", "Enyesados"]
    },
    {
        "id": "club-de-la-union-santiago",
        "nombre_proyecto": "Club de la Unión",
        "arquitecto": "Alberto Cruz Montt",
        "arquitecto_principal": "Alberto Cruz Montt",
        "colaboradores": "Escultores y decoradores franceses e italianos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Libertador Bernardo O'Higgins 1091",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4439, "lng": -70.6514},
        "ano_diseno": "1917",
        "anos_construccion": "1917-1925",
        "ano_inauguracion": "1925",
        "estilos": ["Arquitectura Neoclásica", "Historicismo"],
        "programa": ["Cultural", "Comercial"],
        "descripcion": "Obra maestra del historicismo clásico francés en Chile. Cuenta con una monumental escalera de honor en mármol, salones de madera de roble, bar inglés y una rica pinacoteca nacional.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/club-union",
        "materiales_principales": ["Hormigón armado", "Mármol", "Bronce", "Maderas nobles"]
    },
    {
        "id": "edificio-ariztia-santiago",
        "nombre_proyecto": "Edificio Ariztía",
        "arquitecto": "Alberto Cruz Montt y Ricardo Larraín Bravo",
        "arquitecto_principal": "Alberto Cruz Montt",
        "colaboradores": "Ricardo Larraín Bravo",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Nueva York 52, Barrio Bolsa de Comercio",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4425, "lng": -70.6533},
        "ano_diseno": "1920",
        "anos_construccion": "1920-1921",
        "ano_inauguracion": "1921",
        "estilos": ["Historicismo", "Arquitectura Neoclásica"],
        "programa": ["Comercial", "Institucional / Gubernamental"],
        "descripcion": "Considerado el primer 'rascacielos' de Santiago y de Chile. Con 8 pisos de altura y un mirador en proa que articula el encuentro en vértice del Barrio París-Londres y la Bolsa de Comercio.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado pionero", "Albañilería", "Yeso"]
    },
    {
        "id": "edificio-oberpaur-santiago",
        "nombre_proyecto": "Edificio Oberpaur",
        "arquitecto": "Sergio Larraín García-Moreno y Jorge Arteaga",
        "arquitecto_principal": "Sergio Larraín García-Moreno",
        "colaboradores": "Jorge Arteaga",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Estado 244 esq. Huérfanos",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4400, "lng": -70.6508},
        "ano_diseno": "1929",
        "anos_construccion": "1929",
        "ano_inauguracion": "1929",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Comercial"],
        "descripcion": "El primer edificio del Movimiento Moderno en Chile, proyectado por un joven Sergio Larraín tras su viaje formativo a Europa donde conoció a Le Corbusier. Fachada curva con ventanas horizontales continuas tipo ribbon windows.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Vidrio continuo", "Perfiles de acero"]
    },
    {
        "id": "cite-las-palmas-santiago",
        "nombre_proyecto": "Cité Las Palmas",
        "arquitecto": "Julio Bertrand Vidal",
        "arquitecto_principal": "Julio Bertrand Vidal",
        "colaboradores": "Constructores del Barrio Brasil",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Compañía de Jesús 2315, Barrio Brasil",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4406, "lng": -70.6653},
        "ano_diseno": "1913",
        "anos_construccion": "1913-1914",
        "ano_inauguracion": "1914",
        "estilos": ["Historicismo", "Art Nouveau"],
        "programa": ["Vivienda"],
        "descripcion": "Cúspide de la tipología habitacional del cité en Santiago, proyectado por el notable arquitecto e intelectual Julio Bertrand Vidal con fachada ecléctica y una calle interior ajardinada con palmeras canarias.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Albañilería de ladrillo", "Estucos ornamentales", "Hierro forjado", "Madera"]
    },
    {
        "id": "poblacion-huemul-i-santiago",
        "nombre_proyecto": "Población Huemul I",
        "arquitecto": "Ricardo Larraín Bravo",
        "arquitecto_principal": "Ricardo Larraín Bravo",
        "colaboradores": "Caja de Crédito Hipotecario",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Barrio Huemul, Santiago Sur",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4689, "lng": -70.6483},
        "ano_diseno": "1910",
        "anos_construccion": "1911",
        "ano_inauguracion": "1911",
        "estilos": ["Historicismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "El primer barrio cívico y modelo de vivienda obrera higiénica planificada en Chile, con 166 casas unifamiliares, plaza central, teatro, biblioteca, iglesia y dispensario médico de excelente calidad constructiva.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/zonas-tipicas/barrio-huemul",
        "materiales_principales": ["Albañilería reforzada", "Madera", "Tejas cerámicas"]
    },
    {
        "id": "edificio-banco-de-chile-casa-central",
        "nombre_proyecto": "Edificio Banco de Chile (Casa Central)",
        "arquitecto": "Alberto Cruz Montt",
        "arquitecto_principal": "Alberto Cruz Montt",
        "colaboradores": "Ingenieros calculistas del Banco de Chile",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Ahumada 251",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4406, "lng": -70.6528},
        "ano_diseno": "1921",
        "anos_construccion": "1921-1926",
        "ano_inauguracion": "1926",
        "estilos": ["Arquitectura Neoclásica", "Historicismo"],
        "programa": ["Comercial", "Institucional / Gubernamental"],
        "descripcion": "Imponente palacio financiero de impronta neoclásica monumental en el corazón peatonal de Santiago. Sobresale su gran hall público circular con columnas pareadas de mármol y cúpula de vitral.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/edificio-casa-matriz-banco-chile",
        "materiales_principales": ["Hormigón armado", "Mármol importado", "Bronce", "Vitral"]
    },
    {
        "id": "pabellon-paris-museo-artequin",
        "nombre_proyecto": "Pabellón París / Museo Artequín",
        "arquitecto": "Henri Picq",
        "arquitecto_principal": "Henri Picq",
        "colaboradores": "Estructuras metálicas de la Exposición Universal de París 1889",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Portales 3530, Quinta Normal",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4456, "lng": -70.6836},
        "ano_diseno": "1888",
        "anos_construccion": "1889-1894",
        "ano_inauguracion": "1894",
        "estilos": ["Arquitectura del Hierro y Cristal", "Historicismo"],
        "programa": ["Cultural"],
        "descripcion": "Pabellón construido para representar a Chile en la Exposición Universal de París de 1889 (la misma de la Torre Eiffel). Desmontado y transportado en barco para rearmarse en la Quinta Normal de Santiago.",
        "fuente_url": "https://www.artequin.cl",
        "materiales_principales": ["Hierro fundido", "Acero zincado", "Vidrio policromado", "Cerámicas esmaltadas"]
    },
    {
        "id": "frigorifico-bories-puerto-natales",
        "nombre_proyecto": "Frigorífico Bories",
        "arquitecto": "Joseph Greenwood",
        "arquitecto_principal": "Joseph Greenwood",
        "colaboradores": "Ingenieros de la Sociedad Explotadora de Tierra del Fuego",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Puerto Bories, 5 km al norte de Puerto Natales",
        "ciudad": "Puerto Natales",
        "pais": "Chile",
        "coordenadas": {"lat": -51.6917, "lng": -72.5333},
        "ano_diseno": "1913",
        "anos_construccion": "1913-1915",
        "ano_inauguracion": "1915",
        "estilos": ["Arquitectura del Hierro y Cristal", "Funcionalismo"],
        "programa": ["Infraestructura", "Hospedaje"],
        "descripcion": "El mayor complejo agroindustrial de la Patagonia austral, levantado en ladrillo y acero inglés con generador a vapor. Transformado en el hotel de patrimonio The Singular Patagonia.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/antiguo-frigorifico-bories",
        "materiales_principales": ["Albañilería de ladrillo", "Acero corrugado", "Maquinaria de hierro a vapor"]
    },
    {
        "id": "iglesia-sagrado-corazon-puerto-varas",
        "nombre_proyecto": "Iglesia del Sagrado Corazón de Jesús",
        "arquitecto": "Bernardo Brinkmann",
        "arquitecto_principal": "Bernardo Brinkmann",
        "colaboradores": "Christian Göring; maestros carpinteros alemanes y chilotes",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "San Francisco 441",
        "ciudad": "Puerto Varas",
        "pais": "Chile",
        "coordenadas": {"lat": -41.3208, "lng": -72.9833},
        "ano_diseno": "1914",
        "anos_construccion": "1915-1918",
        "ano_inauguracion": "1918",
        "estilos": ["Historicismo"],
        "programa": ["Religioso"],
        "descripcion": "Icono de Puerto Varas con vistas al Lago Llanquihue y volcán Osorno. Inspirada en la Marienkirche de la Selva Negra alemana, construida con estructura de madera nativa y revestimiento de hierro galvanizado.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/iglesia-parroquial-sagrado-corazon-jesus-puerto-varas",
        "materiales_principales": ["Madera de ulmo y roble", "Chapas de fierro galvanizado"]
    },
    {
        "id": "palacio-montes-punta-arenas",
        "nombre_proyecto": "Palacio Montes",
        "arquitecto": "Antoine Beaulier",
        "arquitecto_principal": "Antoine Beaulier",
        "colaboradores": "Constructores magallánicos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza Muñoz Gamero 1028",
        "ciudad": "Punta Arenas",
        "pais": "Chile",
        "coordenadas": {"lat": -53.1639, "lng": -70.9089},
        "ano_diseno": "1898",
        "anos_construccion": "1898-1900",
        "ano_inauguracion": "1900",
        "estilos": ["Arquitectura Neoclásica", "Historicismo"],
        "programa": ["Institucional / Gubernamental"],
        "descripcion": "Elegante casona residencial decimonónica de estilo neoclásico francés frente a la Plaza de Armas de Punta Arenas, actual sede de la Ilustre Municipalidad de Punta Arenas.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Albañilería estucada", "Madera", "Cubierta de zinc"]
    },
    {
        "id": "teatro-municipal-de-iquique",
        "nombre_proyecto": "Teatro Municipal de Iquique",
        "arquitecto": "Diego y Eduardo Avendaño",
        "arquitecto_principal": "Diego y Eduardo Avendaño",
        "colaboradores": "Escenógrafos y talladores de madera de la época dorada salitrera",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza Prat",
        "ciudad": "Iquique",
        "pais": "Chile",
        "coordenadas": {"lat": -20.2133, "lng": -70.1517},
        "ano_diseno": "1889",
        "anos_construccion": "1889-1890",
        "ano_inauguracion": "1890",
        "estilos": ["Arquitectura Neoclásica", "Historicismo"],
        "programa": ["Cultural"],
        "descripcion": "Construido enteramente en madera de pino oregón con técnica de 'balloon frame' durante el auge salitrero. Sala lírica decorada con querubines y pinturas en cielos rasos por artistas europeos.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/teatro-municipal-iquique",
        "materiales_principales": ["Madera de pino oregón", "Yesería", "Pintura al fresco"]
    }
]

print(f"Period 2 defined: {len(period_2)} projects.")
