#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Period 3: Movimiento Moderno e Infraestructura del Estado (1930 – 1960)"""

period_3 = [
    {
        "id": "edificio-santa-lucia-barco-santiago",
        "nombre_proyecto": "Edificio Santa Lucía \"Barco\"",
        "arquitecto": "Sergio Larraín García-Moreno y Jorge Arteaga",
        "arquitecto_principal": "Sergio Larraín García-Moreno",
        "colaboradores": "Jorge Arteaga",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Santa Lucía 382 esq. Merced",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4389, "lng": -70.6439},
        "ano_diseno": "1932",
        "anos_construccion": "1933-1934",
        "ano_inauguracion": "1934",
        "estilos": ["Racionalismo", "Art Déco"],
        "programa": ["Vivienda"],
        "descripcion": "Máxima expresión de la corriente náutica ('estilo barco') del racionalismo moderno en Chile. Su volumen curvo frente al Cerro Santa Lucía evoca la proa de un transatlántico con barandas tubulares y ojos de buey.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Vidrio", "Acero naval"]
    },
    {
        "id": "escuela-de-derecho-universidad-de-chile",
        "nombre_proyecto": "Escuela de Derecho de la Universidad de Chile",
        "arquitecto": "Juan Martínez Gutiérrez",
        "arquitecto_principal": "Juan Martínez Gutiérrez",
        "colaboradores": "Dirección de Arquitectura MOP",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Pío Nono 1, Providencia/Recoleta",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4358, "lng": -70.6358},
        "ano_diseno": "1934",
        "anos_construccion": "1935-1938",
        "ano_inauguracion": "1938",
        "estilos": ["Racionalismo", "Art Déco", "Funcionalismo"],
        "programa": ["Educacional"],
        "descripcion": "Obra cumbre de Juan Martínez Gutiérrez. Magnífica fachada curva monumental que remata el eje del Río Mapocho y Plaza Baquedano con una columnata dórica simplificada y gran aula magna elíptica.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/facultad-derecho-universidad-chile",
        "materiales_principales": ["Hormigón armado visto", "Mármol travertino", "Bronce"]
    },
    {
        "id": "escuela-militar-de-santiago",
        "nombre_proyecto": "Escuela Militar de Santiago",
        "arquitecto": "Juan Martínez Gutiérrez",
        "arquitecto_principal": "Juan Martínez Gutiérrez",
        "colaboradores": "Ministerio de Defensa y MOP",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Los Militares 4500",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4158, "lng": -70.5847},
        "ano_diseno": "1940",
        "anos_construccion": "1943-1958",
        "ano_inauguracion": "1958",
        "estilos": ["Racionalismo", "Funcionalismo", "Brutalismo"],
        "programa": ["Institucional / Gubernamental", "Educacional"],
        "descripcion": "Conjunto castrense monumental en el sector oriente de Santiago, caracterizado por su rigor volumétrico, severas galerías de pórticos de hormigón a la vista y gran patio de honor Alpatacal.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/escuela-militar-libertador-bernardo-ohiggins",
        "materiales_principales": ["Hormigón armado visto", "Granito", "Vidrio"]
    },
    {
        "id": "templo-votivo-de-maipu",
        "nombre_proyecto": "Templo Votivo de Maipú",
        "arquitecto": "Juan Martínez Gutiérrez",
        "arquitecto_principal": "Juan Martínez Gutiérrez",
        "colaboradores": "Cálculo estructural por Rodrigo Flores; vitrales por Adolfo Winternitz",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Carmen con 5 de Abril, Maipú",
        "ciudad": "Maipú",
        "pais": "Chile",
        "coordenadas": {"lat": -33.5117, "lng": -70.7578},
        "ano_diseno": "1948",
        "anos_construccion": "1948-1974",
        "ano_inauguracion": "1974",
        "estilos": ["Racionalismo", "Expresionismo", "Brutalismo"],
        "programa": ["Religioso"],
        "descripcion": "Monumento votivo nacional a la Virgen del Carmen en el sitio de la Batalla de Maipú. Singular estructura piramidal en hormigón armado con 88 metros de altura y conmovedores vitrales expresionistas.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/santuario-nacional-templo-votivo-maipu",
        "materiales_principales": ["Hormigón armado martillina", "Vitrales de cristal templado", "Cobre"]
    },
    {
        "id": "hotel-antumalal-pucon",
        "nombre_proyecto": "Hotel Antumalal",
        "arquitecto": "Jorge Elton",
        "arquitecto_principal": "Jorge Elton",
        "colaboradores": "Diseño interior por Cristian Valdés; paisajismo por Guillermo Pollak",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Km 2 camino Pucón-Villarrica",
        "ciudad": "Pucón",
        "pais": "Chile",
        "coordenadas": {"lat": -39.2736, "lng": -71.9961},
        "ano_diseno": "1944",
        "anos_construccion": "1945-1950",
        "ano_inauguracion": "1950",
        "estilos": ["Organicismo", "Racionalismo"],
        "programa": ["Hospedaje"],
        "descripcion": "Joya de la arquitectura orgánica moderna en Chile, influenciada por Frank Lloyd Wright. Emplazado sobre un farellón rocoso sobre el Lago Villarrica integrando piedra volcánica, maderas nativas y chimeneas de hierro.",
        "fuente_url": "https://www.antumalal.com/es/historia",
        "materiales_principales": ["Piedra volcánica local", "Madera nativa de roble y coigüe", "Hormigón", "Vidrio"]
    },
    {
        "id": "estacion-biologia-marina-montemar",
        "nombre_proyecto": "Estación de Biología Marina de Montemar",
        "arquitecto": "Enrique Gebhard",
        "arquitecto_principal": "Enrique Gebhard",
        "colaboradores": "Universidad de Chile, Facultad de Ciencias",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Playa de Montemar, Reñaca",
        "ciudad": "Viña del Mar",
        "pais": "Chile",
        "coordenadas": {"lat": -32.9625, "lng": -71.5519},
        "ano_diseno": "1941",
        "anos_construccion": "1941-1951",
        "ano_inauguracion": "1951",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Educacional", "Cultural"],
        "descripcion": "Hito indiscutido de la modernidad corbusiana adaptada al borde costero chileno. Diseñada por Enrique Gebhard escalonando terrazas de hormigón armado sobre las rocas de Montemar.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Vidrio marino", "Granito costero"]
    },
    {
        "id": "edificio-cap-ducal-vina-del-mar",
        "nombre_proyecto": "Edificio Cap Ducal",
        "arquitecto": "Roberto Dávila Carson",
        "arquitecto_principal": "Roberto Dávila Carson",
        "colaboradores": "Ingenieros de obras marinas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Marina 51",
        "ciudad": "Viña del Mar",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0208, "lng": -71.5622},
        "ano_diseno": "1936",
        "anos_construccion": "1936",
        "ano_inauguracion": "1936",
        "estilos": ["Racionalismo"],
        "programa": ["Hospedaje", "Comercial"],
        "descripcion": "Singular edificio-barco fundado sobre los roqueríos costeros de Viña del Mar, concebido por Roberto Dávila (discípulo de Le Corbusier en París) como una nave zarpando hacia el Pacífico.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado fundado en roca marina", "Barandas náuticas", "Vidrio"]
    },
    {
        "id": "edificio-copacabana-vina-del-mar",
        "nombre_proyecto": "Edificio Copacabana",
        "arquitecto": "Jaime Besa y Larraín + Larraín",
        "arquitecto_principal": "Jaime Besa",
        "colaboradores": "Osvaldo Larraín Echenique, Jaime Larraín",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "1 Norte con Av. Perú",
        "ciudad": "Viña del Mar",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0119, "lng": -71.5514},
        "ano_diseno": "1950",
        "anos_construccion": "1950-1951",
        "ano_inauguracion": "1951",
        "estilos": ["Racionalismo", "Estilo Internacional"],
        "programa": ["Vivienda"],
        "descripcion": "Primer gran bloque residencial moderno frente al mar en Viña del Mar. Presenta una fachada modulada en retícula de balcones profundos con brise-soleil y planta libre en el acceso.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Celosías de protección solar", "Vidrio"]
    },
    {
        "id": "poblacion-rios-de-chile-concepcion",
        "nombre_proyecto": "Población Ríos de Chile",
        "arquitecto": "CORVI (Corporación de la Vivienda)",
        "arquitecto_principal": "CORVI",
        "colaboradores": "Equipo técnico de arquitectos del Estado",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Lorenzo Arenas, Concepción",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8167, "lng": -73.0417},
        "ano_diseno": "1954",
        "anos_construccion": "1954-1956",
        "ano_inauguracion": "1956",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Emblemático conjunto de vivienda social moderna post-terremoto del 39 y 60 en Concepción, proyectado bajo principios higienistas con bloques orientados al sol y amplias áreas verdes comunitarias.",
        "fuente_url": "https://www.corvi.cl",
        "materiales_principales": ["Albañilería de ladrillo", "Hormigón armado", "Madera"]
    },
    {
        "id": "poblacion-exequiel-gonzalez-cortes",
        "nombre_proyecto": "Población Ex-Exequiel González Cortés",
        "arquitecto": "Jaime Larraín y asociados",
        "arquitecto_principal": "Jaime Larraín",
        "colaboradores": "Osvaldo Larraín, Jaime Sanfuentes",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Gran Avenida, Comuna de San Miguel",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4833, "lng": -70.6417},
        "ano_diseno": "1949",
        "anos_construccion": "1950-1952",
        "ano_inauguracion": "1952",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Conjunto habitacional pionero de la Caja de la Habitación Popular que integró bloques de cuatro pisos con amplias áreas libres, equipamiento y locales comerciales de barrio.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Albañilería confinada", "Ladrillo"]
    },
    {
        "id": "edificio-radio-mineria-santiago",
        "nombre_proyecto": "Edificio de la Radio Minería",
        "arquitecto": "Emilio Duhart y Sergio Larraín G.M.",
        "arquitecto_principal": "Emilio Duhart",
        "colaboradores": "Sergio Larraín García-Moreno",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Moneda 759",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4419, "lng": -70.6508},
        "ano_diseno": "1949",
        "anos_construccion": "1950-1951",
        "ano_inauguracion": "1951",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Comercial", "Institucional / Gubernamental"],
        "descripcion": "Refinado ejemplo de la modernidad corporativa y de telecomunicaciones del centro de Santiago, con fachada muraria limpia, elegantes carpinterías metálicas y auditorio acústico.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Aluminio anodizado", "Aislamiento acústico de madera"]
    },
    {
        "id": "seminario-pontificio-mayor-santiago",
        "nombre_proyecto": "Seminario Pontificio Mayor de Santiago",
        "arquitecto": "Emilio Duhart",
        "arquitecto_principal": "Emilio Duhart",
        "colaboradores": "Equipo de arquitectos asociados",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Walker Martínez 2020",
        "ciudad": "La Florida",
        "pais": "Chile",
        "coordenadas": {"lat": -33.5250, "lng": -70.5667},
        "ano_diseno": "1948",
        "anos_construccion": "1949-1950",
        "ano_inauguracion": "1950",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Religioso", "Educacional"],
        "descripcion": "Magno complejo religioso y educacional en la precordillera de La Florida, organizado a través de patios claustrales reinterpretados en clave moderna con hormigón visto y celosías de ladrillo.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Ladrillo cocido visto", "Madera"]
    },
    {
        "id": "edificio-plaza-de-armas-santiago",
        "nombre_proyecto": "Edificio Plaza de Armas",
        "arquitecto": "Sergio Larraín G.M., Emilio Duhart, Osvaldo Larraín, Jaime Sanfuentes",
        "arquitecto_principal": "Sergio Larraín García-Moreno",
        "colaboradores": "Emilio Duhart, Osvaldo Larraín, Jaime Sanfuentes",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Monjitas esq. 21 de Mayo",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4372, "lng": -70.6508},
        "ano_diseno": "1953",
        "anos_construccion": "1954-1956",
        "ano_inauguracion": "1956",
        "estilos": ["Racionalismo", "Estilo Internacional"],
        "programa": ["Comercial", "Vivienda"],
        "descripcion": "El mayor manifiesto moderno en el centro histórico de Santiago. Bloque en altura con placa comercial pasante, pasajes peatonales interiores y departamentos con vistas a la Plaza de Armas.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado visto", "Mosaico veneciano", "Vidrio continuo"]
    },
    {
        "id": "poblacion-german-riesco-valparaiso",
        "nombre_proyecto": "Población Germán Riesco",
        "arquitecto": "CORVI (Corporación de la Vivienda)",
        "arquitecto_principal": "CORVI",
        "colaboradores": "Arquitectos de la delegación Valparaíso CORVI",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Cerro Barón",
        "ciudad": "Valparaíso",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0500, "lng": -71.6083},
        "ano_diseno": "1952",
        "anos_construccion": "1952-1954",
        "ano_inauguracion": "1954",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Conjunto habitacional escalonado en la pendiente del Cerro Barón, adaptando el racionalismo corbusiano a la topografía anfiteatral de Valparaíso con pasarelas y terrazas comunes.",
        "fuente_url": "https://www.corvi.cl",
        "materiales_principales": ["Albañilería de ladrillo", "Hormigón armado", "Muros de contención de piedra"]
    },
    {
        "id": "mercado-municipal-de-temuco",
        "nombre_proyecto": "Mercado Municipal de Temuco",
        "arquitecto": "Carlos de Landa",
        "arquitecto_principal": "Carlos de Landa",
        "colaboradores": "Dirección de Obras Municipales de Temuco",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Manuel Rodríguez 960",
        "ciudad": "Temuco",
        "pais": "Chile",
        "coordenadas": {"lat": -38.7389, "lng": -72.5906},
        "ano_diseno": "1928",
        "anos_construccion": "1928-1940",
        "ano_inauguracion": "1940",
        "estilos": ["Art Déco", "Funcionalismo"],
        "programa": ["Comercial"],
        "descripcion": "Gran hito comercial y patrimonial de La Araucanía. Manzana completa con esquinas curvas y detalles ornamentales Art Déco, que albergó el epicentro del intercambio artesanal mapuche y campesino.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/mercado-municipal-temuco",
        "materiales_principales": ["Albañilería reforzada", "Hormigón", "Cerchas de madera y fierro"]
    },
    {
        "id": "catedral-san-bartolome-chillan",
        "nombre_proyecto": "Catedral de San Bartolomé de Chillán",
        "arquitecto": "Hernán Larraín Errázuriz",
        "arquitecto_principal": "Hernán Larraín Errázuriz",
        "colaboradores": "Estructura por Juan E. Schmidt; escultura de Peter Horn",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Arauco con Libertad, Plaza de Armas",
        "ciudad": "Chillán",
        "pais": "Chile",
        "coordenadas": {"lat": -36.6067, "lng": -72.1028},
        "ano_diseno": "1939",
        "anos_construccion": "1940-1960",
        "ano_inauguracion": "1960",
        "estilos": ["Expresionismo", "Racionalismo"],
        "programa": ["Religioso"],
        "descripcion": "Símbolo de la reconstrucción moderna tras el devastador terremoto de Chillán de 1939. Célebre por su monumental secuencia de diez arcos parabólicos de hormigón armado y su campanario exento de 36 metros.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/catedral-san-bartolome-chillan",
        "materiales_principales": ["Hormigón armado visto", "Mosaicos", "Cobre"]
    },
    {
        "id": "casa-schonburn-valdivia",
        "nombre_proyecto": "Casa Schonburn",
        "arquitecto": "Tibor Wiener",
        "arquitecto_principal": "Tibor Wiener",
        "colaboradores": "Constructores valdivianos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Isla Teja / Calle Los Laureles",
        "ciudad": "Valdivia",
        "pais": "Chile",
        "coordenadas": {"lat": -39.8167, "lng": -73.2458},
        "ano_diseno": "1946",
        "anos_construccion": "1947-1948",
        "ano_inauguracion": "1948",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Diseñada por el destacado arquitecto húngaro formado en la Bauhaus Tibor Wiener durante su exilio en Chile. Una lección de composición racionalista de volúmenes puros en diálogo con el paisaje fluvial.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Madera nativa", "Grandes planos acristalados"]
    },
    {
        "id": "edificio-del-ex-seguro-obrero-santiago",
        "nombre_proyecto": "Edificio del Ex-Seguro Obrero",
        "arquitecto": "Ricardo González Cortés",
        "arquitecto_principal": "Ricardo González Cortés",
        "colaboradores": "Caja del Seguro Obrero Obligatorio",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Morandé 107 esq. Moneda",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4422, "lng": -70.6536},
        "ano_diseno": "1936",
        "anos_construccion": "1937-1939",
        "ano_inauguracion": "1939",
        "estilos": ["Racionalismo", "Art Déco"],
        "programa": ["Institucional / Gubernamental", "Comercial"],
        "descripcion": "Parte fundamental del Barrio Cívico de Santiago frente al Palacio de La Moneda. De severas líneas proto-modernas y Art Déco, con doce pisos de altura y revestimiento de piedra artificial granítica.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Piedra reconstituida", "Bronce"]
    },
    {
        "id": "edificio-central-universidad-concepcion",
        "nombre_proyecto": "Edificio Central de la Universidad de Concepción",
        "arquitecto": "Enrique San Martín",
        "arquitecto_principal": "Enrique San Martín",
        "colaboradores": "Dirección de Obras UdeC",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Barrio Universitario, UdeC",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8294, "lng": -73.0375},
        "ano_diseno": "1942",
        "anos_construccion": "1943-1945",
        "ano_inauguracion": "1945",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Educacional", "Institucional / Gubernamental"],
        "descripcion": "Edificio matriz del campus abierto penquista diseñado bajo el modelo de ciudad universitaria moderna, enmarcando el eje cívico ajardinado y el foro central.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/campus-universidad-concepcion",
        "materiales_principales": ["Hormigón armado", "Vidrio", "Enchapado pétreo"]
    },
    {
        "id": "foro-y-campanil-udec-concepcion",
        "nombre_proyecto": "Foro y Campanil UdeC",
        "arquitecto": "Enrique San Martín",
        "arquitecto_principal": "Enrique San Martín",
        "colaboradores": "Cálculo estructural por Luis Rossi",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Campus Universidad de Concepción",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8292, "lng": -73.0369},
        "ano_diseno": "1942",
        "anos_construccion": "1943-1944",
        "ano_inauguracion": "1943",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Educacional", "Cultural"],
        "descripcion": "Símbolo identitario indiscutido de Concepción y de la Universidad de Concepción. Torre campanario exenta de 42 metros de altura inspirada en la torre de San Marcos de Venecia pero depurada en sobrio hormigón moderno.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/campus-universidad-concepcion",
        "materiales_principales": ["Hormigón armado", "Reloj electromecánico alemán", "Campanas de bronce"]
    }
]

print(f"Period 3 defined: {len(period_3)} projects.")
