#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Period 4: Modernidad Radical, Estructuras Masivas y Vivienda Social (1960 – 1975)"""

period_4 = [
    {
        "id": "monasterio-benedictino-santisima-trinidad",
        "nombre_proyecto": "Monasterio Benedictino de la Santísima Trinidad",
        "arquitecto": "Martín Correa y Gabriel Guarda OSB",
        "arquitecto_principal": "Gabriel Guarda & Martín Correa",
        "colaboradores": "Monjes de la Abadía Benedictina",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Montecasino 960, Cerro Los Piques",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.3853, "lng": -70.5283},
        "ano_diseno": "1962",
        "anos_construccion": "1962-1964",
        "ano_inauguracion": "1964",
        "estilos": ["Racionalismo", "Minimalismo", "Brutalismo"],
        "programa": ["Religioso"],
        "descripcion": "Obra cumbre de la arquitectura religiosa moderna del siglo XX. Dos cubos blancos desfasados por donde la luz natural penetra cenitalmente y baña los muros esculpidos de hormigón creando una atmósfera de recogimiento absoluto.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/capilla-monasterio-benedictinos",
        "materiales_principales": ["Hormigón armado pintado a la cal", "Madera", "Luz cenital"]
    },
    {
        "id": "edificio-cepal-vitacura",
        "nombre_proyecto": "Edificio de la CEPAL",
        "arquitecto": "Emilio Duhart",
        "arquitecto_principal": "Emilio Duhart",
        "colaboradores": "Roberto Goycoolea, Christian de Groote, Alberto Montealegre",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Dag Hammarskjöld 3477",
        "ciudad": "Vitacura",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4025, "lng": -70.6019},
        "ano_diseno": "1960",
        "anos_construccion": "1962-1966",
        "ano_inauguracion": "1966",
        "estilos": ["Brutalismo", "Racionalismo"],
        "programa": ["Institucional / Gubernamental"],
        "descripcion": "Hito maestro del brutalismo latinoamericano. Anillo cuadrado suspendido sobre 28 pilares de hormigón a orillas del Río Mapocho, coronado por un caracol helicoidal decorado con relieves que narran la historia de América Latina.",
        "fuente_url": "https://www.cepal.org/es/historia-de-la-cepal/edificio-de-la-cepal",
        "materiales_principales": ["Hormigón armado visto con árido de río", "Vidrio", "Cobre"]
    },
    {
        "id": "unidad-vecinal-portales",
        "nombre_proyecto": "Unidad Vecinal Portales",
        "arquitecto": "Bresciani, Valdés, Castillo, Huidobro (BVCH)",
        "arquitecto_principal": "Bresciani, Valdés, Castillo, Huidobro (BVCH)",
        "colaboradores": "Caja de Previsión de Empleados Particulares",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Portales con Las Sophoras, Quinta Normal",
        "ciudad": "Estación Central",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4503, "lng": -70.6869},
        "ano_diseno": "1954",
        "anos_construccion": "1954-1962",
        "ano_inauguracion": "1962",
        "estilos": ["Racionalismo", "Brutalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Magno complejo de vivienda colectiva de 31 hectáreas y cerca de 2.000 viviendas. Destaca por sus pasarelas aéreas peatonales que conectan bloques flotantes sobre un gran parque continuo.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado visto", "Ladrillo acústico", "Mosaico cerámico"]
    },
    {
        "id": "unidad-vecinal-providencia",
        "nombre_proyecto": "Unidad Vecinal Providencia",
        "arquitecto": "Carlos Bresciani, Héctor Valdés, Fernando Castillo, Carlos Huidobro",
        "arquitecto_principal": "Bresciani, Valdés, Castillo, Huidobro (BVCH)",
        "colaboradores": "Caja de Empleados Particulares",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Providencia con Antonio Varas",
        "ciudad": "Providencia",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4289, "lng": -70.6139},
        "ano_diseno": "1953",
        "anos_construccion": "1953-1967",
        "ano_inauguracion": "1967",
        "estilos": ["Racionalismo", "Estilo Internacional"],
        "programa": ["Vivienda", "Comercial"],
        "descripcion": "Conjunto residencial de alta densidad que liberó el 85% del suelo para áreas verdes y comercio barrial, con esbeltas torres y bloques bajos interconectados en el corazón de Providencia.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado visto", "Celosías", "Vidrio"]
    },
    {
        "id": "edificio-copelec-chillan",
        "nombre_proyecto": "Edificio COPELEC",
        "arquitecto": "Juan Borchers, Jesús Bermejo e Isidro Suárez",
        "arquitecto_principal": "Juan Borchers",
        "colaboradores": "Jesús Bermejo, Isidro Suárez",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Maipón 1079",
        "ciudad": "Chillán",
        "pais": "Chile",
        "coordenadas": {"lat": -36.6111, "lng": -72.1000},
        "ano_diseno": "1962",
        "anos_construccion": "1962-1964",
        "ano_inauguracion": "1964",
        "estilos": ["Brutalismo", "Expresionismo"],
        "programa": ["Institucional / Gubernamental", "Comercial"],
        "descripcion": "Icono radical del brutalismo escultórico en hormigón a nivel mundial. Juan Borchers aplicó su rigurosa teoría de proporciones modulares plásticas creando lucernarios orgánicos y chimeneas lumínicas extraordinarias.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/edificio-cooperativa-electrica-chillan-copelec",
        "materiales_principales": ["Hormigón armado visto martillina", "Vidrio", "Piel de hormigón fluido"]
    },
    {
        "id": "torres-de-san-borja-santiago",
        "nombre_proyecto": "Torres de San Borja",
        "arquitecto": "CORMU (Corporación de Mejoramiento Urbano)",
        "arquitecto_principal": "CORMU",
        "colaboradores": "Equipo CORMU liderado por Eduardo San Martín, Gastón Etcheverry et al.",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Barrio San Borja, Av. Portugal con Alameda",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4417, "lng": -70.6375},
        "ano_diseno": "1968",
        "anos_construccion": "1969-1974",
        "ano_inauguracion": "1974",
        "estilos": ["Racionalismo", "Brutalismo"],
        "programa": ["Vivienda", "Comercial"],
        "descripcion": "Plan de renovación urbana moderno de mayor escala en el centro de Santiago, compuesto por más de 20 torres residenciales en torno al Parque San Borja articuladas por pasarelas elevadas de segundo nivel.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Vidrio", "Pasarelas de acero y hormigón"]
    },
    {
        "id": "villa-san-luis-las-condes",
        "nombre_proyecto": "Villa San Luis",
        "arquitecto": "CORMU / Miguel Lawner y equipo",
        "arquitecto_principal": "Miguel Lawner",
        "colaboradores": "Corporación de Mejoramiento Urbano (CORMU)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Presidente Riesco con Urano",
        "ciudad": "Las Condes",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4072, "lng": -70.5786},
        "ano_diseno": "1971",
        "anos_construccion": "1971-1972",
        "ano_inauguracion": "1972",
        "estilos": ["Racionalismo", "Brutalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Histórico proyecto de integración social urbana que construyó bloques de vivienda digna para familias obreras en los predios de Las Condes mediante el sistema de prefabricación de hormigón KPD.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/lote-18-a-villa-san-luis",
        "materiales_principales": ["Paneles de hormigón armado prefabricado KPD", "Acero"]
    },
    {
        "id": "edificio-unctad-iii-gam",
        "nombre_proyecto": "Edificio UNCTAD III / Centro Cultural GAM",
        "arquitecto": "José Covacevic, Hugo Gaggero, Juan Echenique, José Medina, Miguel Lawner",
        "arquitecto_principal": "José Covacevic",
        "colaboradores": "Hugo Gaggero, Juan Echenique, José Medina, Miguel Lawner (Dirección CORMU)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Libertador Bernardo O'Higgins 227",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4397, "lng": -70.6406},
        "ano_diseno": "1971",
        "anos_construccion": "1971-1972",
        "ano_inauguracion": "1972",
        "estilos": ["Brutalismo", "High-Tech", "Racionalismo"],
        "programa": ["Cultural", "Institucional / Gubernamental"],
        "descripcion": "Construido en récord de 275 días para la Conferencia UNCTAD III de 1972 con vigas de acero corten oxidado, gran cubierta metálica y 30 obras de arte integradas a la arquitectura.",
        "fuente_url": "https://www.gam.cl/el-edificio",
        "materiales_principales": ["Acero corten patinable", "Hormigón armado visto", "Vidrio"]
    },
    {
        "id": "ciudad-abierta-amereida-ritoque",
        "nombre_proyecto": "Ciudad Abierta de Amereida",
        "arquitecto": "Escuela de Arquitectura PUCV / Alberto Cruz, Godofredo Iommi et al.",
        "arquitecto_principal": "Alberto Cruz Covarrubias",
        "colaboradores": "Godofredo Iommi, Claudio Girola, Fabio Cruz, poetas, diseñadores y arquitectos PUCV",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Dunas de Ritoque, Comuna de Quintero",
        "ciudad": "Ritoque",
        "pais": "Chile",
        "coordenadas": {"lat": -32.8872, "lng": -71.5133},
        "ano_diseno": "1970",
        "anos_construccion": "1971-Presente",
        "ano_inauguracion": "1971",
        "estilos": ["Organicismo", "Deconstructivismo"],
        "programa": ["Educacional", "Vivienda", "Cultural"],
        "descripcion": "Comunidad poético-arquitectónica experimental fundada en 270 hectáreas de dunas frente al Pacífico. Sus hospederías, ágoras y palacios del alba son construidos sobre la base de la poesía y el cálculo intuitivo del viento.",
        "fuente_url": "https://www.amereida.cl",
        "materiales_principales": ["Madera", "Ladrillo", "Chapas metálicas", "Hormigón", "Arena"]
    },
    {
        "id": "torres-del-paine-santiago-corvi",
        "nombre_proyecto": "Conjunto Habitacional Torres del Paine",
        "arquitecto": "CORVI (Corporación de la Vivienda)",
        "arquitecto_principal": "CORVI",
        "colaboradores": "Departamento Técnico CORVI",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Departamental con Froilán Roa",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.5042, "lng": -70.6014},
        "ano_diseno": "1966",
        "anos_construccion": "1967-1968",
        "ano_inauguracion": "1968",
        "estilos": ["Brutalismo", "Racionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Conjunto de vivienda social en altura compuesto por torres de hormigón armado a la vista y bloques puente que marcaron el perfil suroriente de Santiago con rigor funcionalista.",
        "fuente_url": "https://www.corvi.cl",
        "materiales_principales": ["Hormigón armado visto", "Albañilería de bloques", "Madera"]
    },
    {
        "id": "poblacion-chinchorro-arica",
        "nombre_proyecto": "Población Chinchorro",
        "arquitecto": "CORVI (Corporación de la Vivienda)",
        "arquitecto_principal": "CORVI",
        "colaboradores": "Junta de Adelanto de Arica",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Playa Chinchorro",
        "ciudad": "Arica",
        "pais": "Chile",
        "coordenadas": {"lat": -18.4556, "lng": -70.3014},
        "ano_diseno": "1960",
        "anos_construccion": "1961-1962",
        "ano_inauguracion": "1962",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Pionero conjunto habitacional impulsado por la Junta de Adelanto de Arica para el Mundial de Fútbol de 1962, con arquitectura moderna adaptada al clima desértico costero mediante celosías y ventilación cruzada.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Bloques de cemento", "Celosías prefabricadas"]
    },
    {
        "id": "villa-olimpica-nunoa",
        "nombre_proyecto": "Villa Olímpica",
        "arquitecto": "Rodolfo Oyarzún, Sergio González, Paulino Moreno",
        "arquitecto_principal": "Rodolfo Oyarzún",
        "colaboradores": "Sergio González, Paulino Moreno; CORVI",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Grecia con Salvador, Ñuñoa",
        "ciudad": "Ñuñoa",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4611, "lng": -70.6194},
        "ano_diseno": "1960",
        "anos_construccion": "1961-1962",
        "ano_inauguracion": "1962",
        "estilos": ["Racionalismo", "Brutalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Barrio residencial ejemplar construido junto al Estadio Nacional para albergar turistas del Mundial de 1962. Destaca por su articulación de bloques de 4 y 5 pisos con áreas verdes continuas y equipamiento vecinal.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/zonas-tipicas/villa-olimpica",
        "materiales_principales": ["Hormigón armado", "Ladrillo a la vista", "Madera"]
    },
    {
        "id": "edificio-caja-reaseguradora-santiago",
        "nombre_proyecto": "Edificio de la Caja Reaseguradora",
        "arquitecto": "Bresciani, Valdés, Castillo, Huidobro (BVCH)",
        "arquitecto_principal": "Bresciani, Valdés, Castillo, Huidobro (BVCH)",
        "colaboradores": "Caja Reaseguradora de Chile",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Miraflores 222",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4408, "lng": -70.6475},
        "ano_diseno": "1965",
        "anos_construccion": "1966-1968",
        "ano_inauguracion": "1968",
        "estilos": ["Brutalismo", "Racionalismo"],
        "programa": ["Institucional / Gubernamental", "Comercial"],
        "descripcion": "Edificio corporativo en altura en el centro de Santiago con poderosa fachada de hormigón armado visto y parteluces escultóricos que proporcionan protección solar y control térmico pasivo.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado visto", "Vidrio termopanel", "Granito"]
    },
    {
        "id": "campus-san-joaquin-puc-master-plan",
        "nombre_proyecto": "Campus San Joaquín PUC (Master Plan)",
        "arquitecto": "Jaime Bellalta",
        "arquitecto_principal": "Jaime Bellalta",
        "colaboradores": "Escuela de Arquitectura PUC",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Vicuña Mackenna 4860",
        "ciudad": "San Joaquín",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4994, "lng": -70.6139},
        "ano_diseno": "1963",
        "anos_construccion": "1965-Presente",
        "ano_inauguracion": "1965",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Educacional"],
        "descripcion": "Plan maestro para el campus universitario de 45 hectáreas de la Universidad Católica, concebido como una cuadrícula ajardinada de facultades vinculadas por avenidas peatonales arboladas y claustros modernos.",
        "fuente_url": "https://www.uc.cl",
        "materiales_principales": ["Hormigón armado", "Ladrillo visto", "Estructuras metálicas", "Paisajismo"]
    },
    {
        "id": "la-tortuga-de-talcahuano",
        "nombre_proyecto": "Gimnasio Municipal de Concepción / La Tortuga de Talcahuano",
        "arquitecto": "José Llambías Merchant",
        "arquitecto_principal": "José Llambías Merchant",
        "colaboradores": "Ingenieros calculistas de cubiertas hiperbólicas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Blanco Encalada s/n",
        "ciudad": "Talcahuano",
        "pais": "Chile",
        "coordenadas": {"lat": -36.7250, "lng": -73.1167},
        "ano_diseno": "1957",
        "anos_construccion": "1957-1980",
        "ano_inauguracion": "1980",
        "estilos": ["Expresionismo", "Brutalismo"],
        "programa": ["Deportivo", "Cultural"],
        "descripcion": "Hazaña estructural de la arquitectura deportiva latinoamericana. Su colosal cubierta suspendida en paraboloide hiperbólico simula el caparazón de una tortuga marina sobre el puerto de Talcahuano con capacidad para 10.000 personas.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Hormigón armado", "Cables tensores de acero", "Cubierta de aluminio"]
    },
    {
        "id": "sede-escuela-de-musica-udec",
        "nombre_proyecto": "Sede de la Escuela de Música UdeC",
        "arquitecto": "Osvaldo Cáceres González",
        "arquitecto_principal": "Osvaldo Cáceres González",
        "colaboradores": "Facultad de Artes y Música UdeC",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Campus Universidad de Concepción",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8306, "lng": -73.0361},
        "ano_diseno": "1962",
        "anos_construccion": "1963-1964",
        "ano_inauguracion": "1964",
        "estilos": ["Organicismo", "Brutalismo"],
        "programa": ["Educacional", "Cultural"],
        "descripcion": "Edificio expresivo de Osvaldo Cáceres que traduce los ritmos armónicos de la música a planos quebrados de hormigón armado, lucernarios acústicos cenitales y revestimientos de madera.",
        "fuente_url": "https://www.udec.cl",
        "materiales_principales": ["Hormigón visto", "Madera acústica", "Vidrio"]
    },
    {
        "id": "mercado-central-de-concepcion",
        "nombre_proyecto": "Mercado Central de Concepción",
        "arquitecto": "Fernando de la Cruz y Tibor Wiener",
        "arquitecto_principal": "Fernando de la Cruz",
        "colaboradores": "Tibor Wiener",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Caupolicán con Maipú",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8250, "lng": -73.0528},
        "ano_diseno": "1939",
        "anos_construccion": "1940",
        "ano_inauguracion": "1940",
        "estilos": ["Racionalismo", "Expresionismo"],
        "programa": ["Comercial"],
        "descripcion": "Icono de la arquitectura moderna del sur de Chile proyectado tras el terremoto de 1939 por Tibor Wiener y Fernando de la Cruz, con una audaz bóveda central parabólica de hormigón armado que flotaba sobre los puestos.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/mercado-central-concepcion",
        "materiales_principales": ["Hormigón armado en bóveda", "Vidrio", "Albañilería"]
    },
    {
        "id": "iglesia-virgen-del-transito-metrenco",
        "nombre_proyecto": "Iglesia de la Virgen del Tránsito de Metrenco",
        "arquitecto": "Fray Bernabé de Lucerna",
        "arquitecto_principal": "Fray Bernabé de Lucerna",
        "colaboradores": "Comunidades mapuches de Metrenco y padres capuchinos",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Ruta 5 Sur Km 685, Metrenco",
        "ciudad": "Padre Las Casas",
        "pais": "Chile",
        "coordenadas": {"lat": -38.8333, "lng": -72.6333},
        "ano_diseno": "1958",
        "anos_construccion": "1958-1960",
        "ano_inauguracion": "1960",
        "estilos": ["Organicismo", "Racionalismo"],
        "programa": ["Religioso"],
        "descripcion": "Santuario rural de líneas expresivas en madera y piedra que dialoga con la cosmovisión y el paisaje de La Araucanía, concebido por el fraile y arquitecto suizo Bernabé de Lucerna.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Piedra rústica", "Madera nativa", "Tejas de alerce"]
    },
    {
        "id": "poblacion-lord-cochrane-antofagasta",
        "nombre_proyecto": "Población Lord Cochrane",
        "arquitecto": "CORVI (Corporación de la Vivienda)",
        "arquitecto_principal": "CORVI",
        "colaboradores": "Delegación Regional CORVI Antofagasta",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Sector Centro-Sur, Antofagasta",
        "ciudad": "Antofagasta",
        "pais": "Chile",
        "coordenadas": {"lat": -23.6583, "lng": -70.4000},
        "ano_diseno": "1962",
        "anos_construccion": "1963-1964",
        "ano_inauguracion": "1964",
        "estilos": ["Racionalismo", "Funcionalismo"],
        "programa": ["Vivienda"],
        "descripcion": "Complejo habitacional del Estado planificado para familias trabajadoras portuarias y mineras del norte de Chile, con bloques modulados de hormigón adaptados al asoleamiento desértico costero.",
        "fuente_url": "https://www.corvi.cl",
        "materiales_principales": ["Hormigón armado", "Bloques de cemento vibrocomprimido"]
    },
    {
        "id": "edificio-intendencia-region-del-biobio",
        "nombre_proyecto": "Edificio de la Intendencia de la Región del Biobío",
        "arquitecto": "Alejandro Rodríguez",
        "arquitecto_principal": "Alejandro Rodríguez",
        "colaboradores": "Ministerio de Obras Públicas",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Aníbal Pinto 442",
        "ciudad": "Concepción",
        "pais": "Chile",
        "coordenadas": {"lat": -36.8278, "lng": -73.0508},
        "ano_diseno": "1968",
        "anos_construccion": "1968-1970",
        "ano_inauguracion": "1970",
        "estilos": ["Brutalismo", "Racionalismo"],
        "programa": ["Institucional / Gubernamental"],
        "descripcion": "Edificio de gobierno regional de potente lenguaje brutalista frente a la Plaza de la Independencia de Concepción, caracterizado por sus vigas y losas de hormigón visto martillina en voladizo.",
        "fuente_url": "https://www.gorebiobio.cl",
        "materiales_principales": ["Hormigón armado visto", "Vidrio con filtro solar", "Madera"]
    }
]

print(f"Period 4 defined: {len(period_4)} projects.")
