#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Script to add requested Chilean architectural projects across 6 historical periods."""

import json

# Period 1: Período Colonial e Histórico (Siglos XVI – XIX)
period_1 = [
    {
        "id": "iglesia-convento-san-francisco-santiago",
        "nombre_proyecto": "Iglesia y Convento de San Francisco",
        "arquitecto": "Anónimo / Fray Francisco de la Cruz",
        "arquitecto_principal": "Fray Francisco de la Cruz",
        "colaboradores": "Canteros indígenas y mestizos coloniales",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Libertador Bernardo O'Higgins con Londres",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4442, "lng": -70.6483},
        "ano_diseno": "1572",
        "anos_construccion": "1572-1618",
        "ano_inauguracion": "1618",
        "estilos": ["Arquitectura Renacentista", "Arquitectura Barroca"],
        "programa": ["Religioso", "Cultural"],
        "descripcion": "El edificio arquitectónico en pie más antiguo de Santiago, testimonio mayor de la arquitectura virreinal chilena con gruesos muros de sillería de piedra canteada, artesonado mudéjar en madera y torre característica.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/iglesia-convento-san-francisco",
        "materiales_principales": ["Piedra", "Madera nativa", "Adobe"]
    },
    {
        "id": "catedral-metropolitana-santiago",
        "nombre_proyecto": "Catedral Metropolitana de Santiago",
        "arquitecto": "Joaquín Toesca, Ignacio Cremonesi",
        "arquitecto_principal": "Joaquín Toesca",
        "colaboradores": "Ignacio Cremonesi (remodelación siglo XIX), Matías Vásquez de Acuña",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza de Armas",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4378, "lng": -70.6514},
        "ano_diseno": "1748",
        "anos_construccion": "1748-1800",
        "ano_inauguracion": "1800",
        "estilos": ["Arquitectura Neoclásica", "Arquitectura Barroca"],
        "programa": ["Religioso"],
        "descripcion": "Templo mayor de la arquidiócesis de Santiago frente a la Plaza de Armas. Iniciada en época virreinal y transformada por Joaquín Toesca en monumental lenguaje neoclásico con fachada de pilastras corintias y frontones de piedra.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/catedral-santiago",
        "materiales_principales": ["Piedra canteada", "Cal y canto", "Mármol"]
    },
    {
        "id": "palacio-la-moneda-santiago",
        "nombre_proyecto": "Palacio de La Moneda",
        "arquitecto": "Joaquín Toesca",
        "arquitecto_principal": "Joaquín Toesca",
        "colaboradores": "Agustín Cavallero, Juan José de Goycolea",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Moneda s/n, Barrio Cívico",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4429, "lng": -70.6539},
        "ano_diseno": "1784",
        "anos_construccion": "1784-1805",
        "ano_inauguracion": "1805",
        "estilos": ["Arquitectura Neoclásica"],
        "programa": ["Institucional / Gubernamental"],
        "descripcion": "Obra cumbre de Joaquín Toesca y sede del gobierno de Chile. Ejemplo fundamental del neoclasicismo puro hispanoamericano, destacando su simetría rigurosa, patios interiores y fachada de orden toscano.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-moneda",
        "materiales_principales": ["Ladrillo cocido", "Piedra de sillería", "Cal y canto"]
    },
    {
        "id": "casa-colorada-santiago",
        "nombre_proyecto": "Casa Colorada",
        "arquitecto": "Joseph de la Vega",
        "arquitecto_principal": "Joseph de la Vega",
        "colaboradores": "Artesanos y constructores coloniales",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Merced 860",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4388, "lng": -70.6496},
        "ano_diseno": "1769",
        "anos_construccion": "1769-1779",
        "ano_inauguracion": "1779",
        "estilos": ["Arquitectura Barroca", "Arquitectura Neoclásica"],
        "programa": ["Vivienda", "Cultural"],
        "descripcion": "Residencia señorial colonial construida para Mateo de Toro y Zambrano. Destaca por su fachada de piedra sillar revestida en rojo almagre, portada de dos pisos con arquería y balconería de hierro.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/casa-colorada",
        "materiales_principales": ["Piedra sillar", "Ladrillo", "Madera de canelo", "Hierro forjado"]
    },
    {
        "id": "posada-del-corregidor-santiago",
        "nombre_proyecto": "Posada del Corregidor",
        "arquitecto": "Anónimo",
        "arquitecto_principal": "Anónimo",
        "colaboradores": "Constructores coloniales",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Esmeralda 749, Plaza Corregidor Zañartu",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4348, "lng": -70.6468},
        "ano_diseno": "1750",
        "anos_construccion": "1750-1770",
        "ano_inauguracion": "1770",
        "estilos": ["Arquitectura Colonial"],
        "programa": ["Hospedaje", "Cultural"],
        "descripcion": "Típico inmueble urbano colonial chileno del siglo XVIII, caracterizado por su balcón esquinero de madera sobre pilares, muros de adobe y tejas de arcilla cocida dispuestas a la usanza tradicional.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/posada-corregidor",
        "materiales_principales": ["Adobe", "Madera", "Teja de arcilla"]
    },
    {
        "id": "iglesia-la-matriz-valparaiso",
        "nombre_proyecto": "Iglesia de la Matriz",
        "arquitecto": "Lorenzo de la Maza",
        "arquitecto_principal": "Lorenzo de la Maza",
        "colaboradores": "Constructores porteños",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Calle Santo Domingo, Barrio Puerto",
        "ciudad": "Valparaíso",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0367, "lng": -71.6322},
        "ano_diseno": "1837",
        "anos_construccion": "1837-1842",
        "ano_inauguracion": "1842",
        "estilos": ["Arquitectura Neoclásica"],
        "programa": ["Religioso"],
        "descripcion": "Corazón fundacional del puerto de Valparaíso. Cuarto templo levantado en el sitio original tras terremotos, de estilo clasicista templario con columnas dóricas y frontón triangular de adobes y calicanto.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/iglesia-matriz-valparaiso",
        "materiales_principales": ["Adobe", "Madera", "Calicanto"]
    },
    {
        "id": "iglesia-santa-maria-loreto-achao",
        "nombre_proyecto": "Iglesia de Santa María de Loreto de Achao",
        "arquitecto": "Misioneros Jesuitas",
        "arquitecto_principal": "Misioneros Jesuitas",
        "colaboradores": "Carpinteros y maestros de ribera huilliches y chilotes",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Frente a Plaza de Armas de Achao, Isla Quinchao",
        "ciudad": "Achao, Chiloé",
        "pais": "Chile",
        "coordenadas": {"lat": -42.4697, "lng": -73.4917},
        "ano_diseno": "1730",
        "anos_construccion": "1740-1784",
        "ano_inauguracion": "1784",
        "estilos": ["Arquitectura Barroca"],
        "programa": ["Religioso"],
        "descripcion": "Monumento de la Escuela Chilota de Arquitectura Religiosa en Madera declarada Patrimonio de la Humanidad UNESCO. Destaca por su estructura ensamblada sin clavos metálicos con tarugos de luma y tejuelas de alerce.",
        "fuente_url": "https://whc.unesco.org/en/list/971",
        "materiales_principales": ["Madera de alerce", "Ciprés de las Guaitecas", "Mañío", "Tarugos de luma"]
    },
    {
        "id": "iglesia-san-francisco-castro",
        "nombre_proyecto": "Iglesia de San Francisco de Castro",
        "arquitecto": "Eduardo Provasoli",
        "arquitecto_principal": "Eduardo Provasoli",
        "colaboradores": "Salvador Sierpe, maestros carpinteros de Chiloé",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza de Armas de Castro",
        "ciudad": "Castro, Chiloé",
        "pais": "Chile",
        "coordenadas": {"lat": -42.4828, "lng": -73.7644},
        "ano_diseno": "1910",
        "anos_construccion": "1910-1912",
        "ano_inauguracion": "1912",
        "estilos": ["Historicismo"],
        "programa": ["Religioso"],
        "descripcion": "Emblema neogótico chilote en madera y revestimiento exterior de fierro galvanizado pintado en vibrante amarillo y morado. Patrimonio de la Humanidad UNESCO con torres de 42 metros de altura.",
        "fuente_url": "https://whc.unesco.org/en/list/971",
        "materiales_principales": ["Madera nativa (alerce, coigüe, ciprés)", "Hierro galvanizado"]
    },
    {
        "id": "iglesia-tenaun-chiloe",
        "nombre_proyecto": "Iglesia de Tenaún",
        "arquitecto": "Anónimo / Comunidad local",
        "arquitecto_principal": "Comunidad local de Tenaún",
        "colaboradores": "Maestros carpinteros de ribera de Dalcahue",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Costanera de Tenaún",
        "ciudad": "Tenaún, Chiloé",
        "pais": "Chile",
        "coordenadas": {"lat": -42.3328, "lng": -73.3644},
        "ano_diseno": "1840",
        "anos_construccion": "1840-1845",
        "ano_inauguracion": "1845",
        "estilos": ["Historicismo", "Arquitectura Neoclásica"],
        "programa": ["Religioso"],
        "descripcion": "Singular templo chilote distinguido por sus tres torres y frontispicio pintado en azul y blanco con estrellas. Patrimonio de la Humanidad UNESCO levantado sobre pilotes de madera frente al canal de Dalcahue.",
        "fuente_url": "https://whc.unesco.org/en/list/971",
        "materiales_principales": ["Madera nativa", "Tejuela de alerce"]
    },
    {
        "id": "iglesia-vilupulli-chonchi",
        "nombre_proyecto": "Iglesia de Vilupulli",
        "arquitecto": "Anónimo",
        "arquitecto_principal": "Anónimo",
        "colaboradores": "Maestros carpinteros chilotes",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Vilupulli, Comuna de Chonchi",
        "ciudad": "Chonchi, Chiloé",
        "pais": "Chile",
        "coordenadas": {"lat": -42.5975, "lng": -73.7850},
        "ano_diseno": "1890",
        "anos_construccion": "1890-1899",
        "ano_inauguracion": "1899",
        "estilos": ["Historicismo"],
        "programa": ["Religioso"],
        "descripcion": "Notable iglesia de Chiloé declarada Patrimonio de la Humanidad UNESCO, caracterizada por su esbelto pórtico de arcos de medio punto y torre campanario de dos cuerpos forrada en tejuela de alerce.",
        "fuente_url": "https://whc.unesco.org/en/list/971",
        "materiales_principales": ["Madera de alerce", "Ciprés", "Coigüe"]
    },
    {
        "id": "casa-central-universidad-de-chile",
        "nombre_proyecto": "Casa Central de la Universidad de Chile",
        "arquitecto": "Lucien Hénault y Fermín Vivaceta",
        "arquitecto_principal": "Lucien Hénault",
        "colaboradores": "Fermín Vivaceta (arquitecto constructor e inspector)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Libertador Bernardo O'Higgins 1058",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4444, "lng": -70.6517},
        "ano_diseno": "1863",
        "anos_construccion": "1863-1872",
        "ano_inauguracion": "1872",
        "estilos": ["Arquitectura Neoclásica"],
        "programa": ["Educacional", "Institucional / Gubernamental"],
        "descripcion": "Sede fundacional de la principal casa de estudios del país. Monumental edificio neoclásico republicano con dos amplios patios claustrales interiores, Salón de Honor y fachada dórica serena hacia la Alameda.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/casa-central-universidad-chile",
        "materiales_principales": ["Albañilería de ladrillo", "Estuco", "Madera de roble", "Hierro"]
    },
    {
        "id": "palacio-pereira-santiago",
        "nombre_proyecto": "Palacio Pereira",
        "arquitecto": "Lucien Hénault",
        "arquitecto_principal": "Lucien Hénault",
        "colaboradores": "Manuel Aldunate; Restauración siglo XXI por Cecilia Puga, Paula Velasco y Alberto Moletto",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Huérfanos 1515",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4402, "lng": -70.6565},
        "ano_diseno": "1872",
        "anos_construccion": "1872-1874",
        "ano_inauguracion": "1874",
        "estilos": ["Arquitectura Neoclásica"],
        "programa": ["Institucional / Gubernamental", "Cultural"],
        "descripcion": "Emblemática mansión neoclásica del siglo XIX con galería cruciforme central y lucernario. Tras décadas de abandono, fue sometida a una restauración contemporánea referencial que consolidó su albañilería histórica.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-pereira",
        "materiales_principales": ["Albañilería de ladrillo", "Estucos de yeso", "Hormigón armado contemporáneo", "Acero"]
    },
    {
        "id": "teatro-municipal-de-santiago",
        "nombre_proyecto": "Teatro Municipal de Santiago",
        "arquitecto": "François Brunet de Baines y Lucien Hénault",
        "arquitecto_principal": "François Brunet de Baines",
        "colaboradores": "Lucien Hénault, Charles Sainte-Marie Céppi",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Agustinas 794",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4419, "lng": -70.6475},
        "ano_diseno": "1853",
        "anos_construccion": "1853-1857",
        "ano_inauguracion": "1857",
        "estilos": ["Arquitectura Neoclásica"],
        "programa": ["Cultural"],
        "descripcion": "Primer coliseo de ópera y ballet de Chile, proyectado bajo cánones del neoclasicismo y academicismo francés con sala en herradura a la italiana, palcos dorados y foyer monumental.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/teatro-municipal-santiago",
        "materiales_principales": ["Ladrillo", "Piedra", "Yesería decorativa", "Cristal de Murano"]
    },
    {
        "id": "mercado-central-de-santiago",
        "nombre_proyecto": "Mercado Central de Santiago",
        "arquitecto": "Manuel Aldunate y Edward Woods",
        "arquitecto_principal": "Manuel Aldunate",
        "colaboradores": "Edward Woods (ingeniero estructura metálica Messers Laidlaw & Sons)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "San Pablo 967",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4336, "lng": -70.6508},
        "ano_diseno": "1869",
        "anos_construccion": "1869-1872",
        "ano_inauguracion": "1872",
        "estilos": ["Arquitectura del Hierro y Cristal", "Historicismo"],
        "programa": ["Comercial"],
        "descripcion": "Pionera estructura de fundición de hierro prefabricada en Glasgow, Escocia, montada sobre una base perimetral de albañilería neoclásica. Monumento Nacional y epicentro gastronómico del casco histórico.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/mercado-central-santiago",
        "materiales_principales": ["Hierro fundido", "Albañilería de ladrillo", "Vidrio"]
    },
    {
        "id": "catedral-de-san-marcos-arica",
        "nombre_proyecto": "Catedral de San Marcos",
        "arquitecto": "Talleres de Gustave Eiffel",
        "arquitecto_principal": "Gustave Eiffel",
        "colaboradores": "Talleres Eiffel en Levallois-Perret (París)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza Colón",
        "ciudad": "Arica",
        "pais": "Chile",
        "coordenadas": {"lat": -18.4794, "lng": -70.3208},
        "ano_diseno": "1871",
        "anos_construccion": "1871-1876",
        "ano_inauguracion": "1876",
        "estilos": ["Arquitectura del Hierro y Cristal", "Historicismo"],
        "programa": ["Religioso"],
        "descripcion": "Templo gótico prefabricado íntegramente en hierro fundido y forjado en los talleres de Gustave Eiffel en Francia, enviado en módulos armables por barco a Arica. Estructura sismorresistente excepcional.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/iglesia-san-marcos-arica",
        "materiales_principales": ["Hierro fundido", "Chapas de acero laminado"]
    },
    {
        "id": "ex-aduana-de-arica",
        "nombre_proyecto": "Ex-Aduana de Arica",
        "arquitecto": "Talleres de Gustave Eiffel",
        "arquitecto_principal": "Gustave Eiffel",
        "colaboradores": "Talleres Eiffel (París)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Máximo Lira con 21 de Mayo",
        "ciudad": "Arica",
        "pais": "Chile",
        "coordenadas": {"lat": -18.4789, "lng": -70.3222},
        "ano_diseno": "1871",
        "anos_construccion": "1871-1874",
        "ano_inauguracion": "1874",
        "estilos": ["Arquitectura del Hierro y Cristal"],
        "programa": ["Institucional / Gubernamental", "Cultural"],
        "descripcion": "Edificio público modular de esqueleto metálico con muros de piedra canteada provenientes de canteras peruanas. Construido por la firma de Gustave Eiffel como aduana portuaria.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/edificio-ex-aduana-arica",
        "materiales_principales": ["Hierro fundido", "Piedra canteada", "Madera"]
    },
    {
        "id": "palacio-el-huique",
        "nombre_proyecto": "Palacio El Huique",
        "arquitecto": "Anónimo",
        "arquitecto_principal": "Anónimo",
        "colaboradores": "Constructores rurales y artesanos de Colchagua",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Hacienda El Huique, Comuna de Palmilla",
        "ciudad": "Palmilla, Región de O'Higgins",
        "pais": "Chile",
        "coordenadas": {"lat": -34.5028, "lng": -71.3653},
        "ano_diseno": "1825",
        "anos_construccion": "1828-1850",
        "ano_inauguracion": "1850",
        "estilos": ["Arquitectura Colonial", "Arquitectura Neoclásica"],
        "programa": ["Vivienda", "Cultural"],
        "descripcion": "La hacienda patronal más representativa de la vida rural decimonónica en Chile, con 22 patios interiores, extensas galerías de corredores con pilares de madera labrada e iglesia con esbelto campanario.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/hacienda-huique",
        "materiales_principales": ["Adobe", "Madera nativa", "Teja colonial"]
    },
    {
        "id": "iglesia-san-jose-pelchuquin",
        "nombre_proyecto": "Iglesia San José de Pelchuquín",
        "arquitecto": "Misioneros Capuchinos",
        "arquitecto_principal": "Misioneros Capuchinos",
        "colaboradores": "Comunidad mapuche-huilliche y colonos de Pelchuquín",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Pelchuquín, Comuna de San José de la Mariquina",
        "ciudad": "Pelchuquín, Región de Los Ríos",
        "pais": "Chile",
        "coordenadas": {"lat": -39.6389, "lng": -73.0806},
        "ano_diseno": "1864",
        "anos_construccion": "1864-1868",
        "ano_inauguracion": "1868",
        "estilos": ["Historicismo"],
        "programa": ["Religioso"],
        "descripcion": "Valioso ejemplo de la arquitectura misional de madera en el sur de Chile impulsada por la orden capuchina bávara, integrando técnicas de carpintería vernácula europea con maderas nativas valdivianas.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Madera de roble pellín", "Laurel", "Tejuelas"]
    },
    {
        "id": "palacio-alhambra-santiago",
        "nombre_proyecto": "Palacio Alhambra",
        "arquitecto": "Manuel Aldunate",
        "arquitecto_principal": "Manuel Aldunate",
        "colaboradores": "Francisco Solano Astaburuaga (mandante)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Compañía de Jesús 1340",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4394, "lng": -70.6558},
        "ano_diseno": "1860",
        "anos_construccion": "1860-1862",
        "ano_inauguracion": "1862",
        "estilos": ["Historicismo"],
        "programa": ["Cultural", "Vivienda"],
        "descripcion": "Inmueble neomudéjar único en Chile inspirado fielmente en la Alhambra de Granada tras los viajes del arquitecto Manuel Aldunate a España. Posee patios de arquería con mocárabes, estucos policromados y fuente central.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-alhambra",
        "materiales_principales": ["Albañilería de ladrillo", "Yesería mudéjar decorativa", "Azulejos vidriados"]
    },
    {
        "id": "palacio-cousino-santiago",
        "nombre_proyecto": "Palacio Cousiño",
        "arquitecto": "Paul Lathoud",
        "arquitecto_principal": "Paul Lathoud",
        "colaboradores": "Empresas y decoradores franceses del Segundo Imperio",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Calle Dieciocho 438",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4533, "lng": -70.6558},
        "ano_diseno": "1870",
        "anos_construccion": "1870-1878",
        "ano_inauguracion": "1878",
        "estilos": ["Historicismo", "Arquitectura Neoclásica"],
        "programa": ["Vivienda", "Cultural"],
        "descripcion": "La cumbre de la opulencia residencial decimonónica ligada a la industria del carbón y la minería. Proyectado por el francés Paul Lathoud con tecnología pionera (calefacción central, generador) y salones dorados.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-cousino-parque",
        "materiales_principales": ["Mármol de Carrara", "Albañilería", "Maderas nobles europeas", "Vidrio biselado"]
    },
    {
        "id": "viaducto-del-malleco",
        "nombre_proyecto": "Viaducto del Malleco",
        "arquitecto": "Victorino Aurelio Lastarria",
        "arquitecto_principal": "Victorino Aurelio Lastarria",
        "colaboradores": "Schneider et Cie (Le Creusot, Francia)",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Paso sobre el río Malleco, Collipulli",
        "ciudad": "Collipulli, Región de La Araucanía",
        "pais": "Chile",
        "coordenadas": {"lat": -37.9583, "lng": -72.4389},
        "ano_diseno": "1885",
        "anos_construccion": "1886-1890",
        "ano_inauguracion": "1890",
        "estilos": ["Arquitectura del Hierro y Cristal", "Funcionalismo"],
        "programa": ["Infraestructura"],
        "descripcion": "Hazaña mundial de la ingeniería y arquitectura del hierro del siglo XIX. Con 102 metros de altura sobre el lecho del río y 347 metros de longitud, conectó ferroviariamente a Chile con la Araucanía.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/viaducto-malleco",
        "materiales_principales": ["Acero dulce", "Hierro forjado laminado"]
    },
    {
        "id": "palacio-sara-braun-punta-arenas",
        "nombre_proyecto": "Palacio Sara Braun",
        "arquitecto": "Numa Mayer",
        "arquitecto_principal": "Numa Mayer",
        "colaboradores": "Constructores y ebanistas europeos en Magallanes",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza Muñoz Gamero 716",
        "ciudad": "Punta Arenas",
        "pais": "Chile",
        "coordenadas": {"lat": -53.1625, "lng": -70.9081},
        "ano_diseno": "1894",
        "anos_construccion": "1895-1905",
        "ano_inauguracion": "1905",
        "estilos": ["Historicismo", "Arquitectura Neoclásica"],
        "programa": ["Vivienda", "Hospedaje", "Cultural"],
        "descripcion": "Suntuoso palacete ecléctico francés ubicado en el extremo austral de América, símbolo de la época de oro ganadera y mercantil de Magallanes. Cuenta con jardín de invierno acristalado y mobiliario original.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/palacio-sara-braun",
        "materiales_principales": ["Piedra", "Albañilería de ladrillo", "Fierro dulce", "Vidrio"]
    },
    {
        "id": "muelle-prat-valparaiso",
        "nombre_proyecto": "Muelle Prat",
        "arquitecto": "Eduardo Woods",
        "arquitecto_principal": "Eduardo Woods",
        "colaboradores": "Ingenieros de la Dirección de Obras del Puerto",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Plaza Sotomayor costanera",
        "ciudad": "Valparaíso",
        "pais": "Chile",
        "coordenadas": {"lat": -33.0381, "lng": -71.6289},
        "ano_diseno": "1882",
        "anos_construccion": "1882-1885",
        "ano_inauguracion": "1885",
        "estilos": ["Arquitectura del Hierro y Cristal", "Funcionalismo"],
        "programa": ["Infraestructura"],
        "descripcion": "Muelle de pasajeros y atraque histórico de Valparaíso que definió la interface entre la Plaza Sotomayor y el Océano Pacífico durante el esplendor comercial del puerto en el siglo XIX.",
        "fuente_url": "https://www.monumentos.gob.cl",
        "materiales_principales": ["Pilotes de acero", "Estructura metálica", "Madera tratada"]
    },
    {
        "id": "ex-fabrica-cerveza-ebner",
        "nombre_proyecto": "Ex Fábrica de Cerveza Ebner",
        "arquitecto": "Anónimo",
        "arquitecto_principal": "Anónimo",
        "colaboradores": "Ingenieros cerveceros alemanes",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Av. Independencia 565",
        "ciudad": "Santiago",
        "pais": "Chile",
        "coordenadas": {"lat": -33.4219, "lng": -70.6547},
        "ano_diseno": "1885",
        "anos_construccion": "1885-1888",
        "ano_inauguracion": "1888",
        "estilos": ["Historicismo", "Arquitectura del Hierro y Cristal"],
        "programa": ["Comercial", "Cultural"],
        "descripcion": "Conjunto fabril e industrial renacentista/ecléctico del siglo XIX fundado por Andrés Ebner. Presenta palacete administrativo con torre mirador y naves de calderas representativas de la primera industria nacional.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/inmueble-denominado-fabrica-cerveza-andres-ebner",
        "materiales_principales": ["Albañilería de ladrillo visto", "Hierro fundido", "Madera"]
    },
    {
        "id": "fuerte-niebla-valdivia",
        "nombre_proyecto": "Fuerte Niebla y Sistema Defensivo de Valdivia",
        "arquitecto": "Ingenieros Militares Españoles",
        "arquitecto_principal": "Ingenieros Militares Españoles",
        "colaboradores": "Pedro de Valdivia, Juan Brizuela, Antonio Duce Oliveros",
        "ano_pritzker": None,
        "fotografia_url": "",
        "fotografia_credito": "",
        "direccion": "Punta de Niebla, desembocadura del Río Valdivia",
        "ciudad": "Valdivia",
        "pais": "Chile",
        "coordenadas": {"lat": -39.8667, "lng": -73.3986},
        "ano_diseno": "1645",
        "anos_construccion": "1645-1790",
        "ano_inauguracion": "1671",
        "estilos": ["Arquitectura Renacentista", "Arquitectura Barroca"],
        "programa": ["Institucional / Gubernamental", "Cultural"],
        "descripcion": "Magna fortificación abaluartada del siglo XVII y XVIII conocida como la Llave del Mar del Sur. Construida con piedra cancagua tallada y cañones de bronce para proteger el estuario valdiviano de incursiones corsarias.",
        "fuente_url": "https://www.monumentos.gob.cl/monumentos/monumentos-historicos/castillo-niebla-sistema-fuertes-valdivia",
        "materiales_principales": ["Piedra cancagua", "Ladrillo colonial", "Cal y arena", "Bronce"]
    }
]

print(f"Period 1 defined: {len(period_1)} projects.")
