#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Data generator for Región de Antofagasta - Part 2 (Sections 4, 5, 6, 7 = 58 works)"""
import json

obras_antofagasta_p2 = [
  # 4. Arquitectura Moderna, Planificación Urbana y Vivienda Social (16)
  {
    "id": "edificio-huanchaca-antofagasta-moderno",
    "nombre_proyecto": "Edificio Huanchaca (El Barco)",
    "arquitecto": "Ricardo Pulgar San Martín",
    "arquitecto_principal": "Ricardo Pulgar San Martín",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Brasil con Antonino Toro, Antofagasta",
    "coordenadas": {"lat": -23.6550, "lng": -70.4010},
    "ano_diseno": "1940",
    "anos_construccion": "1941-1943",
    "ano_inauguracion": "1943",
    "estilos": ["Estilo Barco (Streamline Moderne)", "Movimiento Moderno"],
    "programa": ["Residencial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Ícono del racionalismo náutico chileno. Su volumen curvo aerodinámico con ventanas circulares tipo 'ojo de buey', balcones corridos y barandas de tubo de acero simula la proa de un transatlántico varado frente a la costa de Antofagasta.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón armado", "Acero naval", "Vidrio curvo"]
  },
  {
    "id": "poblacion-gran-via-antofagasta",
    "nombre_proyecto": "Población Gran Vía (Conjunto Habitacional)",
    "arquitecto": "Corporación de la Vivienda (CORVI) / Bresciani, Valdés, Castillo, Huidobro (BVCH)",
    "arquitecto_principal": "BVCH / CORVI",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Angamos con Av. Ejército, Antofagasta",
    "coordenadas": {"lat": -23.6680, "lng": -70.4040},
    "ano_diseno": "1964",
    "anos_construccion": "1965-1970",
    "ano_inauguracion": "1970",
    "estilos": ["Brutalismo Moderno", "Vivienda Social CORVI", "Hormigón Visto"],
    "programa": ["Vivienda"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Magistral conjunto urbano moderno compuesto por torres habitacionales y bloques lineales con pasarelas aéreas, puentes peatonales y centros cívicos integrados, dominando las terrazas marinas del sur de Antofagasta.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón armado visto", "Bloques de cemento", "Acero"]
  },
  {
    "id": "edificio-curvo-antofagasta",
    "nombre_proyecto": "Edificio Curvo de la Gran Vía",
    "arquitecto": "Ricardo Pulgar / Equipo Técnico CORVI",
    "arquitecto_principal": "Ricardo Pulgar",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Angamos frente a la Universidad del Norte, Antofagasta",
    "coordenadas": {"lat": -23.6700, "lng": -70.4045},
    "ano_diseno": "1966",
    "anos_construccion": "1967-1969",
    "ano_inauguracion": "1969",
    "estilos": ["Movimiento Moderno Escultórico", "Brutalismo"],
    "programa": ["Residencial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Edificio serpenteante de varios cientos de metros de desarrollo que acompaña la topografía de la falla costera, con terrazas corridas y celosías de protección solar.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón armado", "Bloque prefabricado", "Hierro"]
  },
  {
    "id": "edificio-intendencia-antofagasta",
    "nombre_proyecto": "Edificio del Gobierno Regional e Intendencia de Antofagasta",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Arturo Prat 384, Antofagasta",
    "coordenadas": {"lat": -23.6470, "lng": -70.3968},
    "ano_diseno": "1972",
    "anos_construccion": "1973-1976",
    "ano_inauguracion": "1976",
    "estilos": ["Brutalismo Cívico", "Movimiento Moderno Institucional"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Sede del poder regional con imponente estructura de hormigón armado a la vista, parasoles profundos (brise-soleil) y plaza cívica abierta a la calle peatonal Prat.",
    "fuente_url": "https://www.goreantofagasta.cl",
    "materiales_principales": ["Hormigón visto martillina", "Acero", "Vidrio tinteado"]
  },
  {
    "id": "campus-coloso-universidad-antofagasta",
    "nombre_proyecto": "Campus Coloso de la Universidad de Antofagasta",
    "arquitecto": "Dirección de Obras Universitarias / MOP",
    "arquitecto_principal": "Arquitectos Universitarios",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Universidad de Antofagasta 02800, Antofagasta",
    "coordenadas": {"lat": -23.7050, "lng": -70.4180},
    "ano_diseno": "1975",
    "anos_construccion": "1976-1981",
    "ano_inauguracion": "1981",
    "estilos": ["Brutalismo Universitario en el Borde Costero"],
    "programa": ["Educación"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Ciudad universitaria emplazada en los farellones costeros de Coloso. Destaca por sus pabellones masivos de hormigón armado, patios hundidos protegidos del viento y vistas panorámicas hacia el Pacífico.",
    "fuente_url": "https://www.uantof.cl",
    "materiales_principales": ["Hormigón armado visto", "Vidrio", "Piedra local"]
  },
  {
    "id": "casa-central-ucn-antofagasta",
    "nombre_proyecto": "Casa Central de la Universidad Católica del Norte (UCN)",
    "arquitecto": "Fundación Jesuitas / Arquitectos UCN",
    "arquitecto_principal": "R.P. Gustavo Le Paige / Arquitectos Modernos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Angamos 0610, Antofagasta",
    "coordenadas": {"lat": -23.6790, "lng": -70.4060},
    "ano_diseno": "1956",
    "anos_construccion": "1957-1960",
    "ano_inauguracion": "1960",
    "estilos": ["Racionalismo Moderno Universitario"],
    "programa": ["Educación"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Conjunto fundacional de la Universidad del Norte con pabellones de líneas horizontales puras, celosías cerámicas y patios interiores sombreados por buganvilias.",
    "fuente_url": "https://www.ucn.cl",
    "materiales_principales": ["Hormigón armado", "Albañilería a la vista", "Madera"]
  },
  {
    "id": "poblacion-favorecedora-antofagasta",
    "nombre_proyecto": "Población Favorecedora",
    "arquitecto": "CORVI",
    "arquitecto_principal": "Equipo Técnico CORVI Antofagasta",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Centro-Sur, faldeos del Cerro El Ancla, Antofagasta",
    "coordenadas": {"lat": -23.6600, "lng": -70.3950},
    "ano_diseno": "1955",
    "anos_construccion": "1956-1958",
    "ano_inauguracion": "1958",
    "estilos": ["Racionalismo de Faldeo", "Vivienda Social"],
    "programa": ["Vivienda"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Barrio obrero y de clase media adaptado a la pronunciada pendiente del farellón costero mediante escalinatas de hormigón, muros de contención de piedra y pasajes peatonales.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón armado", "Albañilería confinada", "Piedra de cerro"]
  },
  {
    "id": "estadio-regional-calvo-y-bascunan",
    "nombre_proyecto": "Estadio Regional Calvo y Bascuñán (Original)",
    "arquitecto": "Mario Recordón / Alberto Sartori",
    "arquitecto_principal": "Mario Recordón",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Angamos con Homero Ávila, Antofagasta",
    "coordenadas": {"lat": -23.6635, "lng": -70.4025},
    "ano_diseno": "1960",
    "anos_construccion": "1961-1964",
    "ano_inauguracion": "1964",
    "estilos": ["Movimiento Moderno Deportivo"],
    "programa": ["Deportivo"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Diseñado para la subsede de la Copa Mundial de Fútbol de 1962 (inaugurado en 1964) con una elipse perfecta de hormigón armado excavada en la meseta costera.",
    "fuente_url": "https://www.municipalidadantofagasta.cl",
    "materiales_principales": ["Hormigón armado", "Tierra compactada", "Acero"]
  },
  {
    "id": "edificio-capredena-antofagasta",
    "nombre_proyecto": "Edificio CAPREDENA Antofagasta",
    "arquitecto": "Oficina Técnica CAPREDENA",
    "arquitecto_principal": "Arquitectos Modernos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Washington con Sucre, Antofagasta",
    "coordenadas": {"lat": -23.6475, "lng": -70.3975},
    "ano_diseno": "1968",
    "anos_construccion": "1969-1971",
    "ano_inauguracion": "1971",
    "estilos": ["Racionalismo Tardío"],
    "programa": ["Institucional / Residencial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Torre moderna de diez plantas con modulación rigurosa de ventanas y pórtico de acceso de doble altura en pleno centro bancario de la ciudad.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio", "Aluminio"]
  },
  {
    "id": "colegio-san-luis-antofagasta",
    "nombre_proyecto": "Colegio San Luis de Antofagasta",
    "arquitecto": "Compañía de Jesús / Arquitectos Jesuitas",
    "arquitecto_principal": "Jesuitas Arquitectos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Baquedano 555, Antofagasta",
    "coordenadas": {"lat": -23.6490, "lng": -70.3930},
    "ano_diseno": "1935",
    "anos_construccion": "1936-1937",
    "ano_inauguracion": "1937",
    "estilos": ["Racionalismo Escolar Clásico"],
    "programa": ["Educación"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Tradicional colegio jesuita con sobria fachada simétrica de hormigón estucado, claustros de arcadas y capilla de estilo neorrománico despojado.",
    "fuente_url": "https://www.sanluis.cl",
    "materiales_principales": ["Hormigón armado", "Albañilería", "Madera nativa"]
  },
  {
    "id": "poblacion-chuquicamata-calama",
    "nombre_proyecto": "Campamento Minero de Chuquicamata (Zona Típica)",
    "arquitecto": "Chile Exploration Company (Guggenheim / Anaconda Copper)",
    "arquitecto_principal": "Ingenieros Urbanistas de Anaconda Copper",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Campamento Chuquicamata, 15 km al norte de Calama",
    "coordenadas": {"lat": -22.3160, "lng": -68.9030},
    "ano_diseno": "1915",
    "anos_construccion": "1915-1970",
    "ano_inauguracion": "1917",
    "estilos": ["Company Town Norteamericana", "Zona Típica"],
    "programa": ["Urbanismo / Ciudad Minera"],
    "ciudad": "Calama",
    "pais": "Chile",
    "descripcion": "Zona Típica. La ciudad-campamento minera más impresionante de los Andes, con plaza central, teatro Chile, hospital Roy H. Glover de estándar mundial, club de empleados y barrios clasificados según jerarquía laboral de la empresa.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Hormigón armado", "Adobe prensado", "Pino oregón", "Cobre"]
  },
  {
    "id": "club-de-la-union-antofagasta",
    "nombre_proyecto": "Edificio Club de la Unión de Antofagasta",
    "arquitecto": "Alberto Cruz Montt / Dávila Carson",
    "arquitecto_principal": "Alberto Cruz Montt",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Prat con San Martín, Plaza Colón, Antofagasta",
    "coordenadas": {"lat": -23.6468, "lng": -70.3972},
    "ano_diseno": "1923",
    "anos_construccion": "1924-1925",
    "ano_inauguracion": "1925",
    "estilos": ["Neoclásico Republicano"],
    "programa": ["Social / Club"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Sede social de la élite minera y salitrera de Antofagasta, con salones de billar, bar inglés de nogal y gran comedor con balcones hacia la Plaza Colón.",
    "fuente_url": "https://www.clubdelaunionantofagasta.cl",
    "materiales_principales": ["Hormigón armado", "Yeso decorativo", "Maderas finas"]
  },
  {
    "id": "edificio-banco-del-estado-antofagasta",
    "nombre_proyecto": "Edificio Banco del Estado de Antofagasta",
    "arquitecto": "Dirección de Arquitectura Banco del Estado",
    "arquitecto_principal": "Arquitectos Bancarios Estatales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle San Martín 2501, Antofagasta",
    "coordenadas": {"lat": -23.6472, "lng": -70.3978},
    "ano_diseno": "1965",
    "anos_construccion": "1966-1967",
    "ano_inauguracion": "1967",
    "estilos": ["Racionalismo Financiero"],
    "programa": ["Financiero / Bancario"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Edificio institucional con marquesina volada de hormigón en la esquina y muro cortina de acero y cristal que refleja la torre del reloj de la plaza.",
    "fuente_url": "https://www.bancoestado.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio", "Granito pulido"]
  },
  {
    "id": "poblacion-estadio-tocopilla",
    "nombre_proyecto": "Población Estadio de Tocopilla",
    "arquitecto": "CORVI",
    "arquitecto_principal": "CORVI Regional",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Sur de Tocopilla",
    "coordenadas": {"lat": -22.1020, "lng": -70.1940},
    "ano_diseno": "1962",
    "anos_construccion": "1963",
    "ano_inauguracion": "1963",
    "estilos": ["Vivienda Social CORVI"],
    "programa": ["Vivienda"],
    "ciudad": "Tocopilla",
    "pais": "Chile",
    "descripcion": "Conjunto habitacional con bloques pareados de hormigón y ladrillo diseñados para soportar el embate de sismos y la alta salinidad del aire marino de Tocopilla.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón", "Ladrillo", "Zinc"]
  },
  {
    "id": "conjunto-habitacional-corvi-calama",
    "nombre_proyecto": "Conjunto Habitacional CORVI Calama",
    "arquitecto": "CORVI",
    "arquitecto_principal": "Equipo CORVI Norte",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Granaderos, Calama",
    "coordenadas": {"lat": -22.4550, "lng": -68.9220},
    "ano_diseno": "1969",
    "anos_construccion": "1970-1971",
    "ano_inauguracion": "1971",
    "estilos": ["Racionalismo en Clima Desértico Frío"],
    "programa": ["Vivienda"],
    "ciudad": "Calama",
    "pais": "Chile",
    "descripcion": "Viviendas con muros gruesos de ladrillo fiscal para retener el calor nocturno de la puna, con ventanas pequeñas orientadas al norte y patios cercados.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Ladrillo fiscal", "Hormigón", "Madera"]
  },
  {
    "id": "estacion-ferrocarril-baquedano",
    "nombre_proyecto": "Estación y Maestranza Ferroviaria de Baquedano",
    "arquitecto": "Ferrocarril de Antofagasta a Bolivia (FCAB) y Ferrocarril Longitudinal Norte",
    "arquitecto_principal": "Ingenieros Ferroviarios del Estado",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Pueblo de Baquedano, Comuna de Sierra Gorda",
    "coordenadas": {"lat": -23.3333, "lng": -69.8333},
    "ano_diseno": "1910",
    "anos_construccion": "1910-1914",
    "ano_inauguracion": "1914",
    "estilos": ["Arquitectura Ferroviaria del Desierto", "Monumento Nacional"],
    "programa": ["Transporte", "Monumento Histórico"],
    "ciudad": "Sierra Gorda",
    "pais": "Chile",
    "descripcion": "Monumento Histórico Nacional. Cruce neurálgico del desierto de Atacama donde convergían el FCAB y el ferrocarril longitudinal. Conserva su monumental casa de máquinas semicircular (rotonda) con tornamesa y locomotoras a vapor gigantes.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Acero estructural", "Rieles de acero", "Madera de pino oregón", "Hierro"]
  },

  # 5. Arquitectura Contemporánea, Hotelería y Paisaje Extremo (20)
  {
    "id": "hotel-explora-en-atacama-san-pedro",
    "nombre_proyecto": "Hotel Explora en Atacama (Hotel Larache)",
    "arquitecto": "Germán del Sol / José Cruz Ovalle",
    "arquitecto_principal": "Germán del Sol",
    "colaboradores": "José Cruz Ovalle",
    "ano_pritzker": None,
    "premio_nacional_arquitectura": 2006,
    "fotografia_url": "",
    "direccion": "Ayllu de Larache, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9200, "lng": -68.1960},
    "ano_diseno": "1997",
    "anos_construccion": "1997-1998",
    "ano_inauguracion": "1998",
    "estilos": ["Vernáculo Contemporáneo de Vanguardia", "Arquitectura de Oasis"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Premio Nacional de Arquitectura. Obra cumbre de la hotelería de paisaje mundial que inauguró una nueva forma de habitar el desierto. Diseñado con muros curvos blancos de estuco a la cal, pasarelas de madera elevadas sobre canales de regadío y piscinas termales abiertas a los volcanes.",
    "fuente_url": "https://www.explora.com",
    "materiales_principales": ["Muros de adobe estucados a la cal blanca", "Pino oregón y teca", "Pizarra", "Agua"]
  },
  {
    "id": "hotel-tierra-atacama-san-pedro",
    "nombre_proyecto": "Hotel Tierra Atacama",
    "arquitecto": "Rodrigo Searle + Matías González",
    "arquitecto_principal": "Rodrigo Searle",
    "colaboradores": "Matías González",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Sequitor s/n, Ayllu de Yaye, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9260, "lng": -68.2040},
    "ano_diseno": "2006",
    "anos_construccion": "2007-2008",
    "ano_inauguracion": "2008",
    "estilos": ["Sustentable de Lujo", "Arquitectura de Tierra y Barro"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Emplazado en un antiguo corral de ganado de adobe recuperado. Integra arquitectura bioclimática pasiva, paneles solares híbridos que abastecen el 100% de la energía y vistas directas hacia el cono perfecto del volcán Licancabur.",
    "fuente_url": "https://www.tierrahotels.com",
    "materiales_principales": ["Adobe recuperado", "Piedra volcánica", "Madera nativa", "Vidrio"]
  },
  {
    "id": "hotel-alto-atacama-san-pedro",
    "nombre_proyecto": "Hotel Nayara Alto Atacama",
    "arquitecto": "Taller de Arquitectura y Paisaje San Pedro",
    "arquitecto_principal": "Arquitectos de Paisaje",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Catarpe s/n, Cordillera de la Sal, San Pedro de Atacama",
    "coordenadas": {"lat": -22.8750, "lng": -68.2200},
    "ano_diseno": "2007",
    "anos_construccion": "2008",
    "ano_inauguracion": "2008",
    "estilos": ["Mimetismo con el Paisaje Geológico"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Construido en el fondo del cañón rojizo de Catarpe, el hotel se mimetiza completamente con las paredes de arcilla de la Cordillera de la Sal utilizando tierra del mismo lugar en los estucos de sus muros.",
    "fuente_url": "https://www.nayaraaltoatacama.com",
    "materiales_principales": ["Tierra arcillosa roja del cañón", "Piedra", "Paja", "Madera"]
  },
  {
    "id": "hotel-cumbres-san-pedro-de-atacama",
    "nombre_proyecto": "Hotel Cumbres San Pedro de Atacama",
    "arquitecto": "Estudio Arquitectura Hoteles del Norte",
    "arquitecto_principal": "Arquitectos Asociados",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Las Tolas s/n, Ayllu de Quitor, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9020, "lng": -68.2080},
    "ano_diseno": "2008",
    "anos_construccion": "2009",
    "ano_inauguracion": "2009",
    "estilos": ["Arquitectura Vernácula Hotelera"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Pueblito hotelero estructurado con patios de piedra toba volcánica, duchas exteriores privadas abiertas al cielo estrellado y muros de aislamiento térmico.",
    "fuente_url": "https://www.cumbres.cl",
    "materiales_principales": ["Piedra toba volcánica", "Madera rústica", "Techo de paja y barro"]
  },
  {
    "id": "museo-del-desierto-de-atacama-huanchaca",
    "nombre_proyecto": "Museo del Desierto de Atacama (Monumento Huanchaca)",
    "arquitecto": "Coeymans Arquitectos / Ramón Coeymans",
    "arquitecto_principal": "Ramón Coeymans",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Parque Cultural Huanchaca, Av. Angamos 01606, Antofagasta",
    "coordenadas": {"lat": -23.6870, "lng": -70.4070},
    "ano_diseno": "2008",
    "anos_construccion": "2009-2010",
    "ano_inauguracion": "2010",
    "estilos": ["Contemporáneo Semienterrado", "Arquitectura de Rampa"],
    "programa": ["Cultura", "Museo"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Edificio semienterrado adyacente a las monumentales ruinas de Huanchaca. Su cubierta es una rampa transitable con vistas al océano que contiene salas de astronomía, geología y paleontología.",
    "fuente_url": "https://www.fundacionhuanchaca.cl",
    "materiales_principales": ["Hormigón visto color ocre", "Acero corten", "Vidrio estructural"]
  },
  {
    "id": "remodelacion-estadio-regional-calvo-y-bascunan",
    "nombre_proyecto": "Estadio Regional Calvo y Bascuñán (Remodelación Bicentenario)",
    "arquitecto": "Valle & Cornejo Arquitectos / Dirección de Arquitectura MOP",
    "arquitecto_principal": "Valle & Cornejo",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Angamos con Homero Ávila, Antofagasta",
    "coordenadas": {"lat": -23.6635, "lng": -70.4025},
    "ano_diseno": "2011",
    "anos_construccion": "2012-2013",
    "ano_inauguracion": "2013",
    "estilos": ["Arquitectura Deportiva Contemporánea", "Fachada Textil Paramétrica"],
    "programa": ["Deportivo"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Remodelación integral para la Copa América 2015 con capacidad para 21.000 espectadores, recubierto por una piel exterior cobriza perforada con lamas que filtran la brisa marina y la radiación solar.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Estructura de acero", "Lamas metálicas perforadas color cobre", "Hormigón"]
  },
  {
    "id": "nuevo-aeropuerto-andres-sabella-antofagasta",
    "nombre_proyecto": "Terminal Internacional Aeropuerto Andrés Sabella",
    "arquitecto": "Dirección de Aeropuertos MOP / Amunátegui Barreau Arquitectos",
    "arquitecto_principal": "MOP Aeropuertos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Cerro Moreno, 25 km al norte de Antofagasta",
    "coordenadas": {"lat": -23.4444, "lng": -70.4450},
    "ano_diseno": "2012",
    "anos_construccion": "2013-2014",
    "ano_inauguracion": "2014",
    "estilos": ["Contemporáneo de Infraestructura de Transporte"],
    "programa": ["Transporte"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Segundo aeropuerto de mayor tráfico aéreo de Chile, diseñado con amplias cubiertas onduladas que evocan el oleaje del Pacífico y terminal de pasajeros vidriada de bajo consumo energético.",
    "fuente_url": "https://www.aeropuertoantofagasta.cl",
    "materiales_principales": ["Acero estructural", "Muro cortina térmico", "Cubiertas de aluminio continuo"]
  },
  {
    "id": "parque-croacia-y-borde-costero-sur-antofagasta",
    "nombre_proyecto": "Parque Croacia y Borde Costero Sur de Antofagasta",
    "arquitecto": "Municipalidad de Antofagasta / Obras Portuarias MOP",
    "arquitecto_principal": "MOP Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Ejército con Av. Angamos, Antofagasta",
    "coordenadas": {"lat": -23.6660, "lng": -70.4060},
    "ano_diseno": "2005",
    "anos_construccion": "2006-2007",
    "ano_inauguracion": "2007",
    "estilos": ["Paisajismo Costero Contemporáneo"],
    "programa": ["Espacio Público / Borde Costero"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Gran parque litoral con anfiteatro al aire libre, ciclovías continuas y áreas verdes resistentes a la salinidad marina frente a la playa El Balneario.",
    "fuente_url": "https://www.municipalidadantofagasta.cl",
    "materiales_principales": ["Hormigón estampado", "Césped marino", "Acero inoxidable", "Piedra"]
  },
  {
    "id": "hospital-regional-de-antofagasta-leonardo-guzman",
    "nombre_proyecto": "Nuevo Hospital Regional de Antofagasta Dr. Leonardo Guzmán",
    "arquitecto": "Dirección de Arquitectura MOP / Concesiones Salud",
    "arquitecto_principal": "Arquitectos Hospitalarios Internacionales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Azapa con Víctor Jara, Antofagasta",
    "coordenadas": {"lat": -23.6280, "lng": -70.3880},
    "ano_diseno": "2013",
    "anos_construccion": "2014-2017",
    "ano_inauguracion": "2017",
    "estilos": ["Contemporáneo Hospitalario de Alta Complejidad"],
    "programa": ["Salud"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "El hospital público más grande y moderno del norte de Chile (123.000 m²). Cuenta con 280 aisladores sísmicos, centro oncológico de referencia macrozonal y fachada ventilada bioclimática.",
    "fuente_url": "https://www.hospitalantofagasta.gob.cl",
    "materiales_principales": ["Aisladores elastoméricos sísmicos", "Hormigón armado", "Paneles fenólicos ventilados"]
  },
  {
    "id": "playa-artificial-el-trocadero-antofagasta",
    "nombre_proyecto": "Playa Artificial y Paseo Costero El Trocadero",
    "arquitecto": "Dirección de Obras Portuarias MOP",
    "arquitecto_principal": "MOP Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Borde Costero Norte, Antofagasta",
    "coordenadas": {"lat": -23.5900, "lng": -70.3950},
    "ano_diseno": "2003",
    "anos_construccion": "2004-2005",
    "ano_inauguracion": "2005",
    "estilos": ["Ingeniería y Paisajismo Marítimo"],
    "programa": ["Espacio Público / Playa Artificial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Transformación del roquerío costero norte en una playa artificial abrigada por dos espigones de enrocado de 300 metros, con paseos peatonales, canchas de vóleibol y miradores.",
    "fuente_url": "https://www.dop.cl",
    "materiales_principales": ["Enrocado marítimo basáltico", "Arena rubia", "Hormigón marino"]
  },
  {
    "id": "mall-plaza-antofagasta-borde-costero",
    "nombre_proyecto": "Mallplaza Antofagasta",
    "arquitecto": "BMA Arquitectos / Mallplaza",
    "arquitecto_principal": "BMA Arquitectos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Balmaceda 2355, Antofagasta",
    "coordenadas": {"lat": -23.6490, "lng": -70.4015},
    "ano_diseno": "2004",
    "anos_construccion": "2005-2006",
    "ano_inauguracion": "2006",
    "estilos": ["Comercial Urbano Abierto al Mar"],
    "programa": ["Comercial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Centro comercial que abrió la ciudad hacia su puerto, incorporando terrazas gastronómicas escalonadas con vistas a la bahía y recuperación de galpones ferroviarios históricos.",
    "fuente_url": "https://www.mallplaza.com",
    "materiales_principales": ["Acero", "Hormigón visto", "Vidrio laminado"]
  },
  {
    "id": "museo-arqueologico-rvdo-gustavo-le-paige",
    "nombre_proyecto": "Nuevo Edificio Museo Arqueológico Gustavo Le Paige",
    "arquitecto": "Dirección de Arquitectura MOP / UCN",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Plaza de San Pedro de Atacama",
    "coordenadas": {"lat": -22.9118, "lng": -68.2005},
    "ano_diseno": "2014",
    "anos_construccion": "2015-2021",
    "ano_inauguracion": "2021",
    "estilos": ["Contemporáneo Andino de Conservación"],
    "programa": ["Cultura", "Museo"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Edificio diseñado para custodiar la colección arqueológica de más de 380.000 piezas atacameñas con cámaras climáticas subterráneas de temperatura y humedad constante.",
    "fuente_url": "https://www.ciidater.ucn.cl",
    "materiales_principales": ["Muros de barro y tierra comprimida", "Hormigón pigmentado", "Madera nativa"]
  },
  {
    "id": "polideportivo-centenario-antofagasta",
    "nombre_proyecto": "Polideportivo Centenario de Antofagasta",
    "arquitecto": "Instituto Nacional de Deportes (IND) / MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Bandera con Huamachuco, Antofagasta",
    "coordenadas": {"lat": -23.6050, "lng": -70.3850},
    "ano_diseno": "2013",
    "anos_construccion": "2014-2015",
    "ano_inauguracion": "2015",
    "estilos": ["Contemporáneo Deportivo"],
    "programa": ["Deportivo"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Polideportivo techado para el sector norte de Antofagasta con cancha central de piso de poliuretano, graderías retráctiles y cerchas espaciales de acero.",
    "fuente_url": "https://www.ind.cl",
    "materiales_principales": ["Acero estructural", "Paneles aislados de cubierta", "Policarbonato alveolar"]
  },
  {
    "id": "edificio-consistorial-calama",
    "nombre_proyecto": "Edificio Consistorial de Calama",
    "arquitecto": "Dirección de Arquitectura MOP / Municipalidad de Calama",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Granaderos 1601, Calama",
    "coordenadas": {"lat": -22.4600, "lng": -68.9250},
    "ano_diseno": "2008",
    "anos_construccion": "2009-2010",
    "ano_inauguracion": "2010",
    "estilos": ["Contemporáneo Cívico del Oasis"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Calama",
    "pais": "Chile",
    "descripcion": "Sede de la municipalidad de Calama con revestimientos de placas de cobre electrolítico, gran atrio cívico central y sistemas de inercia térmica contra la oscilación de temperatura del desierto.",
    "fuente_url": "https://www.municipalidadcalama.cl",
    "materiales_principales": ["Placas de cobre puro", "Hormigón armado", "Vidrio reflectivo"]
  },
  {
    "id": "terminal-rodoviario-antofagasta",
    "nombre_proyecto": "Terminal de Buses Rodoviario de Antofagasta",
    "arquitecto": "Inversiones Urbanas Norte",
    "arquitecto_principal": "Arquitectos de Transporte",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Pedro Aguirre Cerda 5750, Antofagasta",
    "coordenadas": {"lat": -23.5950, "lng": -70.3920},
    "ano_diseno": "2007",
    "anos_construccion": "2008",
    "ano_inauguracion": "2008",
    "estilos": ["Contemporáneo de Transporte"],
    "programa": ["Transporte"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Terminal interprovincial con 40 andenes de embarque protegidos por marquesinas de estructura metálica tridimensional y amplio hall de espera climatizado.",
    "fuente_url": "https://www.rodoviarioantofagasta.cl",
    "materiales_principales": ["Estructura espacial de acero", "Vidrio", "Pavimento de alta resistencia"]
  },
  {
    "id": "paseo-matta-antofagasta",
    "nombre_proyecto": "Paseo Peatonal Manuel Antonio Matta",
    "arquitecto": "Municipalidad de Antofagasta / MINVU",
    "arquitecto_principal": "Arquitectos Urbanistas Municipales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Matta entre Arturo Prat y Maipú, Antofagasta",
    "coordenadas": {"lat": -23.6480, "lng": -70.3960},
    "ano_diseno": "2016",
    "anos_construccion": "2017-2018",
    "ano_inauguracion": "2018",
    "estilos": ["Urbanismo Peatonal Contemporáneo"],
    "programa": ["Espacio Público"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Eje peatonal central con baldosas táctiles de piedra natural, pérgolas metálicas con enredaderas de sombra y mobiliario urbano de hormigón arquitectónico.",
    "fuente_url": "https://www.municipalidadantofagasta.cl",
    "materiales_principales": ["Baldosas de granito", "Acero galvanizado", "Hormigón arquitectónico"]
  },
  {
    "id": "parque-de-los-eventos-antofagasta",
    "nombre_proyecto": "Parque de los Eventos de Antofagasta",
    "arquitecto": "MOP Obras Portuarias / Municipalidad",
    "arquitecto_principal": "MOP Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Balmaceda frente al Puerto, Antofagasta",
    "coordenadas": {"lat": -23.6380, "lng": -70.3970},
    "ano_diseno": "2000",
    "anos_construccion": "2001-2002",
    "ano_inauguracion": "2002",
    "estilos": ["Paisajismo de Borde Costero"],
    "programa": ["Espacio Público"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Espacio público multipropósito que acoge las fondas patrias y festivales multitudinarios de la ciudad junto al mar, con explanada pavimentada y mirador marítimo.",
    "fuente_url": "https://www.municipalidadantofagasta.cl",
    "materiales_principales": ["Hormigón", "Piedra", "Iluminación de alta eficiencia"]
  },
  {
    "id": "centro-de-capacitacion-codelco-calama",
    "nombre_proyecto": "Centro de Entrenamiento Técnico Codelco Distrito Norte",
    "arquitecto": "Codelco Norte / Arquitectura Industrial",
    "arquitecto_principal": "Ingenieros Codelco",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Circunvalación s/n, Calama",
    "coordenadas": {"lat": -22.4400, "lng": -68.9100},
    "ano_diseno": "2015",
    "anos_construccion": "2016",
    "ano_inauguracion": "2016",
    "estilos": ["Contemporáneo Industrial"],
    "programa": ["Educación / Minería"],
    "ciudad": "Calama",
    "pais": "Chile",
    "descripcion": "Centro de simuladores de camiones mineros y minería subterránea con envolvente térmica y fachadas ventiladas de cobre oxidado.",
    "fuente_url": "https://www.codelco.com",
    "materiales_principales": ["Acero", "Chapa de cobre", "Paneles aislados"]
  },
  {
    "id": "edificio-borde-mar-antofagasta",
    "nombre_proyecto": "Edificio Borde Mar",
    "arquitecto": "Estudio Altiplano Arquitectura",
    "arquitecto_principal": "Arquitectos Costeros",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. República de Croacia 0300, Antofagasta",
    "coordenadas": {"lat": -23.6750, "lng": -70.4070},
    "ano_diseno": "2016",
    "anos_construccion": "2017-2018",
    "ano_inauguracion": "2018",
    "estilos": ["Contemporáneo Residencial Costero"],
    "programa": ["Residencial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Torre habitacional frente al mar con balcones con barandas de vidrio transparente continuo para una conexión visual sin obstáculos con el océano.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio de seguridad", "Porcelanato"]
  },
  {
    "id": "escuela-e-42-san-pedro-de-atacama",
    "nombre_proyecto": "Escuela Básica E-26 de San Pedro de Atacama",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Licancabur s/n, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9130, "lng": -68.2010},
    "ano_diseno": "2017",
    "anos_construccion": "2018-2019",
    "ano_inauguracion": "2019",
    "estilos": ["Vernáculo Contemporáneo Educacional"],
    "programa": ["Educación"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Escuela rural andina construida respetando la estética del oasis con muros estucados en tierra, sombreaderos de caña y patios comunitarios.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Albañilería de tierra", "Madera tratada", "Caña"]
  },

  # 6. Casas Contemporáneas, Refugios y Hoteles Boutique (12)
  {
    "id": "casa-en-san-pedro-de-atacama-cazú-zegers",
    "nombre_proyecto": "Casa en Atacama (Taller Cazú Zegers)",
    "arquitecto": "Cazú Zegers",
    "arquitecto_principal": "Cazú Zegers",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ayllu de Solor, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9350, "lng": -68.1900},
    "ano_diseno": "2009",
    "anos_construccion": "2010",
    "ano_inauguracion": "2010",
    "estilos": ["Arquitectura Poética del Territorio"],
    "programa": ["Residencial"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Vivienda concebida como un pliegue de la tierra desértica, con muros curvos continuos de tierra cruda y patios hundidos que capturan el silencio del altiplano.",
    "fuente_url": "https://www.cazuzegers.cl",
    "materiales_principales": ["Tierra estabilizada", "Madera reciclada", "Piedra volcánica"]
  },
  {
    "id": "casa-de-la-luna-san-pedro-atacama",
    "nombre_proyecto": "Casa de la Luna",
    "arquitecto": "Estudio Oasis Atacameño",
    "arquitecto_principal": "Arquitectos del Desierto",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de la Luna, Cordillera de la Sal",
    "coordenadas": {"lat": -22.9250, "lng": -68.2700},
    "ano_diseno": "2012",
    "anos_construccion": "2013",
    "ano_inauguracion": "2013",
    "estilos": ["Minimalismo de Sal y Barro"],
    "programa": ["Residencial"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Refugio en las inmediaciones de la Cordillera de la Sal, con bloques de sal gema y arcilla roja que dialogan con el viento y las sombras crepusculares.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Bloques de sal", "Arcilla roja", "Vidrio"]
  },
  {
    "id": "hotel-al-tiplano-san-pedro",
    "nombre_proyecto": "Hotel Altiplánico San Pedro de Atacama",
    "arquitecto": "Estudio Altiplánico Arquitectura",
    "arquitecto_principal": "Arquitectos Altiplánico",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Domingo Atienza s/n, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9220, "lng": -68.2010},
    "ano_diseno": "2003",
    "anos_construccion": "2004",
    "ano_inauguracion": "2004",
    "estilos": ["Arquitectura Escultórica de Barro"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Conjunto de habitaciones ondulantes con formas orgánicas moldeadas a mano en barro, techos de paja brava y ventanas estratégicamente orientadas a los volcanes.",
    "fuente_url": "https://www.altiplanico.cl",
    "materiales_principales": ["Barro modelado a mano", "Paja brava", "Madera rústica"]
  },
  {
    "id": "casa-solor-san-pedro-atacama",
    "nombre_proyecto": "Casa Solor",
    "arquitecto": "Taller Andino",
    "arquitecto_principal": "Arquitectura de Oasis",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ayllu de Solor, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9400, "lng": -68.1850},
    "ano_diseno": "2015",
    "anos_construccion": "2016",
    "ano_inauguracion": "2016",
    "estilos": ["Contemporáneo de Oasis"],
    "programa": ["Residencial"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Casa patio con muros de tapial de 60 cm de espesor que proporcionan confort térmico pasivo absoluto entre los 35°C diurnos y los bajo cero nocturnos.",
    "fuente_url": "https://www.plataformaarquitectura.cl",
    "materiales_principales": ["Tapial (tierra apisonada)", "Madera de algarrobo", "Vidrio doble hermético"]
  },
  {
    "id": "hotel-poblado-kimal-san-pedro",
    "nombre_proyecto": "Hotel Kimal (Poblado Kimal)",
    "arquitecto": "Kimal Arquitectura y Tradición",
    "arquitecto_principal": "Arquitectos de San Pedro",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Domingo Atienza 352, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9125, "lng": -68.1985},
    "ano_diseno": "2001",
    "anos_construccion": "2002",
    "ano_inauguracion": "2002",
    "estilos": ["Vernáculo Integrado de Centro Histórico"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Hotel boutique integrado a la trama del casco antiguo con callejuelas interiores de tierra sombreadas por chañares y acequias de agua viva.",
    "fuente_url": "https://www.kimal.cl",
    "materiales_principales": ["Adobe", "Caña", "Madera", "Tierra"]
  },
  {
    "id": "casa-en-juan-lopez-antofagasta",
    "nombre_proyecto": "Casa en Caleta Juan López",
    "arquitecto": "Estudio Litoral Desértico",
    "arquitecto_principal": "Arquitectos del Norte",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Caleta Juan López, Península de Mejillones, 38 km al norte de Antofagasta",
    "coordenadas": {"lat": -23.5150, "lng": -70.5350},
    "ano_diseno": "2013",
    "anos_construccion": "2014",
    "ano_inauguracion": "2014",
    "estilos": ["Costero en Pendiente Escarpada"],
    "programa": ["Residencial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Residencia clavada en los acantilados rocosos de la bahía abrigada de Juan López, con terrazas de madera en voladizo sobre las olas calmas del océano.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Hormigón visto", "Pino impregnado", "Acero inoxidable"]
  },
  {
    "id": "refugio-toconao-oasis",
    "nombre_proyecto": "Refugio Quebrada de Jere",
    "arquitecto": "Comunidad de Toconao",
    "arquitecto_principal": "Canteros Locales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Quebrada de Jere, Toconao, San Pedro de Atacama",
    "coordenadas": {"lat": -23.1880, "lng": -67.9950},
    "ano_diseno": "2011",
    "anos_construccion": "2012",
    "ano_inauguracion": "2012",
    "estilos": ["Cantería Vernácula en Piedra Liparita"],
    "programa": ["Turístico / Refugio"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Pabellón de acogida a los visitantes de la quebrada de Jere, levantado en mampostería seca de piedra liparita blanca encajada con precisión incaica.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra liparita blanca", "Madera", "Paja"]
  },
  {
    "id": "casa-terrazas-antofagasta-sur",
    "nombre_proyecto": "Casa Terrazas del Mar",
    "arquitecto": "Taller Moderno Antofagasta",
    "arquitecto_principal": "Arquitectos Urbanos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Jardines del Sur, Antofagasta",
    "coordenadas": {"lat": -23.6820, "lng": -70.4090},
    "ano_diseno": "2017",
    "anos_construccion": "2018",
    "ano_inauguracion": "2018",
    "estilos": ["Contemporáneo Residencial"],
    "programa": ["Residencial"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Vivienda en tres niveles escalonados sobre la pendiente con vistas al monumento natural La Portada y piscina suspendida de hormigón blanco.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón blanco", "Vidrio reflectivo", "Aluminio"]
  },
  {
    "id": "casa-pukara-san-pedro-atacama",
    "nombre_proyecto": "Casa Pukara",
    "arquitecto": "Estudio Andino Contemporáneo",
    "arquitecto_principal": "Arquitectura de Altura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ayllu de Quitor, San Pedro de Atacama",
    "coordenadas": {"lat": -22.8950, "lng": -68.2120},
    "ano_diseno": "2014",
    "anos_construccion": "2015",
    "ano_inauguracion": "2015",
    "estilos": ["Contemporáneo Likanantay"],
    "programa": ["Residencial"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Vivienda que reinterpreta las terrazas defensivas del Pukara de Quitor con muros de contención de piedra andina y amplias pérgolas de chañar.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Piedra andesita", "Madera nativa", "Tierra"]
  },
  {
    "id": "hotel-desertica-san-pedro-atacama",
    "nombre_proyecto": "Hotel Desértica",
    "arquitecto": "Taller Desértica / Paisajismo Nativo",
    "arquitecto_principal": "Arquitectos de Paisaje",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Caracoles 455, San Pedro de Atacama",
    "coordenadas": {"lat": -22.9112, "lng": -68.1970},
    "ano_diseno": "2017",
    "anos_construccion": "2018",
    "ano_inauguracion": "2018",
    "estilos": ["Boutique Sustentable de Oasis"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Emplazado en una huerta histórica del centro con cabañas circulares tipo yurtas atacameñas construidas con adobe, madera y fibras vegetales.",
    "fuente_url": "https://www.desertica.com",
    "materiales_principales": ["Adobe", "Madera", "Fibras de lana y caña"]
  },
  {
    "id": "casa-caleta-buena-tocopilla",
    "nombre_proyecto": "Casa en Caleta Buena",
    "arquitecto": "Estudio Marítimo Tocopilla",
    "arquitecto_principal": "Arquitectos de Costa",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Borde Costero entre Tocopilla e Iquique",
    "coordenadas": {"lat": -21.8500, "lng": -70.1800},
    "ano_diseno": "2018",
    "anos_construccion": "2019",
    "ano_inauguracion": "2019",
    "estilos": ["Costero Desértico Aislado"],
    "programa": ["Residencial"],
    "ciudad": "Tocopilla",
    "pais": "Chile",
    "descripcion": "Refugio totalmente autosuficiente fuera de la red (off-grid) con energía solar fotovoltaica, desalinización osmótica propia y muros de hormigón ciclópeo.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Hormigón ciclópeo", "Madera tratada", "Paneles solares"]
  },
  {
    "id": "refugio-geiseres-del-tatio",
    "nombre_proyecto": "Refugio y Centro de Visitantes Géiseres del Tatio",
    "arquitecto": "Comunidades Atacameñas de Caspana y Toconce / MOP",
    "arquitecto_principal": "Arquitectos de Altura Andina",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Campo Geotérmico del Tatio, 4.320 msnm",
    "coordenadas": {"lat": -22.3350, "lng": -68.0130},
    "ano_diseno": "2012",
    "anos_construccion": "2013",
    "ano_inauguracion": "2013",
    "estilos": ["Arquitectura en Alta Montaña y Clima Extremo"],
    "programa": ["Turístico / Refugio"],
    "ciudad": "Calama",
    "pais": "Chile",
    "descripcion": "Instalación turística a 4.320 msnm en el campo geotérmico más alto del mundo, con aislamiento térmico para resistir temperaturas de -20°C y uso de energía geotermal pasiva.",
    "fuente_url": "https://www.sernatur.cl",
    "materiales_principales": ["Piedra volcánica", "Paneles aislantes poliuretano", "Madera"]
  },

  # 7. Infraestructura Científica, Observatorios y Tecnología (10)
  {
    "id": "observatorio-paranal-eso-residencia",
    "nombre_proyecto": "Residencia del Observatorio Cerro Paranal (Hotel de los Astrónomos)",
    "arquitecto": "Auer+Weber+Assoziierte",
    "arquitecto_principal": "Philipp Auer, Fritz Auer",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Cerro Paranal, 130 km al sur de Antofagasta, Desierto de Atacama",
    "coordenadas": {"lat": -24.6272, "lng": -70.4042},
    "ano_diseno": "1998",
    "anos_construccion": "2000-2002",
    "ano_inauguracion": "2002",
    "estilos": ["Arquitectura Semienterrada de Ciencia Ficción", "Vanguardia Mundial"],
    "programa": ["Científico / Hotelero / Investigación"],
    "ciudad": "Taltal",
    "pais": "Chile",
    "descripcion": "Obra maestra mundial de la arquitectura desértica (locación cumbre de la película de James Bond 'Quantum of Solace'). Edificio semienterrado en una zanja del desierto con un oasis interior cubierto por una cúpula de 35 metros que alberga una piscina tropical para devolver la humedad a los astrónomos.",
    "fuente_url": "https://www.eso.org/public/chile/teles-instr/paranal-site/residencia/",
    "materiales_principales": ["Hormigón pigmentado color rojizo del desierto", "Acero", "Cúpula de policarbonato", "Vidrio"]
  },
  {
    "id": "telescopio-vlt-cerro-paranal",
    "nombre_proyecto": "Very Large Telescope (VLT) Cerro Paranal",
    "arquitecto": "European Southern Observatory (ESO) / Ingenieros Astronómicos",
    "arquitecto_principal": "Consorcio Científico Europeo",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Cumbre de Cerro Paranal a 2.635 msnm, Taltal",
    "coordenadas": {"lat": -24.6253, "lng": -70.4039},
    "ano_diseno": "1991",
    "anos_construccion": "1993-1998",
    "ano_inauguracion": "1998",
    "estilos": ["Megacúpulas Astronómicas", "Alta Tecnología"],
    "programa": ["Científico / Astronómico"],
    "ciudad": "Taltal",
    "pais": "Chile",
    "descripcion": "El observatorio astronómico óptico más avanzado del planeta, con cuatro recintos cilíndricos colosales de acero para los telescopios unitarios de 8,2 metros y túneles subterráneos de interferometría óptica.",
    "fuente_url": "https://www.eso.org",
    "materiales_principales": ["Acero aluminizado de alta reflectividad", "Hormigón masivo sismorresistente", "Espejos cerámicos Zerodur"]
  },
  {
    "id": "observatorio-alma-chajnantor",
    "nombre_proyecto": "Observatorio ALMA (Atacama Large Millimeter/submillimeter Array)",
    "arquitecto": "Consorcio ALMA (ESO, NSF, NINS) / MOP",
    "arquitecto_principal": "Ingenieros de Radioastronomía Mundial",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Llano de Chajnantor a 5.000 msnm, San Pedro de Atacama",
    "coordenadas": {"lat": -23.0292, "lng": -67.7550},
    "ano_diseno": "2003",
    "anos_construccion": "2004-2013",
    "ano_inauguracion": "2013",
    "estilos": ["Alta Tecnología Radioastronómica a 5.000 msnm"],
    "programa": ["Científico / Radioastronómico"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "El mayor radiotelescopio del planeta. Complejo compuesto por 66 antenas de alta precisión de hasta 12 metros de diámetro operando en red interferométrica a 5.000 metros de altitud, con el correlador computacional más rápido del mundo.",
    "fuente_url": "https://www.almaobservatory.org",
    "materiales_principales": ["Fibra de carbono", "Paneles de níquel", "Transportadores colosales de oruga", "Hormigón criogénico"]
  },
  {
    "id": "campamento-base-osf-alma",
    "nombre_proyecto": "Campamento Base y Residencia OSF de ALMA",
    "arquitecto": "Kobe Arquitectos / Consorcio ALMA",
    "arquitecto_principal": "Arquitectos Científicos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Operaciones ALMA (OSF) a 2.900 msnm, San Pedro de Atacama",
    "coordenadas": {"lat": -23.0800, "lng": -68.0400},
    "ano_diseno": "2008",
    "anos_construccion": "2010-2014",
    "ano_inauguracion": "2014",
    "estilos": ["Arquitectura Modular Sustentable de Altura"],
    "programa": ["Científico / Residencial"],
    "ciudad": "San Pedro de Atacama",
    "pais": "Chile",
    "descripcion": "Centro de operaciones técnicas y residencia para científicos de todo el mundo a 2.900 msnm, con edificios modulares aislados térmicamente y presurizados con enriquecimiento de oxígeno.",
    "fuente_url": "https://www.almaobservatory.org",
    "materiales_principales": ["Paneles sandwich aislantes", "Acero", "Vidrio de triple contacto"]
  },
  {
    "id": "extremely-large-telescope-elt-armazones",
    "nombre_proyecto": "Extremely Large Telescope (ELT) Cerro Armazones",
    "arquitecto": "ESO (European Southern Observatory) / Consorcio Ace",
    "arquitecto_principal": "Ingenieros de ESO",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Cumbre de Cerro Armazones a 3.046 msnm, Sierra Gorda / Taltal",
    "coordenadas": {"lat": -24.5892, "lng": -70.1917},
    "ano_diseno": "2014",
    "anos_construccion": "2017-2027",
    "ano_inauguracion": "2028",
    "estilos": ["Megaestructura Astronómica del Siglo XXI"],
    "programa": ["Científico / Astronómico"],
    "ciudad": "Taltal",
    "pais": "Chile",
    "descripcion": "'El ojo más grande del mundo para mirar el cielo'. Colosal cúpula astronómica de 80 metros de altura y 88 metros de diámetro con un telescopio óptico de 39 metros de diámetro segmentado en 798 hexágonos que responderá los misterios del universo primigenio.",
    "fuente_url": "https://elt.eso.org",
    "materiales_principales": ["Acero estructural de ultra alta resistencia", "Aisladores sísmicos masivos", "Zerodur cerámico"]
  },
  {
    "id": "cerro-murphy-observatorio-concepcion",
    "nombre_proyecto": "Observatorio Cerro Murphy",
    "arquitecto": "Universidad de Concepción / Universidad de Bochum",
    "arquitecto_principal": "Ingeniería Astronómica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Cerro Murphy, Desierto de Atacama",
    "coordenadas": {"lat": -24.6000, "lng": -70.3200},
    "ano_diseno": "2005",
    "anos_construccion": "2006",
    "ano_inauguracion": "2006",
    "estilos": ["Cúpulas Robóticas Astronómicas"],
    "programa": ["Científico"],
    "ciudad": "Taltal",
    "pais": "Chile",
    "descripcion": "Estación astronómica con telescopios robóticos de operación remota que monitorean estrellas variables y supernovas en el cielo más transparente de la Tierra.",
    "fuente_url": "https://www.astronomia.udec.cl",
    "materiales_principales": ["Cúpula de fibra de vidrio", "Hormigón", "Acero"]
  },
  {
    "id": "planta-solar-cerro-dominador-maria-elena",
    "nombre_proyecto": "Planta Solar Termoeléctrica Cerro Dominador",
    "arquitecto": "Abengoa / EIG Global Energy Partners",
    "arquitecto_principal": "Ingenieros de Energía Solar de Concentración",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta 5 Norte Km 1440, María Elena / Sierra Gorda",
    "coordenadas": {"lat": -23.2380, "lng": -69.4180},
    "ano_diseno": "2014",
    "anos_construccion": "2015-2021",
    "ano_inauguracion": "2021",
    "estilos": ["Hito Escultórico Tecnológico", "Energía Limpia"],
    "programa": ["Industrial / Energía Solar"],
    "ciudad": "María Elena",
    "pais": "Chile",
    "descripcion": "La primera planta termosolar de torre y sales fundidas de América Latina. Su torre receptora de 250 metros de altura (la segunda estructura más alta de Chile) está rodeada por 10.600 heliostatos que reflejan la luz solar concentrada para generar energía limpia 24 horas continuas.",
    "fuente_url": "https://www.cerrodominador.com",
    "materiales_principales": ["Torre de hormigón armado de 250 m", "Espejos heliostatos", "Sales fundidas"]
  },
  {
    "id": "observatorio-cero-moreno-meteorologia",
    "nombre_proyecto": "Estación Meteorológica y de Radar Cerro Moreno",
    "arquitecto": "Dirección Meteorológica de Chile (DMC) / DGAC",
    "arquitecto_principal": "DGAC Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Península de Mejillones, Cerro Moreno",
    "coordenadas": {"lat": -23.5100, "lng": -70.5200},
    "ano_diseno": "1995",
    "anos_construccion": "1996",
    "ano_inauguracion": "1996",
    "estilos": ["Infraestructura Meteorológica Costera"],
    "programa": ["Científico / Meteorológico"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "Radomo esférico sobre torre de hormigón en la cima de Cerro Moreno (1.100 msnm) para el monitoreo de la camanchaca y vientos costeros del norte grande.",
    "fuente_url": "https://www.meteochile.gob.cl",
    "materiales_principales": ["Radomo de fibra de vidrio", "Hormigón armado sismorresistente", "Acero"]
  },
  {
    "id": "planta-desaladora-norte-antofagasta",
    "nombre_proyecto": "Planta Desaladora Norte de Antofagasta",
    "arquitecto": "Aguas de Antofagasta / Degrémont",
    "arquitecto_principal": "Ingenieros de Desalación Marina",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector La Chimba, borde costero norte, Antofagasta",
    "coordenadas": {"lat": -23.5650, "lng": -70.3980},
    "ano_diseno": "2001",
    "anos_construccion": "2002-2003",
    "ano_inauguracion": "2003",
    "estilos": ["Infraestructura Hídrica Pionera"],
    "programa": ["Industrial / Hídrico"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "La primera gran planta desaladora de agua de mar para consumo humano de una ciudad completa en América Latina, que abastece de agua potable al 100% de la población urbana de Antofagasta y Mejillones.",
    "fuente_url": "https://www.aguasantofagasta.cl",
    "materiales_principales": ["Membranas poliméricas de osmosis", "Acero súper dúplex", "Hormigón marino"]
  },
  {
    "id": "observatorio-atacama-1m-san-pedro",
    "nombre_proyecto": "Observatorio Atacama 1-Metro (Ckoirama)",
    "arquitecto": "Universidad de Antofagasta / Unidad de Astronomía",
    "arquitecto_principal": "Arquitectos de Infraestructura Científica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Estación Experimental Los Desiertos, 70 km al sureste de Antofagasta",
    "coordenadas": {"lat": -24.0880, "lng": -69.9320},
    "ano_diseno": "2013",
    "anos_construccion": "2014-2015",
    "ano_inauguracion": "2015",
    "estilos": ["Observatorio Universitario Chileno"],
    "programa": ["Científico / Educación"],
    "ciudad": "Antofagasta",
    "pais": "Chile",
    "descripcion": "El primer observatorio profesional de investigación astronómica operado íntegramente por una universidad pública estatal del norte chileno, con cúpula de apertura automática y telescopio robótico.",
    "fuente_url": "https://www.astro.uantof.cl/ckoirama/",
    "materiales_principales": ["Cúpula de aluminio y fibra", "Hormigón", "Sensores CCD criogénicos"]
  }
]

with open("data_antofagasta_p1.json", "r", encoding="utf-8") as f:
  p1 = json.load(f)

total_antofagasta = p1 + obras_antofagasta_p2
print(f"Total works in Antofagasta: {len(total_antofagasta)}")

with open("data_antofagasta_100.json", "w", encoding="utf-8") as f:
  json.dump(total_antofagasta, f, ensure_ascii=False, indent=2)

print("Saved data_antofagasta_100.json successfully!")
