#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Completes the 100 works of Región de Arica y Parinacota (Sections 3, 4, 5, 6)"""
import json

obras_sec3_6 = [
  # 3. Vivienda Social e Infraestructura del Movimiento Moderno y Junta de Adelanto de Arica (JAA) (16)
  {
    "id": "poblacion-chinchorro-arica",
    "nombre_proyecto": "Población Chinchorro",
    "arquitecto": "Corporación de la Vivienda (CORVI)",
    "arquitecto_principal": "Equipo de Arquitectura CORVI",
    "colaboradores": "Junta de Adelanto de Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Chinchorro Oriente, Arica",
    "coordenadas": {"lat": -18.4550, "lng": -70.3010},
    "ano_diseno": "1960",
    "anos_construccion": "1961-1962",
    "ano_inauguracion": "1962",
    "estilos": ["Racionalismo", "Vivienda Social Moderna"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Emblemático conjunto habitacional de la CORVI que introdujo la tipología de bloques lineales con ventilación cruzada y celosías cerámicas para responder al clima desértico costero de Arica.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Albañilería confinada", "Losa de hormigón", "Celosía de greda cocida"]
  },
  {
    "id": "poblacion-magisterio-arica",
    "nombre_proyecto": "Población Magisterio",
    "arquitecto": "Junta de Adelanto de Arica / CORVI",
    "arquitecto_principal": "Equipo Técnico JAA",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. 18 de Septiembre con Tucapel, Arica",
    "coordenadas": {"lat": -18.4870, "lng": -70.3050},
    "ano_diseno": "1963",
    "anos_construccion": "1964-1965",
    "ano_inauguracion": "1965",
    "estilos": ["Movimiento Moderno", "Vivienda Social"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Barrio residencial planificado para el gremio docente, caracterizado por viviendas pareadas de un piso con cubiertas ligeras, patios interiores y pasajes peatonales arbolados.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Bloque de hormigón", "Madera", "Cubierta de asbesto-cemento"]
  },
  {
    "id": "poblacion-juan-noe-arica",
    "nombre_proyecto": "Población Juan Noé",
    "arquitecto": "Junta de Adelanto de Arica (JAA)",
    "arquitecto_principal": "Arquitectos JAA",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Juan Noé, Av. Diego Portales, Arica",
    "coordenadas": {"lat": -18.4735, "lng": -70.3032},
    "ano_diseno": "1966",
    "anos_construccion": "1967-1968",
    "ano_inauguracion": "1968",
    "estilos": ["Racionalismo", "Urbanismo Moderno"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Gran intervención urbana de la JAA concebida con supermanzanas, áreas verdes comunitarias y equipamiento vecinal integral para los obreros de las industrias automotrices.",
    "fuente_url": "https://www.uta.cl",
    "materiales_principales": ["Albañilería de ladrillo", "Hormigón armado", "Perfiles de acero"]
  },
  {
    "id": "conjunto-habitacional-estadio-arica",
    "nombre_proyecto": "Conjunto Habitacional Estadio",
    "arquitecto": "CORVI / Junta de Adelanto de Arica",
    "arquitecto_principal": "Equipo CORVI",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Adyacente al Estadio Carlos Dittborn, Arica",
    "coordenadas": {"lat": -18.4855, "lng": -70.2980},
    "ano_diseno": "1962",
    "anos_construccion": "1963-1964",
    "ano_inauguracion": "1964",
    "estilos": ["Movimiento Moderno", "Brutalismo"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Edificios de cuatro pisos estructurados en hormigón armado a la vista con pasarelas de circulación abiertas que favorecen el encuentro vecinal y la brisa marina nocturna.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón armado visto", "Albañilería", "Barandas metálicas"]
  },
  {
    "id": "poblacion-manuel-rodriguez-arica",
    "nombre_proyecto": "Población Manuel Rodríguez",
    "arquitecto": "Corporación de la Vivienda (CORVI)",
    "arquitecto_principal": "CORVI",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Cerro La Cruz, Arica",
    "coordenadas": {"lat": -18.4890, "lng": -70.3150},
    "ano_diseno": "1959",
    "anos_construccion": "1960",
    "ano_inauguracion": "1960",
    "estilos": ["Racionalismo"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Asentamiento moderno escalonado sobre la topografía del cerro, empleando muros de contención de piedra andesita y casas de albañilería con azoteas transitables.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Piedra de cantera", "Ladrillo", "Losa de hormigón"]
  },
  {
    "id": "poblacion-carlos-pezoa-veliz-arica",
    "nombre_proyecto": "Población Carlos Pezoa Véliz",
    "arquitecto": "Corporación de la Vivienda (CORVI)",
    "arquitecto_principal": "CORVI",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Azolas con Renato Rocca, Arica",
    "coordenadas": {"lat": -18.4680, "lng": -70.2990},
    "ano_diseno": "1968",
    "anos_construccion": "1969-1970",
    "ano_inauguracion": "1970",
    "estilos": ["Racionalismo", "Bloques CORVI"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Conjunto de bloques habitacionales prefabricados tipo H con escaleras abiertas exentas y marquesinas de hormigón que generan sombras arrojadas sobre las fachadas.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón armado", "Paneles premoldeados", "Malla metálica"]
  },
  {
    "id": "edificio-plaza-condell-arica",
    "nombre_proyecto": "Edificio Plaza Condell",
    "arquitecto": "Privado / Constructora JAA",
    "arquitecto_principal": "Arquitectos Modernos Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Plaza Condell, Calle Patricio Lynch, Arica",
    "coordenadas": {"lat": -18.4790, "lng": -70.3160},
    "ano_diseno": "1969",
    "anos_construccion": "1970-1971",
    "ano_inauguracion": "1971",
    "estilos": ["Racionalismo en Altura"],
    "programa": ["Residencial", "Comercial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Torre habitacional pionera en el centro urbano de Arica con placa comercial en primer piso, balcones voladizos continuos y remate con terraza panorámica sobre el puerto.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio", "Aluminio"]
  },
  {
    "id": "poblacion-cardenal-silva-henriquez-arica",
    "nombre_proyecto": "Población Cardenal Silva Henríquez",
    "arquitecto": "Ministerio de la Vivienda y Urbanismo (MINVU)",
    "arquitecto_principal": "MINVU Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Norte, Av. Cancha Rayada, Arica",
    "coordenadas": {"lat": -18.4420, "lng": -70.2920},
    "ano_diseno": "1976",
    "anos_construccion": "1977-1978",
    "ano_inauguracion": "1978",
    "estilos": ["Vivienda Estatal Densa"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Mega población del norte de la ciudad que absorbió el crecimiento demográfico obrero y pesquero con una retícula ordenada de bloques multifamiliares.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Bloques de concreto", "Hormigón armado", "Tejuelas asfálticas"]
  },
  {
    "id": "poblacion-san-jose-arica",
    "nombre_proyecto": "Población San José",
    "arquitecto": "Junta de Adelanto de Arica (JAA)",
    "arquitecto_principal": "JAA",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector San José, Arica",
    "coordenadas": {"lat": -18.4810, "lng": -70.2940},
    "ano_diseno": "1964",
    "anos_construccion": "1965-1966",
    "ano_inauguracion": "1966",
    "estilos": ["Movimiento Moderno", "Vivienda Social"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Desarrollo habitacional de escala barrial con plazas centrales triangulares, centros comunitarios y viviendas de crecimiento progresivo.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Albañilería", "Madera", "Cubiertas de zinc"]
  },
  {
    "id": "conjunto-habitacional-san-marcos-arica",
    "nombre_proyecto": "Conjunto Habitacional San Marcos",
    "arquitecto": "Corporación de Mejoramiento Urbano (CORMU) / CORVU",
    "arquitecto_principal": "Equipo CORMU",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Santa María con Juan Noé, Arica",
    "coordenadas": {"lat": -18.4750, "lng": -70.3090},
    "ano_diseno": "1971",
    "anos_construccion": "1972-1973",
    "ano_inauguracion": "1973",
    "estilos": ["Racionalismo", "Bloque CORVU"],
    "programa": ["Vivienda"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Bloques de viviendas de alta densidad que representan el período tardío de las corporaciones estatales chilenas, con patios comunes y pasillos exteriores en voladizo.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón armado", "Ladrillo princesa", "Acero"]
  },
  {
    "id": "edificio-alborada-arica",
    "nombre_proyecto": "Edificio Alborada",
    "arquitecto": "Arquitectos Modernos del Norte",
    "arquitecto_principal": "Oficina Técnica Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle 18 de Septiembre 340, Arica",
    "coordenadas": {"lat": -18.4812, "lng": -70.3170},
    "ano_diseno": "1972",
    "anos_construccion": "1973-1974",
    "ano_inauguracion": "1974",
    "estilos": ["Movimiento Moderno", "Residencial"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Edificio habitacional en altura con quiebrasoles verticales de hormigón y vanos profundos para mitigar la radiación del mediodía.",
    "fuente_url": "https://www.uta.cl",
    "materiales_principales": ["Hormigón armado", "Mármol reconstituido", "Vidrio"]
  },
  {
    "id": "estadio-carlos-dittborn-arica",
    "nombre_proyecto": "Estadio Carlos Dittborn",
    "arquitecto": "Karl Sorensen / Junta de Adelanto de Arica",
    "arquitecto_principal": "Karl Sorensen",
    "colaboradores": "Junta de Adelanto de Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. 18 de Septiembre 2000, Arica",
    "coordenadas": {"lat": -18.4875, "lng": -70.2977},
    "ano_diseno": "1960",
    "anos_construccion": "1961-1962",
    "ano_inauguracion": "1962",
    "estilos": ["Movimiento Moderno", "Brutalismo Deportivo"],
    "programa": ["Deportivo"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Sede de la Copa Mundial de la FIFA Chile 1962 construida en tiempo récord por la Junta de Adelanto. Destaca su estructura de graderías cóncavas de hormigón armado y su marquesina volada en tribuna oficial.",
    "fuente_url": "https://www.municipalidaddearica.cl",
    "materiales_principales": ["Hormigón armado pretensado", "Acero", "Tierra compactada"]
  },
  {
    "id": "campus-velasquez-uta-arica",
    "nombre_proyecto": "Campus Velásquez Universidad de Tarapacá",
    "arquitecto": "Junta de Adelanto de Arica / MOP",
    "arquitecto_principal": "Equipo JAA",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. General Velásquez 1775, Arica",
    "coordenadas": {"lat": -18.4905, "lng": -70.3060},
    "ano_diseno": "1963",
    "anos_construccion": "1964-1965",
    "ano_inauguracion": "1965",
    "estilos": ["Brutalismo Universitario", "Modernismo"],
    "programa": ["Educación"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Campus universitario fundado en la era dorada de la JAA (originalmente Universidad del Norte / Universidad de Chile sede Arica). Pabellones con patios de luz, galerías porticadas y auditorio de hormigón visto.",
    "fuente_url": "https://www.uta.cl",
    "materiales_principales": ["Hormigón armado visto", "Madera", "Piedra local"]
  },
  {
    "id": "piscina-olimpica-de-arica",
    "nombre_proyecto": "Piscina Olímpica de Arica",
    "arquitecto": "Junta de Adelanto de Arica (JAA)",
    "arquitecto_principal": "Arquitectos e Ingenieros JAA",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Comandante San Martín s/n, Costanera Sur, Arica",
    "coordenadas": {"lat": -18.4895, "lng": -70.3245},
    "ano_diseno": "1970",
    "anos_construccion": "1971-1972",
    "ano_inauguracion": "1972",
    "estilos": ["Brutalismo Estructural", "Modernismo Costero"],
    "programa": ["Deportivo"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Complejo acuático al aire libre frente al Océano Pacífico, con graderías monumentales en voladizo de hormigón armado y foso de saltos ornamentales con plataforma escultural.",
    "fuente_url": "https://www.municipalidaddearica.cl",
    "materiales_principales": ["Hormigón armado impermeable", "Acero inoxidable", "Cerámica vitrificada"]
  },
  {
    "id": "hotel-el-paso-arica",
    "nombre_proyecto": "Hotel El Paso",
    "arquitecto": "Corporación de Fomento de la Producción (CORFO)",
    "arquitecto_principal": "Equipo de Arquitectura Hotelera CORFO",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. General Velásquez 1109, Arica",
    "coordenadas": {"lat": -18.4830, "lng": -70.3125},
    "ano_diseno": "1953",
    "anos_construccion": "1954-1955",
    "ano_inauguracion": "1955",
    "estilos": ["Movimiento Moderno", "Arquitectura Hotelera de Estado"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Hito de la red estatal de hoteles y hosterías de Chile (HONSA). Diseñado con pabellones horizontales articulados en torno a jardines tropicales, terrazas sombreadas y alberca privada.",
    "fuente_url": "https://www.patrimoniomoderno.cl",
    "materiales_principales": ["Hormigón armado", "Madera nativa", "Mampostería de piedra"]
  },
  {
    "id": "hosteria-arica-faa",
    "nombre_proyecto": "Hostería Arica",
    "arquitecto": "HONSA / CORFO",
    "arquitecto_principal": "Arquitectos HONSA",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Comandante San Martín 599, Playa El Laucho, Arica",
    "coordenadas": {"lat": -18.4870, "lng": -70.3255},
    "ano_diseno": "1956",
    "anos_construccion": "1957-1958",
    "ano_inauguracion": "1958",
    "estilos": ["Movimiento Moderno en la Costa"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Emplazada al borde de los requeríos y arenas de Playa El Laucho, su arquitectura se abre en amplios ventanales corridos hacia el océano, integrando salones de fiesta con cubiertas plegadas.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio templado", "Piedra de mar"]
  },

  # 4. Arquitectura Contemporánea, Equipamiento y Paisaje (17)
  {
    "id": "museo-de-sitio-colon-10-arica",
    "nombre_proyecto": "Museo de Sitio Colón 10",
    "arquitecto": "Sebastián Irarrázaval",
    "arquitecto_principal": "Sebastián Irarrázaval",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Colón 10, Casco Histórico, Arica",
    "coordenadas": {"lat": -18.4800, "lng": -70.3225},
    "ano_diseno": "2003",
    "anos_construccion": "2003-2004",
    "ano_inauguracion": "2004",
    "estilos": ["Contemporáneo", "Arquitectura Patrimonial / Arqueológica"],
    "programa": ["Cultura", "Museo"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Museo in situ que resguarda momias de la Cultura Chinchorro (las más antiguas del mundo). Un piso de vidrio suspendido permite a los visitantes caminar directamente sobre el estrato funerario iluminado en penumbra.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piso de vidrio estructural", "Acero negro", "Hormigón visto"]
  },
  {
    "id": "museo-arqueologico-san-miguel-azapa",
    "nombre_proyecto": "Museo Arqueológico de San Miguel de Azapa",
    "arquitecto": "Dirección de Arquitectura MOP / Universidad de Tarapacá",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Camino Azapa Km 12, San Miguel de Azapa",
    "coordenadas": {"lat": -18.5192, "lng": -70.2185},
    "ano_diseno": "1967",
    "anos_construccion": "1968-2010",
    "ano_inauguracion": "2010",
    "estilos": ["Arquitectura Vernácula Contemporánea", "Regionalismo Crítico"],
    "programa": ["Cultura", "Museo"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Principal recinto cultural que custodia el tesoro Chinchorro y la arqueología andina. Su arquitectura se integra a los olivares milenarios mediante pabellones de adobe contemporáneo y pérgolas de caña.",
    "fuente_url": "https://masma.uta.cl",
    "materiales_principales": ["Adobe contemporáneo", "Caña de Guayaquil", "Piedra de río", "Hormigón"]
  },
  {
    "id": "edificio-consistorial-camarones",
    "nombre_proyecto": "Edificio Consistorial de Camarones (Cuya)",
    "arquitecto": "Dirección de Arquitectura MOP Arica y Parinacota",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta 5 Norte Km 1968, Cuya, Camarones",
    "coordenadas": {"lat": -19.1610, "lng": -70.1775},
    "ano_diseno": "2013",
    "anos_construccion": "2014-2015",
    "ano_inauguracion": "2015",
    "estilos": ["Contemporáneo Institucional", "Arquitectura del Desierto"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Camarones",
    "pais": "Chile",
    "descripcion": "Sede municipal de la comuna rural emplazada en la quebrada de Cuya. Muros gruesos con acabado de tierra de color y celosías oxidadas de acero corten que protegen del sol extremo.",
    "fuente_url": "https://www.municamarones.cl",
    "materiales_principales": ["Acero corten", "Hormigón pigmentado", "Piedra local"]
  },
  {
    "id": "paso-fronterizo-chungara",
    "nombre_proyecto": "Complejo Fronterizo Chungará",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta 11-CH, Frontera Chile-Bolivia, Lago Chungará, Putre",
    "coordenadas": {"lat": -18.2830, "lng": -69.1415},
    "ano_diseno": "2015",
    "anos_construccion": "2016-2018",
    "ano_inauguracion": "2018",
    "estilos": ["Arquitectura en Climas Extremos", "Contemporáneo Funcional"],
    "programa": ["Infraestructura Fronteriza"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Construido a 4.685 msnm frente al majestuoso Lago Chungará y el volcán Parinacota. Integra aerotermia, cubiertas aerodinámicas de acero contra ventiscas y aislamiento térmico de triple capa.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Paneles aislantes de acero", "Triple vidriado hermético", "Estructura metálica"]
  },
  {
    "id": "liceo-granaderos-de-putre",
    "nombre_proyecto": "Liceo Granaderos de Putre",
    "arquitecto": "MOP Arquitectura / Consultores Bioclimáticos",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Baquedano s/n, Putre",
    "coordenadas": {"lat": -18.1970, "lng": -69.5605},
    "ano_diseno": "2010",
    "anos_construccion": "2011-2012",
    "ano_inauguracion": "2012",
    "estilos": ["Bioclimático Andino", "Contemporáneo"],
    "programa": ["Educación"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Establecimiento educacional a 3.500 msnm con muros trombe para captación solar pasiva, cubiertas vegetales de paja y piedra volcánica que reinterpretan la tradición aymara.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Piedra volcánica", "Madera laminada", "Muros trombe de vidrio y hormigón"]
  },
  {
    "id": "paseo-costero-playa-el-laucho",
    "nombre_proyecto": "Paseo Costero Playa El Laucho",
    "arquitecto": "Dirección de Obras Portuarias MOP",
    "arquitecto_principal": "MOP Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Costanera Sur, Playa El Laucho, Arica",
    "coordenadas": {"lat": -18.4880, "lng": -70.3260},
    "ano_diseno": "2013",
    "anos_construccion": "2014-2015",
    "ano_inauguracion": "2015",
    "estilos": ["Diseño de Espacio Público", "Arquitectura del Paisaje"],
    "programa": ["Espacio Público / Borde Costero"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Paseo peatonal y ciclovía con sombreadores de madera laminada curva que emulan las olas marinas, pavimentos de hormigón desbastado y miradores sobre la rompiente.",
    "fuente_url": "https://www.dop.cl",
    "materiales_principales": ["Madera tratada para ambiente marino", "Hormigón", "Acero galvanizado"]
  },
  {
    "id": "cuevas-de-anzota-arica",
    "nombre_proyecto": "Paseo Costero Cuevas de Anzota",
    "arquitecto": "Dirección de Obras Portuarias MOP / Mario Pérez de Arce",
    "arquitecto_principal": "MOP Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta Costera A-37 Km 12 al sur de Arica",
    "coordenadas": {"lat": -18.5520, "lng": -70.3290},
    "ano_diseno": "2014",
    "anos_construccion": "2015-2016",
    "ano_inauguracion": "2016",
    "estilos": ["Intervención Territorial", "Paisajismo Extremo"],
    "programa": ["Espacio Público", "Turismo"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Senda peatonal suspendida sobre acantilados rocosos y cavernas marinas milenarias donde habitaron los Chinchorro. Pasarelas de acero galvanizado ancladas a la roca viva.",
    "fuente_url": "https://www.dop.cl",
    "materiales_principales": ["Acero galvanizado en caliente", "Rejillas electroforjadas", "Roca viva"]
  },
  {
    "id": "paseo-comandante-san-martin-arica",
    "nombre_proyecto": "Paseo Costero Comandante San Martín",
    "arquitecto": "MOP Obras Portuarias / Municipalidad de Arica",
    "arquitecto_principal": "MOP Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Comandante San Martín, pie del Morro, Arica",
    "coordenadas": {"lat": -18.4820, "lng": -70.3250},
    "ano_diseno": "2012",
    "anos_construccion": "2013-2014",
    "ano_inauguracion": "2014",
    "estilos": ["Espacio Público Costero"],
    "programa": ["Espacio Público / Borde Costero"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Articulación del borde costero bajo los farallones del Morro de Arica con áreas verdes sustentables, iluminación LED rasante y plazoletas cívicas frente al océano.",
    "fuente_url": "https://www.dop.cl",
    "materiales_principales": ["Piedra granítica", "Hormigón estampado", "Acero inoxidable"]
  },
  {
    "id": "centro-cultural-junta-de-adelanto-arica",
    "nombre_proyecto": "Centro Cultural Junta de Adelanto",
    "arquitecto": "Reciclaje Patrimonial / Municipalidad de Arica",
    "arquitecto_principal": "Equipo de Patrimonio Municipal",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. General Velásquez 955, Arica",
    "coordenadas": {"lat": -18.4802, "lng": -70.3130},
    "ano_diseno": "2018",
    "anos_construccion": "2019-2020",
    "ano_inauguracion": "2020",
    "estilos": ["Reciclaje Arquitectónico", "Contemporáneo"],
    "programa": ["Cultura"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Reconversión de las antiguas dependencias de la Junta de Adelanto en centro multicultural para exposiciones, talleres artísticos y salas de artes escénicas.",
    "fuente_url": "https://www.municipalidaddearica.cl",
    "materiales_principales": ["Hormigón restaurado", "Maderas nobles", "Acristalamiento"]
  },
  {
    "id": "liceo-politecnico-arica",
    "nombre_proyecto": "Liceo Politécnico Arica (Nueva Infraestructura)",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "18 de Septiembre 2200, Arica",
    "coordenadas": {"lat": -18.4890, "lng": -70.2950},
    "ano_diseno": "2006",
    "anos_construccion": "2007-2008",
    "ano_inauguracion": "2008",
    "estilos": ["Contemporáneo Institucional"],
    "programa": ["Educación"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Edificio educacional técnico estructurado en talleres de doble altura con iluminación cenital filtrada, ventilación eólica inducida y patios de maniobras.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Hormigón armado", "Estructura metálica", "Termopanel"]
  },
  {
    "id": "tribunal-juicio-oral-arica",
    "nombre_proyecto": "Edificio del Tribunal de Juicio Oral en lo Penal de Arica",
    "arquitecto": "Poder Judicial / Dirección de Arquitectura MOP",
    "arquitecto_principal": "Corporación Administrativa del Poder Judicial",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle General Lagos con 21 de Mayo, Arica",
    "coordenadas": {"lat": -18.4796, "lng": -70.3168},
    "ano_diseno": "2004",
    "anos_construccion": "2005-2006",
    "ano_inauguracion": "2006",
    "estilos": ["Contemporáneo Institucional", "Minimalismo Cívico"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Edificio judicial caracterizado por su doble piel de celosías metálicas que mitiga el asoleamiento poniente y un atrio central con claraboya que organiza las salas de audiencia.",
    "fuente_url": "https://www.pjud.cl",
    "materiales_principales": ["Hormigón visto", "Celosías de aluminio", "Mármol travertino"]
  },
  {
    "id": "biblioteca-publica-alfredo-wormald-cruz",
    "nombre_proyecto": "Biblioteca Pública Alfredo Wormald Cruz",
    "arquitecto": "Dirección de Arquitectura MOP / DIBAM",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Baquedano 94, Arica",
    "coordenadas": {"lat": -18.4775, "lng": -70.3205},
    "ano_diseno": "2009",
    "anos_construccion": "2010-2011",
    "ano_inauguracion": "2011",
    "estilos": ["Patrimonial Contemporáneo"],
    "programa": ["Cultura", "Educación"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Remodelación integral de inmueble cívico histórico en el casco antiguo, articulando salas de lectura con muros de adobe consolidado y entrepisos de acero y cristal.",
    "fuente_url": "https://www.bibliotecaspublicas.gob.cl",
    "materiales_principales": ["Adobe restaurado", "Acero estructural", "Madera laminada"]
  },
  {
    "id": "complejo-fronterizo-chacalluta",
    "nombre_proyecto": "Complejo Fronterizo Chacalluta (Ampliación)",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta 5 Norte Km 2090, Línea de la Concordia, Arica",
    "coordenadas": {"lat": -18.3240, "lng": -70.3110},
    "ano_diseno": "2017",
    "anos_construccion": "2018-2019",
    "ano_inauguracion": "2019",
    "estilos": ["Contemporáneo", "Infraestructura de Transporte"],
    "programa": ["Infraestructura Fronteriza"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "El paso fronterizo terrestre de mayor flujo de Chile. Diseñado con marquesinas modulares de gran luz para el control expedito de vehículos y peatones en el desierto costero.",
    "fuente_url": "https://www.pasosfronterizos.gov.cl",
    "materiales_principales": ["Acero estructural", "Membrana tensada", "Hormigón pulido"]
  },
  {
    "id": "terminal-internacional-buses-arica",
    "nombre_proyecto": "Terminal Internacional de Buses de Arica",
    "arquitecto": "Municipalidad de Arica",
    "arquitecto_principal": "Equipo de Obras Municipales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Diego Portales 948, Arica",
    "coordenadas": {"lat": -18.4720, "lng": -70.3015},
    "ano_diseno": "1986",
    "anos_construccion": "1987-1988",
    "ano_inauguracion": "1988",
    "estilos": ["Postmodernismo Funcional"],
    "programa": ["Transporte"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Nodo neurálgico del transporte terrestre con Tacna y Bolivia. Cuenta con naves techadas de acero, andenes en espina de pescado y amplia galería de servicios comerciales.",
    "fuente_url": "https://www.municipalidaddearica.cl",
    "materiales_principales": ["Cerchas metálicas", "Albañilería", "Policarbonato"]
  },
  {
    "id": "terminal-terrestre-nacional-arica",
    "nombre_proyecto": "Terminal Terrestre Nacional de Arica",
    "arquitecto": "Municipalidad de Arica / Concesiones MOP",
    "arquitecto_principal": "Oficina Técnica Municipal",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Diego Portales 1002, Arica",
    "coordenadas": {"lat": -18.4715, "lng": -70.3005},
    "ano_diseno": "1990",
    "anos_construccion": "1991-1992",
    "ano_inauguracion": "1992",
    "estilos": ["Racionalismo Tardío"],
    "programa": ["Transporte"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Edificio terminal de conexión interurbana con el resto del país, proyectado con marquesina continua de hormigón armado y circulaciones directas.",
    "fuente_url": "https://www.municipalidaddearica.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio templado", "Acero pintado"]
  },
  {
    "id": "edificio-contraloria-regional-arica",
    "nombre_proyecto": "Edificio Contraloría Regional de Arica y Parinacota",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Arturo Prat 305, Arica",
    "coordenadas": {"lat": -18.4786, "lng": -70.3179},
    "ano_diseno": "2010",
    "anos_construccion": "2011-2012",
    "ano_inauguracion": "2012",
    "estilos": ["Contemporáneo Institucional"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Inmueble con certificación de eficiencia energética, provisto de celosías horizontales que protegen los puestos de trabajo y patio interior con vegetación nativa.",
    "fuente_url": "https://www.contraloria.cl",
    "materiales_principales": ["Hormigón arquitectónico", "Muro cortina DVH", "Parasoles de aluminio"]
  },
  {
    "id": "terminal-aereo-chacalluta-ampliacion",
    "nombre_proyecto": "Terminal Aéreo Chacalluta (Ampliación y Modernización)",
    "arquitecto": "Dirección de Aeropuertos MOP / Amunátegui Barreau Arquitectos",
    "arquitecto_principal": "Dirección de Aeropuertos MOP",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Aeropuerto Internacional Chacalluta, Arica",
    "coordenadas": {"lat": -18.3485, "lng": -70.3386},
    "ano_diseno": "2012",
    "anos_construccion": "2013-2014",
    "ano_inauguracion": "2014",
    "estilos": ["Contemporáneo", "Infraestructura de Transporte"],
    "programa": ["Transporte"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Ampliación del principal aeropuerto regional con puentes de embarque vidriados, cubierta ondulada que dialoga con los médanos costeros y eficiencia lumínica natural.",
    "fuente_url": "https://www.aeropuertochacalluta.cl",
    "materiales_principales": ["Estructura metálica tubular", "Aluminio compuesto", "Vidrio de control solar"]
  },

  # 5. Casas Contemporáneas, Refugios y Arquitectura del Valle (16)
  {
    "id": "casa-azapa-i",
    "nombre_proyecto": "Casa Azapa I",
    "arquitecto": "Arquitectos Locales de Arica",
    "arquitecto_principal": "Taller de Arquitectura Azapa",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Km 8 Valle de Azapa, Arica",
    "coordenadas": {"lat": -18.5140, "lng": -70.2450},
    "ano_diseno": "2004",
    "anos_construccion": "2004-2005",
    "ano_inauguracion": "2005",
    "estilos": ["Vernáculo Contemporáneo"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Vivienda unifamiliar rural estructurada mediante muros de adobe estabilizado y pérgolas de caña que generan microclimas frescos bajo la sombra de olivos.",
    "fuente_url": "https://www.arquitour.com",
    "materiales_principales": ["Adobe estabilizado", "Madera rústica", "Caña brava"]
  },
  {
    "id": "casa-azapa-ii",
    "nombre_proyecto": "Casa Azapa II (Estructuras de Sombra)",
    "arquitecto": "Estudio Regional Norte",
    "arquitecto_principal": "Arquitectos del Desierto",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Km 14 Valle de Azapa, Arica",
    "coordenadas": {"lat": -18.5220, "lng": -70.1980},
    "ano_diseno": "2011",
    "anos_construccion": "2012",
    "ano_inauguracion": "2012",
    "estilos": ["Contemporáneo", "Bioclimático"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Proyecto residencial concebido a partir de una gran doble cubierta ventilada que flota sobre volúmenes habitables de albañilería, favoreciendo corrientes térmicas naturales.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Acero liviano", "Malla sombreante", "Albañilería a la vista"]
  },
  {
    "id": "refugio-en-lluta",
    "nombre_proyecto": "Refugio en Lluta",
    "arquitecto": "Taller Agrícola y Paisaje",
    "arquitecto_principal": "Equipo de Arquitectura del Valle",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Lluta Km 22, Arica",
    "coordenadas": {"lat": -18.4200, "lng": -70.1800},
    "ano_diseno": "2014",
    "anos_construccion": "2015",
    "ano_inauguracion": "2015",
    "estilos": ["Arquitectura Agrícola Contemporánea"],
    "programa": ["Residencial", "Agrícola"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Refugio agrícola modular construido en madera y fardos de totora locales, orientado para capturar la brisa del valle y proteger de las tolvaneras vespertinas.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Madera de pino impregnado", "Totora trenzada", "Chapa ondulada"]
  },
  {
    "id": "casa-gallinazo-azapa",
    "nombre_proyecto": "Casa Gallinazo",
    "arquitecto": "Estudio Bioclimático del Norte",
    "arquitecto_principal": "Arquitectos Asociados Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Gallinazo, Valle de Azapa, Arica",
    "coordenadas": {"lat": -18.5280, "lng": -70.1650},
    "ano_diseno": "2017",
    "anos_construccion": "2017-2018",
    "ano_inauguracion": "2018",
    "estilos": ["Bioclimático de Desierto"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Residencia de bajo impacto ambiental con muros de tapial de tierra cruda apisonada, patios de ventilación y reutilización de aguas grises para riego.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Tierra compactada (tapial)", "Madera de chañar", "Vidrio"]
  },
  {
    "id": "casa-el-pedregal-azapa",
    "nombre_proyecto": "Casa El Pedregal",
    "arquitecto": "Taller de Arquitectura y Paisaje",
    "arquitecto_principal": "Arquitectos Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector El Pedregal, Azapa, Arica",
    "coordenadas": {"lat": -18.5170, "lng": -70.2310},
    "ano_diseno": "2010",
    "anos_construccion": "2011",
    "ano_inauguracion": "2011",
    "estilos": ["Contemporáneo", "Piedra Local"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Vivienda aterrazada que aprovecha la piedra extraída en el despeje de la parcela para erigir muros ciclópeos que dialogan con el fondo de los cerros color ocre.",
    "fuente_url": "https://www.plataformaarquitectura.cl",
    "materiales_principales": ["Piedra local ciclópea", "Hormigón visto", "Ventanas correderas"]
  },
  {
    "id": "cabanas-turisticas-socoroma",
    "nombre_proyecto": "Cabañas Turísticas Socoroma",
    "arquitecto": "Comunidad Indígena de Socoroma / CONADI",
    "arquitecto_principal": "Arquitectos Comunitarios",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Andenes de Socoroma, Putre",
    "coordenadas": {"lat": -18.2630, "lng": -69.5860},
    "ano_diseno": "2015",
    "anos_construccion": "2015-2016",
    "ano_inauguracion": "2016",
    "estilos": ["Integración Paisajística", "Eco-turismo Andino"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Conjunto de cabañas de hospedaje rural mimetizadas con los bancales precolombinos de alfalfa y orégano, utilizando mampostería de toba volcánica y techos de barro.",
    "fuente_url": "https://rutadelasmisiones.cl",
    "materiales_principales": ["Piedra volcánica", "Barro y paja brava", "Madera nativa"]
  },
  {
    "id": "casa-campo-las-maitenas-azapa",
    "nombre_proyecto": "Casa de Campo Las Maitenas",
    "arquitecto": "Oficina de Arquitectura Azapa",
    "arquitecto_principal": "Arquitectos del Valle",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Km 5 Valle de Azapa, Arica",
    "coordenadas": {"lat": -18.5110, "lng": -70.2620},
    "ano_diseno": "2007",
    "anos_construccion": "2008",
    "ano_inauguracion": "2008",
    "estilos": ["Neovernáculo"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Casona campestre estructurada en torno a una crujía de corredores exteriores con pilares de pino oregón y tejas coloniales recuperadas.",
    "fuente_url": "https://www.arquitour.com",
    "materiales_principales": ["Albañilería", "Teja de arcilla", "Madera de pino oregón"]
  },
  {
    "id": "refugio-en-codpa",
    "nombre_proyecto": "Refugio en Codpa",
    "arquitecto": "Taller Tierra Viva",
    "arquitecto_principal": "Equipo de Bioconstrucción",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Codpa, Camarones",
    "coordenadas": {"lat": -18.8340, "lng": -69.7400},
    "ano_diseno": "2016",
    "anos_construccion": "2017",
    "ano_inauguracion": "2017",
    "estilos": ["Bioconstrucción", "Tierra Compactada"],
    "programa": ["Residencial"],
    "ciudad": "Camarones",
    "pais": "Chile",
    "descripcion": "Refugio vinícola autosuficiente para la elaboración artesanal del vino Pintatani, edificado íntegramente con tierra local estabilizada y carpintería de eucalipto.",
    "fuente_url": "https://www.municamarones.cl",
    "materiales_principales": ["Tierra apisonada", "Caña brava", "Madera"]
  },
  {
    "id": "casa-valle-de-lluta",
    "nombre_proyecto": "Casa del Valle de Lluta",
    "arquitecto": "Arquitectura del Norte",
    "arquitecto_principal": "Arquitectos Asociados",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Lluta Km 15, Arica",
    "coordenadas": {"lat": -18.4250, "lng": -70.2200},
    "ano_diseno": "2013",
    "anos_construccion": "2014",
    "ano_inauguracion": "2014",
    "estilos": ["Contemporáneo"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Vivienda moderna levantada sobre zócalos de mampostería de piedra para protegerse de las crecidas esporádicas del río Lluta, con amplias terrazas sombreadas.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Piedra de río", "Hormigón armado", "Madera tratada"]
  },
  {
    "id": "cabanas-altiplano-putre",
    "nombre_proyecto": "Cabañas del Altiplano Putre",
    "arquitecto": "Equipo de Turismo Sustentable",
    "arquitecto_principal": "Arquitectura Andina",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Camino Las Vicuñas s/n, Putre",
    "coordenadas": {"lat": -18.1990, "lng": -69.5620},
    "ano_diseno": "2009",
    "anos_construccion": "2010",
    "ano_inauguracion": "2010",
    "estilos": ["Vernáculo Altiplánico"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Módulos de alojamiento diseñados con muros dobles de quincha y piedra volcánica que almacenan el calor solar diurno para liberarlo en las gélidas noches de altura.",
    "fuente_url": "https://www.sernatur.cl",
    "materiales_principales": ["Piedra volcánica", "Quincha", "Paja brava"]
  },
  {
    "id": "casa-mirador-del-morro-arica",
    "nombre_proyecto": "Casa Mirador del Morro",
    "arquitecto": "Estudio Assadi & Asociados Norte",
    "arquitecto_principal": "Arquitectura Costera",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Faldas del Morro, Calle Sotomayor alta, Arica",
    "coordenadas": {"lat": -18.4810, "lng": -70.3230},
    "ano_diseno": "2002",
    "anos_construccion": "2003",
    "ano_inauguracion": "2003",
    "estilos": ["Minimalismo Costero"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Volumen cúbico blanco empotrado en la ladera rocosa del Morro con ventanales de piso a cielo que enmarcan la vista panorámica del puerto y la bahía.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón blanco", "Vidrio templado", "Acero inoxidable"]
  },
  {
    "id": "casa-panamericana-north-arica",
    "nombre_proyecto": "Casa Panamericana North",
    "arquitecto": "Taller del Desierto",
    "arquitecto_principal": "Arquitectos Arica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Acceso Norte, Ruta 5, Arica",
    "coordenadas": {"lat": -18.4350, "lng": -70.2980},
    "ano_diseno": "2012",
    "anos_construccion": "2013",
    "ano_inauguracion": "2013",
    "estilos": ["Arquitectura del Desierto"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Vivienda suburbana que combina patios ingleses excavados para generar sombra y frescor, y chimeneas solares que inducen ventilación convectiva continua.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Bloques de cemento celular", "Madera", "Grava volcánica"]
  },
  {
    "id": "casa-brisas-chinchorro-arica",
    "nombre_proyecto": "Casa Las Brisas de Chinchorro",
    "arquitecto": "Estudio Costero Arica",
    "arquitecto_principal": "Arquitectura de Playa",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Las Dunas, Playa Chinchorro, Arica",
    "coordenadas": {"lat": -18.4520, "lng": -70.3060},
    "ano_diseno": "2008",
    "anos_construccion": "2009",
    "ano_inauguracion": "2009",
    "estilos": ["Costero Moderno"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Residencia de playa con amplios aleros de madera para repeler la insolación directa, terrazas de madera teca y cerramientos móviles de lamas orientables.",
    "fuente_url": "https://www.plataformaarquitectura.cl",
    "materiales_principales": ["Madera tratada", "Hormigón visto", "Aluminio marino"]
  },
  {
    "id": "cabanas-parque-lauca-putre",
    "nombre_proyecto": "Cabañas de Guardaparques y Visitantes Parque Lauca",
    "arquitecto": "Corporación Nacional Forestal (CONAF)",
    "arquitecto_principal": "Departamento de Infraestructura CONAF",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Las Cuevas, Parque Nacional Lauca, Putre",
    "coordenadas": {"lat": -18.1750, "lng": -69.3600},
    "ano_diseno": "2003",
    "anos_construccion": "2004",
    "ano_inauguracion": "2004",
    "estilos": ["Infraestructura en Ecosistema Frágil"],
    "programa": ["Infraestructura de Parque / Refugio"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Refugios bioclimáticos de alta montaña a 4.500 msnm con energía solar fotovoltaica, captación térmica de muro masivo y reciclaje de agua para resguardar la flora y fauna altiplánica.",
    "fuente_url": "https://www.conaf.cl",
    "materiales_principales": ["Piedra andina", "Madera termo-tratada", "Placas de policarbonato alveolar"]
  },
  {
    "id": "casa-en-chinisey-azapa",
    "nombre_proyecto": "Casa en Chinisey",
    "arquitecto": "Taller Regional",
    "arquitecto_principal": "Arquitectos de Azapa",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Chinisey, Valle de Azapa Km 18, Arica",
    "coordenadas": {"lat": -18.5250, "lng": -70.1500},
    "ano_diseno": "2018",
    "anos_construccion": "2019",
    "ano_inauguracion": "2019",
    "estilos": ["Contemporáneo"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Vivienda compacta levantada con estructuras de acero ligero y paneles aislantes térmicos revestidos en cañizo tradicional del valle.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Estructura de acero liviano (Metalcon)", "Cañizo", "Vidrio"]
  },
  {
    "id": "casa-saucache-arica",
    "nombre_proyecto": "Casa Saucache",
    "arquitecto": "Estudio Urbano Arica",
    "arquitecto_principal": "Arquitectos Urbanos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Barrio Saucache, Arica",
    "coordenadas": {"lat": -18.4910, "lng": -70.3010},
    "ano_diseno": "2006",
    "anos_construccion": "2007",
    "ano_inauguracion": "2007",
    "estilos": ["Residencial Moderno"],
    "programa": ["Residencial"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Casa de ciudad que reinterpreta el patio central colonial mediante un claustro moderno ajardinado alrededor del cual se organizan las estancias diurnas y nocturnas.",
    "fuente_url": "https://www.arquitour.com",
    "materiales_principales": ["Albañilería confinada", "Vigas de madera laminada", "Hormigón"]
  },

  # 6. Archivos del Patrimonio Precolombino y Etnográfico (Espacio Vernáculo) (20)
  {
    "id": "pukara-de-san-lorenzo-azapa",
    "nombre_proyecto": "Pukara de San Lorenzo",
    "arquitecto": "Cultura Tiwanaku / Cabuza / Arica",
    "arquitecto_principal": "Pobladores Originarios Andinos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "San Lorenzo Km 10, Valle de Azapa, Arica",
    "coordenadas": {"lat": -18.5160, "lng": -70.2350},
    "ano_diseno": "Siglo XII",
    "anos_construccion": "1100-1200",
    "ano_inauguracion": "Siglo XII",
    "estilos": ["Arquitectura Precolombina Fortificada"],
    "programa": ["Arqueológico / Fortificación"],
    "ciudad": "Arica",
    "pais": "Chile",
    "descripcion": "Asentamiento fortificado erigido en la cumbre de un espolón que domina el valle agrícola de Azapa. Presenta recintos circulares y rectangulares con muros dobles de piedra calzada y mortero de arcilla.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra de cerro", "Mortero de barro", "Troncos de algarrobo"]
  },
  {
    "id": "pukara-de-copaquilla",
    "nombre_proyecto": "Pukara de Copaquilla",
    "arquitecto": "Señoríos Andinos Regionales",
    "arquitecto_principal": "Constructores Prehispánicos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta 11-CH Km 100, Precordillera de Putre",
    "coordenadas": {"lat": -18.3970, "lng": -69.6450},
    "ano_diseno": "Siglo XII",
    "anos_construccion": "1150-1250",
    "ano_inauguracion": "Siglo XII",
    "estilos": ["Pukara Andino Prehispánico"],
    "programa": ["Arqueológico / Defensivo"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Monumento Histórico Nacional ubicado al borde de un precipicio de 150 metros sobre la quebrada de Copaquilla. Conserva una muralla defensiva doble con parapetos y vanos trapezoidales.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra pircada en seco", "Roca madre", "Tierra compacta"]
  },
  {
    "id": "pukara-de-belen",
    "nombre_proyecto": "Pukara de Belén (Incuyo)",
    "arquitecto": "Cultura Pre-Inca y Tawantinsuyu",
    "arquitecto_principal": "Constructores Andinos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Cerro Huaihuarani / Incuyo, Belén, Putre",
    "coordenadas": {"lat": -18.4720, "lng": -69.5220},
    "ano_diseno": "Siglo XIV",
    "anos_construccion": "1350-1450",
    "ano_inauguracion": "Siglo XIV",
    "estilos": ["Arquitectura Defensiva Andina"],
    "programa": ["Arqueológico / Asentamiento"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Complejo habitacional y militar con más de 120 recintos aterrazados escalonados en la roca, silos de granos (colcas) y atalayas de vigilancia hacia las quebradas fértiles.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra canteada", "Piedra pómez", "Arcilla roja"]
  },
  {
    "id": "tambo-de-chungara",
    "nombre_proyecto": "Tambo de Chungará (Qhapaq Ñan)",
    "arquitecto": "Ingenieros del Imperio Incaico (Tawantinsuyu)",
    "arquitecto_principal": "Incas",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta Incaica, orillas del Lago Chungará, Putre",
    "coordenadas": {"lat": -18.2580, "lng": -69.1720},
    "ano_diseno": "Siglo XV",
    "anos_construccion": "1470-1500",
    "ano_inauguracion": "Siglo XV",
    "estilos": ["Arquitectura Imperial Inca", "Qhapaq Ñan"],
    "programa": ["Transporte / Almacén Arqueológico"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Estación de relevo del Camino del Inca a 4.550 msnm para chasquis y caravanas de llamas entre el lago Titicaca y la costa del Pacífico. Recintos ortogonales de piedra con hornacinas trapezoidales.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra volcánica labrada", "Barro arcilloso", "Paja brava"]
  },
  {
    "id": "aldea-de-zapahuira",
    "nombre_proyecto": "Aldea de Zapahuira y Chullpas Funerarias",
    "arquitecto": "Señoríos Altiplánicos Preincaicos",
    "arquitecto_principal": "Constructores Aymara",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Quebrada de Zapahuira, Ruta 11-CH Km 95, Putre",
    "coordenadas": {"lat": -18.3510, "lng": -69.6050},
    "ano_diseno": "Siglo XIV",
    "anos_construccion": "1300-1400",
    "ano_inauguracion": "Siglo XIV",
    "estilos": ["Arquitectura Mortuoria y Habitacional Andina"],
    "programa": ["Arqueológico / Funerario"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Conjunto de chullpas (torres funerarias de piedra y adobe) de planta circular y rectangular junto a recintos habitacionales y colcas para la preservación de semillas en clima seco.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Adobe prehispánico", "Piedra laja", "Madera de queñoa"]
  },
  {
    "id": "pukara-de-saxamar",
    "nombre_proyecto": "Pukara de Saxamar",
    "arquitecto": "Señoríos Andinos de la Precordillera",
    "arquitecto_principal": "Constructores Andinos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Saxamar, Putre",
    "coordenadas": {"lat": -18.5300, "lng": -69.5700},
    "ano_diseno": "Siglo XII",
    "anos_construccion": "1150-1200",
    "ano_inauguracion": "Siglo XII",
    "estilos": ["Pukara Andino"],
    "programa": ["Arqueológico / Defensivo"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Fortificación de valle sobre promontorio escarpado, con muros concéntricos de contención de piedra seca que protegían las áreas agrícolas y habitacionales.",
    "fuente_url": "https://rutadelasmisiones.cl",
    "materiales_principales": ["Piedra basalto", "Tierra", "Gravas"]
  },
  {
    "id": "inkawasi-de-caquena",
    "nombre_proyecto": "Inkawasi de Caquena (Tambo Incaico)",
    "arquitecto": "Ingenieros del Imperio Incaico",
    "arquitecto_principal": "Tawantinsuyu",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Bofedal de Caquena, General Lagos",
    "coordenadas": {"lat": -18.0620, "lng": -69.2150},
    "ano_diseno": "Siglo XV",
    "anos_construccion": "1480-1500",
    "ano_inauguracion": "Siglo XV",
    "estilos": ["Arquitectura Imperial Incaica"],
    "programa": ["Arqueológico / Tambo"],
    "ciudad": "General Lagos",
    "pais": "Chile",
    "descripcion": "Complejo administrativo estatal incaico emplazado en la zona ganadera más rica en camélidos del altiplano norte. Destacan sus muros de piedra con aparejo almohadillado.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra volcánica almohadillada", "Mortero de calicanto inca", "Paja"]
  },
  {
    "id": "aldea-de-cerro-blanco-camarones",
    "nombre_proyecto": "Aldea de Cerro Blanco",
    "arquitecto": "Pobladores de Quebradas Tarapaqueñas",
    "arquitecto_principal": "Comunidades Andinas",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Cerro Blanco, Camarones",
    "coordenadas": {"lat": -18.9800, "lng": -69.8200},
    "ano_diseno": "Siglo XII",
    "anos_construccion": "1100-1250",
    "ano_inauguracion": "Siglo XII",
    "estilos": ["Arquitectura Habitacional de Piedra"],
    "programa": ["Arqueológico"],
    "ciudad": "Camarones",
    "pais": "Chile",
    "descripcion": "Aldea de piedra construida sobre laderas áridas con recintos circulares semienterrados para protección del viento y conservación de calor ambiental.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra arenisca", "Barro", "Queñoa"]
  },
  {
    "id": "chullpas-de-guacollo",
    "nombre_proyecto": "Chullpas de Guacollo",
    "arquitecto": "Cultura Aymara Carangas / Pacajes",
    "arquitecto_principal": "Maestros Canteros Aymara",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Meseta de Guacollo, General Lagos",
    "coordenadas": {"lat": -17.8100, "lng": -69.4100},
    "ano_diseno": "Siglo XV",
    "anos_construccion": "1400-1500",
    "ano_inauguracion": "Siglo XV",
    "estilos": ["Arquitectura Funeraria Andina"],
    "programa": ["Arqueológico / Funerario"],
    "ciudad": "General Lagos",
    "pais": "Chile",
    "descripcion": "Torres funerarias de noble factura en piedra canteada levantadas para honrar a los mallkus (líderes andinos). Presentan falsa cúpula por aproximación de hiladas.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Bloques de toba volcánica", "Paja brava", "Tierra greda"]
  },
  {
    "id": "aldea-caleta-camarones-chinchorro",
    "nombre_proyecto": "Aldea de Caleta Camarones (Sitio Arcaico Chinchorro)",
    "arquitecto": "Cultura Chinchorro",
    "arquitecto_principal": "Pescadores Arcaicos Chinchorro",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Desembocadura Río Camarones, Caleta Camarones",
    "coordenadas": {"lat": -19.1950, "lng": -70.2650},
    "ano_diseno": "5000 a.C.",
    "anos_construccion": "5000 a.C. - 2000 a.C.",
    "ano_inauguracion": "5000 a.C.",
    "estilos": ["Arquitectura Vernácula Arcaica", "Patrimonio Mundial UNESCO"],
    "programa": ["Arqueológico / Asentamiento Arcaico"],
    "ciudad": "Camarones",
    "pais": "Chile",
    "descripcion": "Patrimonio Mundial de la Humanidad UNESCO. Sitio de los asentamientos y momificación artificial más antiguos del planeta, con refugios semicirculares de postes de madera de chañar, costillas de ballena y esteras de totora.",
    "fuente_url": "https://whc.unesco.org/en/list/1634",
    "materiales_principales": ["Postes de chañar", "Hueso de cetáceo", "Esteras de totora", "Pieles de lobo marino"]
  },
  {
    "id": "tambo-de-huaytane",
    "nombre_proyecto": "Tambo de Huaytane (Qhapaq Ñan)",
    "arquitecto": "Incas",
    "arquitecto_principal": "Tawantinsuyu",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta Altiplánica, General Lagos",
    "coordenadas": {"lat": -17.7500, "lng": -69.3800},
    "ano_diseno": "Siglo XV",
    "anos_construccion": "1480-1510",
    "ano_inauguracion": "Siglo XV",
    "estilos": ["Qhapaq Ñan", "Incaico"],
    "programa": ["Arqueológico / Transporte"],
    "ciudad": "General Lagos",
    "pais": "Chile",
    "descripcion": "Punto de abastecimiento sobre el tramo transversal del camino incaico que unía la meseta boliviana con los valles occidentales. Preserva kallankas (grandes salas comunales) de piedra.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra volcánica", "Argamasa de barro", "Vigas de queñoa"]
  },
  {
    "id": "chullpas-de-tacora",
    "nombre_proyecto": "Chullpas de Tacora",
    "arquitecto": "Pobladores Aymara de Tacora",
    "arquitecto_principal": "Constructores Altiplánicos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Faldas del Volcán Tacora, General Lagos",
    "coordenadas": {"lat": -17.7200, "lng": -69.7700},
    "ano_diseno": "Siglo XV",
    "anos_construccion": "1450-1520",
    "ano_inauguracion": "Siglo XV",
    "estilos": ["Arquitectura Funeraria Altiplánica"],
    "programa": ["Arqueológico / Funerario"],
    "ciudad": "General Lagos",
    "pais": "Chile",
    "descripcion": "Monumentos funerarios cilíndricos erigidos a más de 4.200 msnm con bloques de piedra volcánica porosa y cúpulas de adobe resistentes al hielo permanente.",
    "fuente_url": "https://rutadelasmisiones.cl",
    "materiales_principales": ["Piedra volcánica", "Adobe resistente a heladas", "Paja"]
  },
  {
    "id": "casas-de-piedra-ancuta",
    "nombre_proyecto": "Casas de Piedra de Ancuta",
    "arquitecto": "Pastores Aymara Altiplánicos",
    "arquitecto_principal": "Comunidad Pastoril",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Bofedal de Ancuta, cerca de Guallatire, Putre",
    "coordenadas": {"lat": -18.4600, "lng": -69.2100},
    "ano_diseno": "Siglo XIX",
    "anos_construccion": "Siglo XIX",
    "ano_inauguracion": "1860",
    "estilos": ["Arquitectura Ganadera de Bofedal"],
    "programa": ["Vernáculo / Ganadero"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Conjunto de estancias ganaderas tradicionales de alpaca y llama. Viviendas de piedra de baja altura con corrales circulares cerrados (pircas) estratégicamente ubicados en el bofedal.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra laja", "Paja brava", "Cuero crudo"]
  },
  {
    "id": "estancia-altiplanica-chucuyo",
    "nombre_proyecto": "Estancia Altiplánica Chucuyo",
    "arquitecto": "Pastores Aymara",
    "arquitecto_principal": "Comunidad Chucuyo",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Bofedal de Chucuyo, Parque Nacional Lauca, Putre",
    "coordenadas": {"lat": -18.2350, "lng": -69.2820},
    "ano_diseno": "Siglo XIX",
    "anos_construccion": "Siglo XIX",
    "ano_inauguracion": "1880",
    "estilos": ["Pastoral Andino"],
    "programa": ["Vernáculo / Ganadero"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Poblado tradicional de pastores trashumantes situado entre los volcanes Pomerape y Parinacota, célebre por sus tejedurías de lana de vicuña y sus casas de piedra encalada.",
    "fuente_url": "https://rutadelasmisiones.cl",
    "materiales_principales": ["Piedra encalada", "Tierra greda", "Paja de páramo"]
  },
  {
    "id": "aldea-vernacula-de-parinacota",
    "nombre_proyecto": "Aldea Vernácula de Parinacota",
    "arquitecto": "Comunidad Tradicional Aymara",
    "arquitecto_principal": "Comunidad Aymara",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Poblado de Parinacota, Parque Nacional Lauca, Putre",
    "coordenadas": {"lat": -18.2000, "lng": -69.2700},
    "ano_diseno": "Siglo XVIII",
    "anos_construccion": "Siglos XVIII-XIX",
    "ano_inauguracion": "1780",
    "estilos": ["Trama Urbana Andina Tradicional"],
    "programa": ["Urbanismo / Vernáculo"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Zona Típica protegida por el Consejo de Monumentos Nacionales. Trama de callejuelas estrechas encaladas en blanco orientadas para cortar el viento cordillerano y converger en la plaza de la iglesia.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra volcánica blanca", "Barro encalado", "Madera de queñoa"]
  },
  {
    "id": "poblado-historico-de-belen",
    "nombre_proyecto": "Poblado Histórico de Belén",
    "arquitecto": "Colonizadores Españoles y Comunidad Aymara",
    "arquitecto_principal": "Comunidad Andina",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Poblado de Belén, Precordillera de Putre",
    "coordenadas": {"lat": -18.4670, "lng": -69.5150},
    "ano_diseno": "1580",
    "anos_construccion": "Siglo XVI",
    "ano_inauguracion": "1620",
    "estilos": ["Trama Urbana Colonial e Incaica"],
    "programa": ["Urbanismo Patrimonial"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "El único pueblo fundado por los españoles en la sierra de Arica en 1625, superpuesto sobre terrazas agrícolas incaicas con dos templos tutelares (San Santiago y Nuestra Señora del Carmen).",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra canteada", "Adobe", "Madera de queñoa"]
  },
  {
    "id": "aldea-de-humapalca",
    "nombre_proyecto": "Aldea de Humapalca",
    "arquitecto": "Comunidad Ganadera Altiplánica",
    "arquitecto_principal": "Comunidad local",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Humapalca, Comuna de General Lagos",
    "coordenadas": {"lat": -17.6800, "lng": -69.6200},
    "ano_diseno": "Siglo XIX",
    "anos_construccion": "Siglo XIX",
    "ano_inauguracion": "1890",
    "estilos": ["Asentamiento Ganadero Altiplánico"],
    "programa": ["Vernáculo"],
    "ciudad": "General Lagos",
    "pais": "Chile",
    "descripcion": "Asentamiento pastoral próximo a los bofedales de altura, con viviendas de piedra volcánica asentada en barro y techos de paja amarrados con tientos de cuero de llama.",
    "fuente_url": "https://rutadelasmisiones.cl",
    "materiales_principales": ["Piedra volcánica", "Barro", "Paja brava", "Cuero"]
  },
  {
    "id": "casas-de-piedra-de-chilcaya",
    "nombre_proyecto": "Casas de Piedra de Chilcaya (Salar de Surire)",
    "arquitecto": "Mineros del Bórax y Pastores",
    "arquitecto_principal": "Constructores Tradicionales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Borde sur del Salar de Surire, Putre",
    "coordenadas": {"lat": -18.9100, "lng": -69.0800},
    "ano_diseno": "Siglo XIX",
    "anos_construccion": "Siglo XIX",
    "ano_inauguracion": "1895",
    "estilos": ["Arquitectura Minero-Pastoral de Salar"],
    "programa": ["Vernáculo / Industrial Histórico"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Construcciones rústicas de piedra y caliza ubicadas a 4.250 msnm en el Salar de Surire, vinculadas a la histórica explotación del bórax y a la crianza de camélidos.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra de salar", "Cal", "Chapa metálica"]
  },
  {
    "id": "estancia-guallatire",
    "nombre_proyecto": "Estancia Guallatire",
    "arquitecto": "Comunidad Aymara de Guallatire",
    "arquitecto_principal": "Comunidad local",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Guallatire, Reserva Las Vicuñas, Putre",
    "coordenadas": {"lat": -18.5100, "lng": -69.1600},
    "ano_diseno": "Siglo XIX",
    "anos_construccion": "Siglo XIX",
    "ano_inauguracion": "1875",
    "estilos": ["Pastoral Andino"],
    "programa": ["Vernáculo"],
    "ciudad": "Putre",
    "pais": "Chile",
    "descripcion": "Conjunto tradicional pastoral con viviendas bajas, corrales de piedra pircada y secaderos de carne al sol (charqui) en la inmensidad del altiplano volcánico.",
    "fuente_url": "https://rutadelasmisiones.cl",
    "materiales_principales": ["Piedra", "Paja brava", "Barro"]
  },
  {
    "id": "poblado-historico-de-codpa",
    "nombre_proyecto": "Poblado Histórico de Codpa",
    "arquitecto": "Comunidad Andina y Doctrinares Coloniales",
    "arquitecto_principal": "Comunidad de Codpa",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Codpa, Camarones",
    "coordenadas": {"lat": -18.8320, "lng": -69.7440},
    "ano_diseno": "1620",
    "anos_construccion": "Siglos XVII-XIX",
    "ano_inauguracion": "1650",
    "estilos": ["Traza Colonial de Valle Andino"],
    "programa": ["Urbanismo Patrimonial"],
    "ciudad": "Camarones",
    "pais": "Chile",
    "descripcion": "Pueblo oasis encajonado en la quebrada de Vitor, con casas coloniales de adobe encalado, lagares tradicionales para pisar uvas y canales de regadío incaicos en continuo funcionamiento.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Adobe", "Piedra", "Madera nativa", "Teja de barro"]
  }
]

with open("data_arica_part1.json", "r", encoding="utf-8") as f:
  p1 = json.load(f)

total_arica = p1 + obras_sec3_6
print(f"Total works in Arica: {len(total_arica)}")

with open("data_arica_100.json", "w", encoding="utf-8") as f:
  json.dump(total_arica, f, ensure_ascii=False, indent=2)

print("Saved data_arica_100.json successfully!")
