#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Data generator for Región de Tarapacá - Part 2 (Sections 4, 5, 6, 7 = 53 works)"""
import json

obras_tarapaca_p2 = [
  # 4. Vivienda Social, Modernismo Urbano y Equipamiento (16)
  {
    "id": "viviendas-quinta-monroy-iquique",
    "nombre_proyecto": "Viviendas Sociales Quinta Monroy",
    "arquitecto": "ELEMENTAL / Alejandro Aravena",
    "arquitecto_principal": "Alejandro Aravena",
    "colaboradores": "Alfonso Montero, Tomás Cortese, Emilio de la Cerda",
    "ano_pritzker": 2016,
    "fotografia_url": "",
    "direccion": "Avenida Pedro Prado con Céspedes y González, Iquique",
    "coordenadas": {"lat": -20.2292, "lng": -70.1384},
    "ano_diseno": "2003",
    "anos_construccion": "2003-2004",
    "ano_inauguracion": "2004",
    "estilos": ["Incrementalismo", "Vivienda Social Contemporánea"],
    "programa": ["Vivienda"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Obra icónica mundial que revolucionó el diseño de la vivienda social y consagró el concepto de vivienda incremental: el Estado construye 'la mitad difícil' (estructura de hormigón, cocina, baño y escaleras) y cada familia autoconstruye y personaliza la otra mitad en el tiempo.",
    "fuente_url": "https://www.elementalchile.cl/proyectos/quinta-monroy/",
    "materiales_principales": ["Bloque de hormigón celular", "Losa de hormigón armado", "Madera", "Estructura metálica"]
  },
  {
    "id": "poblacion-ex-estadio-iquique",
    "nombre_proyecto": "Población Ex-Estadio",
    "arquitecto": "Corporación de la Vivienda (CORVI)",
    "arquitecto_principal": "Equipo de Arquitectura CORVI",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Ex Estadio Cavancha, Iquique",
    "coordenadas": {"lat": -20.2310, "lng": -70.1450},
    "ano_diseno": "1958",
    "anos_construccion": "1959-1960",
    "ano_inauguracion": "1960",
    "estilos": ["Racionalismo Moderno", "Vivienda Social"],
    "programa": ["Vivienda"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Conjunto pionero de vivienda obrera en Iquique impulsado por la CORVI para relocalizar familias de los campamentos salitreros hacia la costa.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Albañilería confinada", "Losa de hormigón", "Celosías"]
  },
  {
    "id": "conjunto-habitacional-chipana-iquique",
    "nombre_proyecto": "Conjunto Habitacional Chipana",
    "arquitecto": "Corporación de la Vivienda y Urbanismo (CORVU)",
    "arquitecto_principal": "Equipo Técnico CORVU",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Chipana con Rancagua, Iquique",
    "coordenadas": {"lat": -20.2580, "lng": -70.1340},
    "ano_diseno": "1976",
    "anos_construccion": "1977-1978",
    "ano_inauguracion": "1978",
    "estilos": ["Racionalismo Tardío"],
    "programa": ["Vivienda"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Extensión sur urbana de Iquique conformada por bloques repetitivos de cuatro pisos con balcones protegidos del viento sur costero.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón armado", "Bloques de cemento", "Hierro"]
  },
  {
    "id": "edificio-cavancha-iquique",
    "nombre_proyecto": "Edificio Cavancha",
    "arquitecto": "Estudio Moderno del Norte",
    "arquitecto_principal": "Arquitectos Asociados Iquique",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Arturo Prat frente a Playa Cavancha, Iquique",
    "coordenadas": {"lat": -20.2280, "lng": -70.1490},
    "ano_diseno": "1973",
    "anos_construccion": "1974-1975",
    "ano_inauguracion": "1975",
    "estilos": ["Movimiento Moderno en la Costa"],
    "programa": ["Residencial"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Uno de los primeros edificios modernos en altura de la costanera de Cavancha, con terrazas continuas y amplias visuales a la rompiente.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio", "Aluminio"]
  },
  {
    "id": "poblacion-ohiggins-iquique",
    "nombre_proyecto": "Población O'Higgins",
    "arquitecto": "CORVI",
    "arquitecto_principal": "Equipo de Arquitectura CORVI",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Centro-Oriente, Iquique",
    "coordenadas": {"lat": -20.2220, "lng": -70.1380},
    "ano_diseno": "1960",
    "anos_construccion": "1961-1962",
    "ano_inauguracion": "1962",
    "estilos": ["Racionalismo"],
    "programa": ["Vivienda"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Urbanización moderna con tipologías de casas pareadas de dos niveles con jardín frontal y ventilación cruzada continua.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Albañilería armada", "Hormigón", "Cubierta metálica"]
  },
  {
    "id": "poblacion-playa-blanca-iquique",
    "nombre_proyecto": "Población Playa Blanca",
    "arquitecto": "Ministerio de la Vivienda y Urbanismo (MINVU)",
    "arquitecto_principal": "MINVU Tarapacá",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Sur de Playa Brava, Iquique",
    "coordenadas": {"lat": -20.2450, "lng": -70.1370},
    "ano_diseno": "1967",
    "anos_construccion": "1968",
    "ano_inauguracion": "1968",
    "estilos": ["Vivienda Social Costera"],
    "programa": ["Vivienda"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Asentamiento residencial frente al borde litoral sur con pasajes peatonales que convergen en plazas de juegos infantiles protegidas.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Bloques de concreto", "Madera tratada", "Zinc"]
  },
  {
    "id": "edificio-cavancha-miramar-iquique",
    "nombre_proyecto": "Edificio Cavancha Miramar",
    "arquitecto": "Constructora Internacional Norte",
    "arquitecto_principal": "Arquitectos Urbanos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Península de Cavancha, Iquique",
    "coordenadas": {"lat": -20.2330, "lng": -70.1480},
    "ano_diseno": "1980",
    "anos_construccion": "1981-1982",
    "ano_inauguracion": "1982",
    "estilos": ["Modernismo Residencial Tardío"],
    "programa": ["Residencial"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Torre residencial en la península rocosa de Cavancha, que inauguró la era de la densificación turística vertical en la bahía histórica.",
    "fuente_url": "https://www.iquique.cl",
    "materiales_principales": ["Hormigón armado sismorresistente", "Vidrio tinteado", "Aluminio"]
  },
  {
    "id": "conjunto-habitacional-jorge-inostroza",
    "nombre_proyecto": "Conjunto Habitacional Jorge Inostroza",
    "arquitecto": "CORVI",
    "arquitecto_principal": "Equipo CORVI",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Norte, Calle Salitrera Victoria, Iquique",
    "coordenadas": {"lat": -20.2050, "lng": -70.1390},
    "ano_diseno": "1970",
    "anos_construccion": "1971-1972",
    "ano_inauguracion": "1972",
    "estilos": ["Racionalismo", "Bloques de Densidad Media"],
    "programa": ["Vivienda"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Bloques de cuatro niveles de escala humana integrados a canchas deportivas y locales comerciales de abastecimiento vecinal.",
    "fuente_url": "https://www.minvu.gob.cl",
    "materiales_principales": ["Hormigón armado", "Albañilería", "Acero"]
  },
  {
    "id": "edificio-aguas-marinas-iquique",
    "nombre_proyecto": "Edificio Aguas Marinas",
    "arquitecto": "Estudio Costero Iquique",
    "arquitecto_principal": "Arquitectos Locales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Playa Brava con Tadeo Haenke, Iquique",
    "coordenadas": {"lat": -20.2420, "lng": -70.1410},
    "ano_diseno": "1984",
    "anos_construccion": "1985",
    "ano_inauguracion": "1985",
    "estilos": ["Postmodernismo Costero"],
    "programa": ["Residencial"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Torre habitacional con fachadas escalonadas orientadas al poniente con balcones aterrazados para el disfrute de las puestas de sol en el océano.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio", "Enlucido cerámico"]
  },
  {
    "id": "liceo-bernardo-ohiggins-iquique",
    "nombre_proyecto": "Liceo Bernardo O'Higgins (Ex Liceo de Hombres)",
    "arquitecto": "Sociedad Constructora de Establecimientos Educacionales (SCEE)",
    "arquitecto_principal": "Equipo de Arquitectura SCEE",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Aníbal Pinto con Orella, Iquique",
    "coordenadas": {"lat": -20.2215, "lng": -70.1500},
    "ano_diseno": "1936",
    "anos_construccion": "1937-1938",
    "ano_inauguracion": "1938",
    "estilos": ["Racionalismo Educacional", "Monumento Nacional"],
    "programa": ["Educación"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Edificio escolar patrimonial concebido según los principios del funcionalismo moderno: amplios ventanales corridos, gimnasio techado y aulas con ventilación cenital.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Hormigón armado", "Albañilería de ladrillo", "Acero"]
  },
  {
    "id": "edificio-intendencia-regional-tarapaca",
    "nombre_proyecto": "Edificio de la Intendencia Regional de Tarapacá",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Arturo Prat 1099, Iquique",
    "coordenadas": {"lat": -20.2150, "lng": -70.1540},
    "ano_diseno": "1978",
    "anos_construccion": "1979-1980",
    "ano_inauguracion": "1980",
    "estilos": ["Racionalismo Institucional", "Brutalismo"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Sede del gobierno regional caracterizada por su imponente estructura de hormigón armado visto con potentes voladizos y amplias galerías cívicas frente a la rada portuaria.",
    "fuente_url": "https://www.goretarapaca.gov.cl",
    "materiales_principales": ["Hormigón armado visto", "Vidrio de seguridad", "Granito"]
  },
  {
    "id": "hotel-terrado-cavancha-iquique",
    "nombre_proyecto": "Hotel Terrado Cavancha",
    "arquitecto": "Arquitectos Hoteleros del Norte",
    "arquitecto_principal": "Oficina Técnica Hotelera",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Calle Aeropuerto con Playa Cavancha, Iquique",
    "coordenadas": {"lat": -20.2295, "lng": -70.1470},
    "ano_diseno": "1993",
    "anos_construccion": "1994-1995",
    "ano_inauguracion": "1995",
    "estilos": ["Arquitectura Turística Costera"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Hito del boom turístico y de la Zona Franca (ZOFRI), con torre curvilínea que optimiza las vistas al mar y terrazas escalonadas con piscinas panorámicas.",
    "fuente_url": "https://www.terrado.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio reflectivo", "Piedra reconstituida"]
  },
  {
    "id": "estadio-tierra-de-campeones-iquique",
    "nombre_proyecto": "Estadio Tierra de Campeones Ramón Estay Saavedra",
    "arquitecto": "Dirección de Arquitectura MOP / Valle & Cornejo Arquitectos",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Salvador Allende con Tadeo Haenke, Iquique",
    "coordenadas": {"lat": -20.2442, "lng": -70.1347},
    "ano_diseno": "2016",
    "anos_construccion": "2017-2020",
    "ano_inauguracion": "2020",
    "estilos": ["Contemporáneo Deportivo", "Estructura Tensada"],
    "programa": ["Deportivo"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Reconstrucción integral de estándar FIFA para 13.000 espectadores con membrana tensada de PTFE continua que protege a las graderías de la alta radiación solar del desierto.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Membrana tensada PTFE", "Acero estructural galvanizado", "Hormigón prefabricado"]
  },
  {
    "id": "piscina-alcalde-godoy-iquique",
    "nombre_proyecto": "Piscina Alcalde Godoy",
    "arquitecto": "Municipalidad de Iquique",
    "arquitecto_principal": "Ingeniería Municipal",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Cavancha, Iquique",
    "coordenadas": {"lat": -20.2315, "lng": -70.1465},
    "ano_diseno": "1963",
    "anos_construccion": "1964-1965",
    "ano_inauguracion": "1965",
    "estilos": ["Movimiento Moderno Deportivo"],
    "programa": ["Deportivo"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Complejo deportivo acuático clásico que albergó los torneos nacionales de waterpolo y natación de la era dorada deportiva de Iquique.",
    "fuente_url": "https://www.municipioiquique.cl",
    "materiales_principales": ["Hormigón armado", "Mosaico veneciano", "Tuberías de bronce"]
  },
  {
    "id": "edificio-consistorial-alto-hospicio",
    "nombre_proyecto": "Edificio Consistorial de Alto Hospicio",
    "arquitecto": "Dirección de Arquitectura MOP / Municipalidad de Alto Hospicio",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Ramón Pérez Opazo 3125, Alto Hospicio",
    "coordenadas": {"lat": -20.2740, "lng": -70.1080},
    "ano_diseno": "2010",
    "anos_construccion": "2011-2012",
    "ano_inauguracion": "2012",
    "estilos": ["Contemporáneo Institucional"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Alto Hospicio",
    "pais": "Chile",
    "descripcion": "Edificio cívico municipal en la meseta de la pampa a 600 metros de altitud sobre Iquique. Incorpora una plaza cívica techada con celosías de acero corten que proyectan sombras dinámicas.",
    "fuente_url": "https://www.maho.cl",
    "materiales_principales": ["Hormigón visto", "Acero corten", "Muro cortina"]
  },
  {
    "id": "edificio-registro-civil-iquique",
    "nombre_proyecto": "Edificio del Registro Civil e Identificación de Iquique",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sotomayor 735, Iquique",
    "coordenadas": {"lat": -20.2185, "lng": -70.1485},
    "ano_diseno": "2006",
    "anos_construccion": "2007-2008",
    "ano_inauguracion": "2008",
    "estilos": ["Contemporáneo Institucional"],
    "programa": ["Institucional / Gubernamental"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Edificio público con atrio vidriado a triple altura, celosías de aluminio y distribución espacial diáfana orientada a la atención ciudadana masiva.",
    "fuente_url": "https://www.registrocivil.cl",
    "materiales_principales": ["Hormigón armado", "Aluminio", "Vidrio laminado"]
  },

  # 5. Arquitectura Contemporánea, Infraestructura y Proyectos en Desierto (15)
  {
    "id": "centro-cultural-alto-hospicio",
    "nombre_proyecto": "Centro Cultural de Alto Hospicio",
    "arquitecto": "Dirección de Arquitectura MOP / Gubbins Arquitectos",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Los Tamarugos con Los Naranjos, Alto Hospicio",
    "coordenadas": {"lat": -20.2710, "lng": -70.1020},
    "ano_diseno": "2014",
    "anos_construccion": "2015-2016",
    "ano_inauguracion": "2016",
    "estilos": ["Contemporáneo", "Infraestructura Cultural Pública"],
    "programa": ["Cultura"],
    "ciudad": "Alto Hospicio",
    "pais": "Chile",
    "descripcion": "Complejo cultural con teatro de 300 butacas, salas de artes visuales y talleres comunitarios. Su volumetría facetada de hormigón pigmentado rinde homenaje a los estratos geológicos de la cordillera de la Costa.",
    "fuente_url": "https://www.maho.cl",
    "materiales_principales": ["Hormigón pigmentado color tierra", "Madera acústica", "Acero"]
  },
  {
    "id": "paso-fronterizo-colchane",
    "nombre_proyecto": "Complejo Fronterizo Colchane",
    "arquitecto": "Dirección de Arquitectura MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta 15-CH, Frontera Chile-Bolivia, Colchane",
    "coordenadas": {"lat": -19.2770, "lng": -68.6400},
    "ano_diseno": "2016",
    "anos_construccion": "2017-2018",
    "ano_inauguracion": "2018",
    "estilos": ["Arquitectura en Climas Extremos", "Contemporáneo"],
    "programa": ["Infraestructura Fronteriza"],
    "ciudad": "Colchane",
    "pais": "Chile",
    "descripcion": "Complejo de control migratorio y aduanero erigido a 3.700 msnm en el corazón del altiplano aymara. Cuenta con sistema de calefacción solar pasiva, estructura antisísmica pesada y cubiertas para nevadas intensas.",
    "fuente_url": "https://www.pasosfronterizos.gov.cl",
    "materiales_principales": ["Acero estructural", "Paneles sandwich aislados", "Hormigón armado"]
  },
  {
    "id": "cesfam-pedro-pulgar-alto-hospicio",
    "nombre_proyecto": "Centro de Salud Familiar Pedro Pulgar",
    "arquitecto": "Servicio de Salud Iquique / MOP",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Los Cóndores 3201, Alto Hospicio",
    "coordenadas": {"lat": -20.2780, "lng": -70.0980},
    "ano_diseno": "2013",
    "anos_construccion": "2014-2015",
    "ano_inauguracion": "2015",
    "estilos": ["Contemporáneo de Salud"],
    "programa": ["Salud"],
    "ciudad": "Alto Hospicio",
    "pais": "Chile",
    "descripcion": "Infraestructura sanitaria de atención primaria de gran escala con patios interiores bioclimáticos y celosías de protección contra el polvo del desierto.",
    "fuente_url": "https://www.saludtarapaca.gob.cl",
    "materiales_principales": ["Hormigón armado", "Cerámica sanitaria", "Vidrio de control solar"]
  },
  {
    "id": "mirador-de-chusmiza",
    "nombre_proyecto": "Mirador de Chusmiza",
    "arquitecto": "MOP / Comunidad Indígena de Chusmiza-Usmagama",
    "arquitecto_principal": "Arquitectos de Paisaje MOP",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Ruta 15-CH Km 75, Huara",
    "coordenadas": {"lat": -19.6800, "lng": -69.1800},
    "ano_diseno": "2013",
    "anos_construccion": "2014",
    "ano_inauguracion": "2014",
    "estilos": ["Intervención de Paisaje Andino"],
    "programa": ["Espacio Público / Mirador"],
    "ciudad": "Huara",
    "pais": "Chile",
    "descripcion": "Balcón voladizo de piedra y acero sobre la quebrada termal de Chusmiza, concebido con muros pircados tradicionales y paneles informativos astronómicos y geológicos.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Piedra volcánica", "Acero galvanizado", "Madera nativa"]
  },
  {
    "id": "liceo-bicentenario-minero-juan-pablo-ii",
    "nombre_proyecto": "Liceo Bicentenario Minero Juan Pablo II",
    "arquitecto": "Fundación Educacional Collahuasi / MOP",
    "arquitecto_principal": "Equipo de Infraestructura Educacional",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. La Pampa 3500, Alto Hospicio",
    "coordenadas": {"lat": -20.2820, "lng": -70.0950},
    "ano_diseno": "2012",
    "anos_construccion": "2013-2014",
    "ano_inauguracion": "2014",
    "estilos": ["Contemporáneo Educacional Minero"],
    "programa": ["Educación"],
    "ciudad": "Alto Hospicio",
    "pais": "Chile",
    "descripcion": "Campus técnico minero con simuladores industriales, cubiertas con paneles solares y pabellones organizados en torno a patios con microclimas sombreados.",
    "fuente_url": "https://www.collahuasi.cl",
    "materiales_principales": ["Hormigón armado", "Estructura metálica", "Lamas parasol de aluminio"]
  },
  {
    "id": "hospital-de-alto-hospicio",
    "nombre_proyecto": "Hospital de Alto Hospicio",
    "arquitecto": "Dirección de Arquitectura MOP / Sacyr",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Las Parcelas con Los Álamos, Alto Hospicio",
    "coordenadas": {"lat": -20.2650, "lng": -70.0890},
    "ano_diseno": "2018",
    "anos_construccion": "2019-2023",
    "ano_inauguracion": "2023",
    "estilos": ["Contemporáneo Hospitalario de Alta Complejidad"],
    "programa": ["Salud"],
    "ciudad": "Alto Hospicio",
    "pais": "Chile",
    "descripcion": "Mega obra hospitalaria de 40.000 m² con aisladores sísmicos elastoméricos de última generación, helipuerto y envolvente bioclimática para eficiencia energética en la pampa.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Aisladores sísmicos", "Hormigón armado", "Fachada ventilada de paneles de resina"]
  },
  {
    "id": "escuela-poblados-rurales-huara",
    "nombre_proyecto": "Escuela de Poblados Rurales de Huara",
    "arquitecto": "MOP / Municipalidad de Huara",
    "arquitecto_principal": "Arquitectos Bioclimáticos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Poblado de Huara",
    "coordenadas": {"lat": -19.9950, "lng": -69.7710},
    "ano_diseno": "2017",
    "anos_construccion": "2018",
    "ano_inauguracion": "2018",
    "estilos": ["Bioclimático Andino"],
    "programa": ["Educación"],
    "ciudad": "Huara",
    "pais": "Chile",
    "descripcion": "Infraestructura rural que utiliza muros de inercia térmica, captadores solares y patios cubiertos para acoger alumnos de las comunidades aymaras del Tamarugal.",
    "fuente_url": "https://www.mop.gob.cl",
    "materiales_principales": ["Bloque térmico", "Madera tratada", "Policarbonato"]
  },
  {
    "id": "terminal-aereo-diego-aracena-ampliacion",
    "nombre_proyecto": "Terminal Aéreo Internacional Diego Aracena (Ampliación)",
    "arquitecto": "Dirección de Aeropuertos MOP / Concesiones",
    "arquitecto_principal": "Dirección de Aeropuertos MOP",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Aeropuerto Diego Aracena, 45 km al sur de Iquique",
    "coordenadas": {"lat": -20.5352, "lng": -70.1812},
    "ano_diseno": "2019",
    "anos_construccion": "2020-2022",
    "ano_inauguracion": "2022",
    "estilos": ["Contemporáneo", "Infraestructura de Transporte"],
    "programa": ["Transporte"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Ampliación integral que duplicó la capacidad del aeropuerto, con nueva torre de control, puentes de embarque vidriados panorámicos y cubiertas que simulan la duna del Cerro Dragón.",
    "fuente_url": "https://www.aeropuertodeiquique.cl",
    "materiales_principales": ["Acero estructural", "Muro cortina DVH", "Aluminio compuesto"]
  },
  {
    "id": "paseo-costero-maritimo-cavancha",
    "nombre_proyecto": "Paseo Costero Marítimo Cavancha",
    "arquitecto": "Municipalidad de Iquique / MOP",
    "arquitecto_principal": "Dirección de Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Borde Costero de Playa Cavancha, Iquique",
    "coordenadas": {"lat": -20.2285, "lng": -70.1475},
    "ano_diseno": "2003",
    "anos_construccion": "2004-2005",
    "ano_inauguracion": "2005",
    "estilos": ["Espacio Público Costero", "Paisajismo Litoral"],
    "programa": ["Espacio Público / Borde Costero"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Eje urbano de la vida al aire libre en Iquique, con senderos peatonales, palmeras, ciclovías continuas y anfiteatro natural para conciertos junto a la rompiente de olas.",
    "fuente_url": "https://www.municipioiquique.cl",
    "materiales_principales": ["Hormigón estampado", "Madera marina", "Piedra granítica"]
  },
  {
    "id": "paseo-peatonal-bellavista-iquique",
    "nombre_proyecto": "Paseo Peatonal Bellavista",
    "arquitecto": "MOP Obras Portuarias",
    "arquitecto_principal": "MOP Obras Portuarias",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Bellavista y El Morro, Iquique",
    "coordenadas": {"lat": -20.2100, "lng": -70.1570},
    "ano_diseno": "2017",
    "anos_construccion": "2018",
    "ano_inauguracion": "2018",
    "estilos": ["Diseño Urbano del Borde Costero"],
    "programa": ["Espacio Público"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Recuperación del borde costero del histórico barrio El Morro, con miradores hacia el puerto pesquero, luminarias solares y accesos universales a las caletas.",
    "fuente_url": "https://www.dop.cl",
    "materiales_principales": ["Hormigón armado con inhibidores de corrosión", "Acero galvanizado", "Piedra"]
  },
  {
    "id": "edificio-pampa-uta-iquique",
    "nombre_proyecto": "Edificio Pampa de la Universidad de Tarapacá (Sede Iquique)",
    "arquitecto": "Universidad de Tarapacá / MOP",
    "arquitecto_principal": "Arquitectos Universitarios",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Av. Luis Emilio Recabarren 2477, Iquique",
    "coordenadas": {"lat": -20.2520, "lng": -70.1320},
    "ano_diseno": "2009",
    "anos_construccion": "2010",
    "ano_inauguracion": "2010",
    "estilos": ["Contemporáneo Universitario"],
    "programa": ["Educación"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Sede académica concebida con pabellones de hormigón a la vista y celosías metálicas orientadas que optimizan la luz natural sin sobrecalentar las aulas.",
    "fuente_url": "https://www.uta.cl",
    "materiales_principales": ["Hormigón armado", "Vidrio", "Aluminio"]
  },
  {
    "id": "centro-de-arte-yilam-pica",
    "nombre_proyecto": "Centro de Arte Yilam",
    "arquitecto": "Estudio Oasis & Desierto",
    "arquitecto_principal": "Arquitectos Locales de Pica",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Camino a las Termas de Cocha Resbaladero, Pica",
    "coordenadas": {"lat": -20.4930, "lng": -69.3280},
    "ano_diseno": "2018",
    "anos_construccion": "2019",
    "ano_inauguracion": "2019",
    "estilos": ["Vernáculo Contemporáneo de Oasis"],
    "programa": ["Cultura"],
    "ciudad": "Pica",
    "pais": "Chile",
    "descripcion": "Espacio cultural levantado entre huertos de cítricos y mangos con muros de tierra apisonada y techos enramados de caña y algarrobo.",
    "fuente_url": "https://www.pica.cl",
    "materiales_principales": ["Tierra apisonada", "Madera de algarrobo", "Caña brava"]
  },
  {
    "id": "residencia-adulto-mayor-alto-hospicio",
    "nombre_proyecto": "Residencia de Adulto Mayor Alto Hospicio",
    "arquitecto": "Dirección de Arquitectura MOP / SENAMA",
    "arquitecto_principal": "MOP Arquitectura",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector La Pampa, Alto Hospicio",
    "coordenadas": {"lat": -20.2760, "lng": -70.0930},
    "ano_diseno": "2016",
    "anos_construccion": "2017",
    "ano_inauguracion": "2017",
    "estilos": ["Contemporáneo Asistencial"],
    "programa": ["Social / Salud"],
    "ciudad": "Alto Hospicio",
    "pais": "Chile",
    "descripcion": "Residencia geriátrica pública diseñada en una sola planta sin desniveles, con patios interiores sombreados y huertos terapéuticos protegidos del viento.",
    "fuente_url": "https://www.senama.gob.cl",
    "materiales_principales": ["Albañilería confinada", "Madera laminada", "Hormigón"]
  },
  {
    "id": "puerto-patache-collahuasi",
    "nombre_proyecto": "Complejo Portuario Patache (Minera Doña Inés de Collahuasi)",
    "arquitecto": "Ingeniería Portuaria e Industrial Internacional",
    "arquitecto_principal": "Bechtel / Collahuasi",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Punta Patache, 65 km al sur de Iquique",
    "coordenadas": {"lat": -20.8030, "lng": -70.1920},
    "ano_diseno": "1996",
    "anos_construccion": "1997-1998",
    "ano_inauguracion": "1998",
    "estilos": ["Arquitectura Industrial de Gran Escala"],
    "programa": ["Industrial / Portuario"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Terminal marítimo donde concluye el mineroducto de 203 km desde la cordillera a 4.400 msnm. Cuenta con planta de filtrado, domo de concentrado y muelle mecanizado sobre el océano.",
    "fuente_url": "https://www.collahuasi.cl",
    "materiales_principales": ["Estructura espacial de acero", "Hormigón de alta resistencia marina", "Domo geodésico"]
  },
  {
    "id": "planta-desaladora-quebrada-blanca",
    "nombre_proyecto": "Planta Desaladora Quebrada Blanca Fase 2 (QB2)",
    "arquitecto": "Teck Resources / Bechtel Infrastructure",
    "arquitecto_principal": "Ingeniería de Desalación",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Puerto Punta Patache Sur, Iquique",
    "coordenadas": {"lat": -20.8250, "lng": -70.1850},
    "ano_diseno": "2019",
    "anos_construccion": "2020-2022",
    "ano_inauguracion": "2022",
    "estilos": ["Infraestructura Hídrica Contemporánea"],
    "programa": ["Industrial / Hídrico"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Megaplanta de osmosis inversa con capacidad de 1.000 l/s que bombea agua de mar desalinizada hasta los 4.400 msnm de la mina, liberando los acuíferos continentales del Tamarugal.",
    "fuente_url": "https://www.teck.com",
    "materiales_principales": ["Membranas poliméricas", "Acero súper dúplex", "Hormigón masivo"]
  },

  # 6. Casas Contemporáneas, Refugios y Arquitectura Vernácula (11)
  {
    "id": "casa-en-cavancha-iquique",
    "nombre_proyecto": "Casa en Cavancha",
    "arquitecto": "Taller de Arquitectura Costera",
    "arquitecto_principal": "Arquitectos Iquique",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Península de Cavancha, Iquique",
    "coordenadas": {"lat": -20.2320, "lng": -70.1485},
    "ano_diseno": "2007",
    "anos_construccion": "2008",
    "ano_inauguracion": "2008",
    "estilos": ["Costero Contemporáneo"],
    "programa": ["Residencial"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Residencia unifamiliar que dialoga con los requeríos mediante terrazas de hormigón blanco y carpintería de maderas que resisten la bruma marina.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Hormigón blanco", "Madera teca", "Vidrio templado"]
  },
  {
    "id": "casa-pica-oasis",
    "nombre_proyecto": "Casa Pica",
    "arquitecto": "Estudio Tierra & Luz",
    "arquitecto_principal": "Arquitectura de Oasis",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Quisma, Pica",
    "coordenadas": {"lat": -20.4850, "lng": -69.3400},
    "ano_diseno": "2011",
    "anos_construccion": "2012",
    "ano_inauguracion": "2012",
    "estilos": ["Vernáculo Contemporáneo"],
    "programa": ["Residencial"],
    "ciudad": "Pica",
    "pais": "Chile",
    "descripcion": "Vivienda inmersa en huertos de guayabas y naranjas, construida con mampostería de piedra volcánica liparita y vigas a la vista de pino oregón recuperado.",
    "fuente_url": "https://www.plataformaarquitectura.cl",
    "materiales_principales": ["Piedra liparita", "Pino oregón", "Vidrio"]
  },
  {
    "id": "cabanas-oasis-de-pica",
    "nombre_proyecto": "Cabañas Oasis de Pica",
    "arquitecto": "Ecoturismo Tamarugal",
    "arquitecto_principal": "Constructores del Valle",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Camino a Miraflores, Pica",
    "coordenadas": {"lat": -20.4920, "lng": -69.3350},
    "ano_diseno": "2014",
    "anos_construccion": "2015",
    "ano_inauguracion": "2015",
    "estilos": ["Turismo Sustentable"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "Pica",
    "pais": "Chile",
    "descripcion": "Cabañas ecológicas con piscinas alimentadas por agua de socavón andino tradicional y cubiertas vegetales de sombra.",
    "fuente_url": "https://www.sernatur.cl",
    "materiales_principales": ["Adobe estabilizado", "Madera", "Caña"]
  },
  {
    "id": "casa-tres-marias-matilla",
    "nombre_proyecto": "Casa Tres Marías",
    "arquitecto": "Taller Regional Pica",
    "arquitecto_principal": "Arquitectos Asociados",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Oasis de Matilla, Pica",
    "coordenadas": {"lat": -20.5120, "lng": -69.3620},
    "ano_diseno": "2015",
    "anos_construccion": "2016",
    "ano_inauguracion": "2016",
    "estilos": ["Contemporáneo de Desierto"],
    "programa": ["Residencial"],
    "ciudad": "Pica",
    "pais": "Chile",
    "descripcion": "Casa de campo estructurada alrededor de tres patios que canalizan las corrientes de aire fresco provenientes de los manantiales de agua subterránea.",
    "fuente_url": "https://www.arquitour.com",
    "materiales_principales": ["Ladrillo cocido", "Hormigón visto", "Madera"]
  },
  {
    "id": "casa-tres-cabezas-huara",
    "nombre_proyecto": "Casa Tres Cabezas",
    "arquitecto": "Estudio Desierto Profundo",
    "arquitecto_principal": "Arquitectura del Desierto",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Huara Rural",
    "coordenadas": {"lat": -19.9900, "lng": -69.7650},
    "ano_diseno": "2018",
    "anos_construccion": "2019",
    "ano_inauguracion": "2019",
    "estilos": ["Minimalismo en el Desierto"],
    "programa": ["Residencial"],
    "ciudad": "Huara",
    "pais": "Chile",
    "descripcion": "Tres volúmenes monolíticos ciegos hacia el viento del desierto y abiertos hacia patios protegidos mediante ventanales retranqueados.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Hormigón pigmentado", "Piedra local", "Vidrio templado"]
  },
  {
    "id": "refugio-en-mamina-termas",
    "nombre_proyecto": "Refugio en Mamiña",
    "arquitecto": "Comunidad Indígena de Mamiña",
    "arquitecto_principal": "Maestros Canteros de Mamiña",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Baños Ipla, Mamiña, Pozo Almonte",
    "coordenadas": {"lat": -20.0730, "lng": -69.2150},
    "ano_diseno": "2013",
    "anos_construccion": "2014",
    "ano_inauguracion": "2014",
    "estilos": ["Arquitectura Termal Andina"],
    "programa": ["Hotelero / Salud"],
    "ciudad": "Pozo Almonte",
    "pais": "Chile",
    "descripcion": "Baños termales y refugio construidos en torno a pozas naturales de aguas sulfurosas milenarias con muros ciclópeos de piedra rosada liparita.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra liparita rosada", "Madera de chañar", "Agua termal"]
  },
  {
    "id": "casa-playa-tres-islas-iquique",
    "nombre_proyecto": "Casa Playa Tres Islas",
    "arquitecto": "Estudio Litoral Norte",
    "arquitecto_principal": "Arquitectura Marina",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Borde Costero Sur, Playa Tres Islas, Iquique",
    "coordenadas": {"lat": -20.3500, "lng": -70.1400},
    "ano_diseno": "2016",
    "anos_construccion": "2017",
    "ano_inauguracion": "2017",
    "estilos": ["Costero Contemporáneo"],
    "programa": ["Residencial"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Vivienda suspendida sobre pilotes frente al oleaje del Pacífico sur con terrazas voladas y cerramientos de celosías corredizas.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Hormigón armado marino", "Madera impregnada", "Vidrio"]
  },
  {
    "id": "casa-en-los-verdes-iquique",
    "nombre_proyecto": "Casa en Los Verdes",
    "arquitecto": "Taller Costero Iquique",
    "arquitecto_principal": "Arquitectos de Playa",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Caleta Los Verdes Km 25, Iquique",
    "coordenadas": {"lat": -20.4050, "lng": -70.1600},
    "ano_diseno": "2010",
    "anos_construccion": "2011",
    "ano_inauguracion": "2011",
    "estilos": ["Arquitectura de Borde Costero"],
    "programa": ["Residencial"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Residencia de fin de semana que conjuga la tradición pesquera artesanal con volúmenes limpios de hormigón y cubiertas sombreadas.",
    "fuente_url": "https://www.colegiodearquitectos.cl",
    "materiales_principales": ["Hormigón", "Piedra de mar", "Aluminio"]
  },
  {
    "id": "casa-campo-canchones-pozo-almonte",
    "nombre_proyecto": "Casa de Campo Canchones",
    "arquitecto": "Estudio Pampa del Tamarugal",
    "arquitecto_principal": "Arquitectura Rural",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Estación Experimental Canchones, Pozo Almonte",
    "coordenadas": {"lat": -20.4400, "lng": -69.6100},
    "ano_diseno": "2017",
    "anos_construccion": "2018",
    "ano_inauguracion": "2018",
    "estilos": ["Bioclimático de Pampa"],
    "programa": ["Residencial / Investigación"],
    "ciudad": "Pozo Almonte",
    "pais": "Chile",
    "descripcion": "Casa de investigación agrícola en medio del bosque de tamarugos con ventilación geotérmica subterránea y captación de neblina matinal (camanchaca).",
    "fuente_url": "https://www.unap.cl",
    "materiales_principales": ["Madera de tamarugo tratada", "Tierra estabilizada", "Malla atrapanieblas"]
  },
  {
    "id": "cabanas-huayquique-iquique",
    "nombre_proyecto": "Cabañas Huayquique",
    "arquitecto": "Constructora Playa Sur",
    "arquitecto_principal": "Arquitectos de Surf",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Sector Playa Huayquique, Iquique",
    "coordenadas": {"lat": -20.2720, "lng": -70.1360},
    "ano_diseno": "2005",
    "anos_construccion": "2006",
    "ano_inauguracion": "2006",
    "estilos": ["Arquitectura de Playa"],
    "programa": ["Hotelero / Turístico"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Complejo de cabañas sobre los roqueríos frente a la ola de surf de Huayquique, con amplias cubiertas de madera marina.",
    "fuente_url": "https://www.sernatur.cl",
    "materiales_principales": ["Madera tratada", "Hormigón", "Zinc"]
  },
  {
    "id": "casa-chanavayita-iquique",
    "nombre_proyecto": "Casa Chanavayita",
    "arquitecto": "Estudio Costero Sur",
    "arquitecto_principal": "Arquitectos Litorales",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Caleta Chanavayita, 50 km al sur de Iquique",
    "coordenadas": {"lat": -20.6900, "lng": -70.1700},
    "ano_diseno": "2014",
    "anos_construccion": "2015",
    "ano_inauguracion": "2015",
    "estilos": ["Arquitectura Costera Contemporánea"],
    "programa": ["Residencial"],
    "ciudad": "Iquique",
    "pais": "Chile",
    "descripcion": "Vivienda frente a la bahía abrigada de Chanavayita, con ventanales corredizos integrales y plataformas de solárium.",
    "fuente_url": "https://www.archdaily.cl",
    "materiales_principales": ["Hormigón visto", "Pino impregnado", "Cristal templado"]
  },

  # 7. Asentamientos Precolombinos y Vernáculos de la Pampa y Altiplano (11)
  {
    "id": "pukara-de-la-huayca-pozo-almonte",
    "nombre_proyecto": "Pukara de La Huayca",
    "arquitecto": "Pobladores Prehispánicos del Tamarugal",
    "arquitecto_principal": "Constructores de la Pampa",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Oasis de La Huayca, Pozo Almonte",
    "coordenadas": {"lat": -20.4200, "lng": -69.5800},
    "ano_diseno": "Siglo XIV",
    "anos_construccion": "1350-1450",
    "ano_inauguracion": "Siglo XIV",
    "estilos": ["Arquitectura Defensiva Prehispánica"],
    "programa": ["Arqueológico"],
    "ciudad": "Pozo Almonte",
    "pais": "Chile",
    "descripcion": "Asentamiento fortificado en medio del bosque de tamarugos que controlaba el cruce de caravanas de sal y charqui hacia la costa.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Troncos de algarrobo y tamarugo", "Barro", "Piedra"]
  },
  {
    "id": "aldea-de-guatacondo-pozo-almonte",
    "nombre_proyecto": "Aldea de Guatacondo",
    "arquitecto": "Cultura Complejo Guatacondo (Período Formativo)",
    "arquitecto_principal": "Pobladores Arcaicos de Guatacondo",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Quebrada de Guatacondo, Pozo Almonte",
    "coordenadas": {"lat": -20.9250, "lng": -69.2150},
    "ano_diseno": "800 a.C.",
    "anos_construccion": "800 a.C. - 200 d.C.",
    "ano_inauguracion": "800 a.C.",
    "estilos": ["Arquitectura Arcaica en Barro Batido", "Monumento Nacional"],
    "programa": ["Arqueológico / Aldea"],
    "ciudad": "Pozo Almonte",
    "pais": "Chile",
    "descripcion": "Monumento Histórico Nacional. Una de las aldeas agrícolas sedentarias más tempranas de América del Sur. Más de 100 recintos circulares de barro batido moldeado a mano con una plaza ceremonial central de 60 metros de diámetro.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Mortero de barro batido", "Madera de algarrobo", "Cañas"]
  },
  {
    "id": "aldea-de-caserones-tarapaca",
    "nombre_proyecto": "Aldea de Caserones",
    "arquitecto": "Cultura Tarapacá Precolombina",
    "arquitecto_principal": "Constructores de Quebradas",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Quebrada de Tarapacá, Huara",
    "coordenadas": {"lat": -19.9100, "lng": -69.5800},
    "ano_diseno": "1000 a.C.",
    "anos_construccion": "1000 a.C. - 1000 d.C.",
    "ano_inauguracion": "1000 a.C.",
    "estilos": ["Arquitectura Formativa en Barro y Quincha"],
    "programa": ["Arqueológico / Aldea"],
    "ciudad": "Huara",
    "pais": "Chile",
    "descripcion": "Gran aldea habitacional amurallada del período formativo con recintos rectangulares de quincha y barro con silos subterráneos para maíz y frejoles.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Quincha", "Barro", "Piedra", "Algarrobo"]
  },
  {
    "id": "gigante-de-tarapaca-cerro-unita",
    "nombre_proyecto": "Gigante de Tarapacá y Entorno Urbano de Cerro Unita",
    "arquitecto": "Cultura Aymara / Tarapacá",
    "arquitecto_principal": "Sacerdotes y Astrónomos Andinos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Cerro Unita, 15 km al noreste de Huara",
    "coordenadas": {"lat": -19.9480, "lng": -69.6330},
    "ano_diseno": "Siglo XI",
    "anos_construccion": "1000-1400",
    "ano_inauguracion": "Siglo XI",
    "estilos": ["Hito Territorial", "Geoglifo Monumental"],
    "programa": ["Arqueológico / Territorial"],
    "ciudad": "Huara",
    "pais": "Chile",
    "descripcion": "El geoglifo con figura humana más grande del planeta (86 metros de altura), concebido como hito de orientación territorial y calendario astronómico para los caravaneros transandinos.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra de cerro oscura", "Suelo caliche claro desescombrado"]
  },
  {
    "id": "poblado-historico-de-pica",
    "nombre_proyecto": "Poblado Histórico de Pica",
    "arquitecto": "Comunidad de Pica y Españoles",
    "arquitecto_principal": "Habitantes del Oasis",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Casco Histórico del Oasis de Pica",
    "coordenadas": {"lat": -20.4890, "lng": -69.3310},
    "ano_diseno": "Siglo XVI",
    "anos_construccion": "Siglos XVI-XIX",
    "ano_inauguracion": "1580",
    "estilos": ["Zona Típica", "Arquitectura de Oasis"],
    "programa": ["Urbanismo Patrimonial"],
    "ciudad": "Pica",
    "pais": "Chile",
    "descripcion": "Zona Típica. Excepcional trama urbana de oasis colonial regada por galerías filtrantes subterráneas de socavón incaico, con casonas de dos pisos con miradores de madera.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Pino oregón", "Adobe", "Piedra liparita", "Barro"]
  },
  {
    "id": "poblado-historico-de-matilla",
    "nombre_proyecto": "Poblado Histórico de Matilla",
    "arquitecto": "Vitivinicultores de Matilla",
    "arquitecto_principal": "Comunidad Colonial",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Oasis de Matilla, Comuna de Pica",
    "coordenadas": {"lat": -20.5130, "lng": -69.3600},
    "ano_diseno": "Siglo XVII",
    "anos_construccion": "Siglos XVII-XIX",
    "ano_inauguracion": "1650",
    "estilos": ["Trama Urbana Tradicional de Oasis"],
    "programa": ["Urbanismo Patrimonial"],
    "ciudad": "Pica",
    "pais": "Chile",
    "descripcion": "Pueblo oasis célebre por sus lagares coloniales subterráneos de piedra donde se prensaba el mosto del vino y sus callejones sombreados por centenarios mangos.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra liparita", "Adobe", "Algarrobo"]
  },
  {
    "id": "aldea-de-cariquima-colchane",
    "nombre_proyecto": "Aldea de Cariquima",
    "arquitecto": "Comunidad Aymara de Cariquima",
    "arquitecto_principal": "Pastores Altiplánicos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Valle de Cariquima, Colchane",
    "coordenadas": {"lat": -19.4700, "lng": -68.8300},
    "ano_diseno": "Siglo XIX",
    "anos_construccion": "Siglo XIX",
    "ano_inauguracion": "1860",
    "estilos": ["Arquitectura Altiplánica Ganadera"],
    "programa": ["Vernáculo"],
    "ciudad": "Colchane",
    "pais": "Chile",
    "descripcion": "Centro tradicional textil y ganadero a 3.800 msnm con viviendas de piedra volcánica sin labrar asentadas en barro y techos a cuatro aguas de paja brava.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra volcánica", "Barro", "Paja brava", "Madera de queñoa"]
  },
  {
    "id": "aldea-ceremonial-de-isluga",
    "nombre_proyecto": "Aldea Ceremonial de Isluga",
    "arquitecto": "Comunidad Indígena Aymara de Isluga",
    "arquitecto_principal": "Comunidad Aymara",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Parque Nacional Volcán Isluga, Colchane",
    "coordenadas": {"lat": -19.2550, "lng": -68.7050},
    "ano_diseno": "Siglo XVIII",
    "anos_construccion": "Siglo XVIII",
    "ano_inauguracion": "1750",
    "estilos": ["Centro Ceremonial Andino", "Monumento Nacional"],
    "programa": ["Religioso / Ceremonial"],
    "ciudad": "Colchane",
    "pais": "Chile",
    "descripcion": "Pueblo sagrado deshabitado durante el año que sólo cobra vida en las festividades religiosas y de machaq mara (año nuevo andino). Su iglesia blanca resplandece al pie del volcán activo Isluga.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra volcánica encalada", "Paja brava", "Madera de queñoa"]
  },
  {
    "id": "poblado-de-tarapaca",
    "nombre_proyecto": "Poblado Histórico de Tarapacá",
    "arquitecto": "Españoles y Pueblos Andinos",
    "arquitecto_principal": "Habitantes de la Quebrada",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Quebrada de Tarapacá, Huara",
    "coordenadas": {"lat": -19.9250, "lng": -69.5100},
    "ano_diseno": "1536",
    "anos_construccion": "Siglos XVI-XIX",
    "ano_inauguracion": "1540",
    "estilos": ["Zona Típica", "Trama Urbana Colonial"],
    "programa": ["Urbanismo Patrimonial"],
    "ciudad": "Huara",
    "pais": "Chile",
    "descripcion": "El pueblo histórico más antiguo del norte grande chileno, visitado por Diego de Almagro en 1536. Posee casas coloniales de gruesos adobes con patios de parrones y canales de piedra.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Adobe masivo", "Piedra", "Madera nativa", "Barro"]
  },
  {
    "id": "lagunillas-asentamiento-ganadero",
    "nombre_proyecto": "Lagunillas (Asentamiento Ganadero Altiplánico)",
    "arquitecto": "Pastores de Camélidos",
    "arquitecto_principal": "Comunidad Pastoril",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Altiplano de Pozo Almonte / Pica",
    "coordenadas": {"lat": -20.6500, "lng": -68.9500},
    "ano_diseno": "Siglo XIX",
    "anos_construccion": "Siglo XIX",
    "ano_inauguracion": "1870",
    "estilos": ["Arquitectura Pastoril Andina"],
    "programa": ["Vernáculo"],
    "ciudad": "Pozo Almonte",
    "pais": "Chile",
    "descripcion": "Caserío de altura con corrales de piedra pircada y pequeñas chozas de pastoreo destinadas a la protección durante la esquila de alpacas.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra seca", "Barro", "Paja brava"]
  },
  {
    "id": "poblado-pisagua-viejo",
    "nombre_proyecto": "Poblado Histórico de Pisagua Viejo",
    "arquitecto": "Pescadores Changos y Mineros Coloniales",
    "arquitecto_principal": "Pobladores Históricos",
    "ano_pritzker": None,
    "fotografia_url": "",
    "direccion": "Desembocadura de la Quebrada de Tana, Huara",
    "coordenadas": {"lat": -19.5700, "lng": -70.1900},
    "ano_diseno": "Siglo XVII",
    "anos_construccion": "Siglos XVII-XIX",
    "ano_inauguracion": "1650",
    "estilos": ["Asentamiento Costero Histórico"],
    "programa": ["Arqueológico / Histórico"],
    "ciudad": "Huara",
    "pais": "Chile",
    "descripcion": "Asentamiento primigenio de Pisagua antes de su traslado al puerto salitrero. Conserva ruinas de caleta pesquera, fundición de minerales y vestigios de la ocupación prehispánica de desembocadura.",
    "fuente_url": "https://www.monumentos.gob.cl",
    "materiales_principales": ["Piedra canteada", "Mortero de barro con conchuela", "Madera"]
  }
]

with open("data_tarapaca_part1.json", "r", encoding="utf-8") as f:
  p1 = json.load(f)

total_tarapaca = p1 + obras_tarapaca_p2
print(f"Total works in Tarapacá: {len(total_tarapaca)}")

with open("data_tarapaca_100.json", "w", encoding="utf-8") as f:
  json.dump(total_tarapaca, f, ensure_ascii=False, indent=2)

print("Saved data_tarapaca_100.json successfully!")
